moveit_core/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_planners/chomp/chomp_interface/CMakeLists.txt
moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt
moveit_ros/visualization/trajectory_rviz_plugin/CMakeLists.txt

We're only 2 commits behind, but i wanted to test the waters now. How I did this:
```
git clone git@github.com:ros-planning/moveit
git remote add davetcoleman2 git@github.com:davetcoleman/moveit2
git push davetcoleman2 melodic-devel
```
This allows my fork of moveit2 to have the latest ``melodic-devel`` branch. Then using Github's interface I created a PR from ``melodic-devel`` to ``master``

Sync melodic-devel to moveit2/master

---

moveit_core/logging/include/moveit/logging/logging.h

See https://github.com/ros-planning/moveit2/pull/2#discussion_r258234915

Fix missing namespace for logging.h

---

moveit_core/CMakeLists.txt
moveit_kinematics/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
moveit_planners/ompl/CMakeLists.txt
moveit_ros/benchmarks/CMakeLists.txt
moveit_ros/manipulation/CMakeLists.txt
moveit_ros/move_group/CMakeLists.txt
moveit_ros/perception/CMakeLists.txt
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/robot_interaction/CMakeLists.txt
moveit_ros/visualization/CMakeLists.txt
moveit_ros/warehouse/CMakeLists.txt
moveit_setup_assistant/CMakeLists.txt

Rather than doing these for each package individually, e.g. https://github.com/ros-planning/moveit2/pull/10#discussion_r259637946
See http://www.ros.org/reps/rep-2000.html
This assumes we will not be building ROS2 on 16.04, which from my understanding ROS2 isn't really supported there.

Increase CMake version to 3.10.2 per REP 2000 for Ubuntu Bionic / Crystal

---

.docker/ci/Dockerfile
.docker/source/Dockerfile

This augments https://github.com/ros-planning/moveit2/pull/57 to successfully build the source docker image: Sourcing the ROS underlay was missing.
Also, I cleaned up the ci docker image as originally promised my Mike in https://github.com/ros-planning/moveit2/pull/46#event-2228195081.
As can be seen [here](https://cloud.docker.com/u/moveit/repository/docker/moveit/moveit2/builds), the source docker image wasn't yet built.

Cleaning up Docker

---

moveit_core/background_processing/CMakeLists.txt
moveit_core/background_processing/src/background_processing.cpp

- Change the name of the logger 
- library as shared

moveit_core background processing - 

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/kinematics_plugin_loader/CMakeLists.txt
moveit_ros/planning/kinematics_plugin_loader/include/moveit/kinematics_plugin_loader/kinematics_plugin_loader.h
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

This is a continuation of [PR#74](https://github.com/ros-planning/moveit2/pull/74)
I did the same as in this [PR#104](https://github.com/ros-planning/moveit2/pull/104) for applying the changes

Port kinematics_plugin_loader to ROS2 

---

moveit2.repos

https://github.com/ros-planning/moveit_msgs/pull/62 is merged, so we can use the upstream branch as dependency

Use upstream version of moveit_msgs

---

moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp
moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h
moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/kinematics_base/src/kinematics_base.cpp
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

Adding a node as a parameter for the initialize function of kienamtics_base otherwise, the kinematics plugins will segfault due to using a null node, this's related to the moveit_kinematics [PR](https://github.com/ros-planning/moveit2/pull/128) 

Fix node uninitialized bug

---

.docker/ci-testing/Dockerfile
.docker/ci/Dockerfile
.docker/release/Dockerfile
.docker/source/Dockerfile

I switched to eloquent as default right away as we are dropping support for dashing in the future.

Upgrade docker images to ROS 2 Eloquent

---

moveit_ros/planning/kinematics_plugin_loader/CMakeLists.txt
moveit_ros/planning/package.xml

The reason why I added `moveit_rdf_loader` and `moveit_kinematics_plugin_loader` in `target_link_libraries` because they don't have a `*Config.cmake` file, after making `moveit_kinematics_plugin_loader` library `SHARED` I got some weird linking errors fixed them by adding the dependencies from the same package in `target_link_libraries`
[ament_target_dependencies reference](https://github.com/ament/ament_cmake/blob/master/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake)

Re-enable moveit_ros_planning & CMakeLists fixes

---

.docker/source/Dockerfile

This should fix the docker build, compiling with `--symlink-install` flag causes moveit_core library targets to not get installed in `moveit_core/lib` folder (they will get installed directly in `moveit_core` folder, which causes errors about finding its libraries
[occupancy_map_monitor](https://github.com/ros-planning/moveit2/pull/148) should be merged first, otherwise rosdep will complain `moveit_ros_planning: Cannot locate rosdep definition for [moveit_ros_occupancy_map_monitor]`

Fixing docker

---

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h

This line was deleted in the kinematics_base port, this PR restore it -- this's needed for the moveit_kinematics unit tests to pass

Kinematics base: lookup param default value fix

---

moveit_ros/occupancy_map_monitor/CMakeLists.txt
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/package.xml
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp
moveit_ros/occupancy_map_monitor/src/occupancy_map_updater.cpp

#112 is blocked by `occupancy_map_monitor`, please see https://github.com/ros-planning/moveit2/blob/fa81678b965eafcb1e8c72018ba4d99ab2593255/moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h#L45
This work followed AcutronicRobotics' porting, but didn't use the original commits. Because `occupancy_map_monitor` was moved from `moveit_ros` to `moveit_ros_perception`([ref](https://github.com/AcutronicRobotics/moveit2/tree/master/moveit_ros/perception/occupancy_map_monitor)), the original commits are very difficult to directly use.

Port occupancy_map_monitor to ROS2

---

moveit_ros/planning/planning_scene_monitor/CMakeLists.txt

This PR intends to fix the linking issue of planning_scene_monitor: seems two non-ROS-package dependencies `moveit_robot_model_loader` and `moveit_collision_plugin_loader` are missing, which resulted in [errors](https://travis-ci.org/ros-planning/moveit2/jobs/643203147#L495) when compiling `trajectory_execution_manager`.

Fix linking issue of planning_scene_monitor

---

moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/common_planning_interface_objects/CMakeLists.txt
moveit_ros/planning_interface/common_planning_interface_objects/include/moveit/common_planning_interface_objects/common_objects.h
moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp
moveit_ros/planning_interface/package.xml

This's essential for `moveit_ros_visualization` port, but it's blocked by planning_scene_monitor
TODO:

Port common_planning_interface_objects

---

moveit_core/controller_manager/include/moveit/controller_manager/controller_manager.h
moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/follow_joint_trajectory_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/package.xml
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp
moveit_ros/planning/trajectory_execution_manager/test/test_moveit_controller_manager.h

Port moveit_simple_controller_manager

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/planning_components_tools/CMakeLists.txt
moveit_ros/planning/planning_components_tools/src/display_random_state.cpp
moveit_ros/planning/planning_components_tools/src/evaluate_collision_checking_speed.cpp
moveit_ros/planning/planning_components_tools/src/evaluate_state_operations_speed.cpp
moveit_ros/planning/planning_components_tools/src/kinematics_speed_and_validity_evaluator.cpp
moveit_ros/planning/planning_components_tools/src/print_planning_model_info.cpp
moveit_ros/planning/planning_components_tools/src/print_planning_scene_info.cpp
moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp
moveit_ros/planning/planning_components_tools/src/visualize_robot_collision_volume.cpp

This's a partial port the other executable need porting planning scene monitor first
For the multi-threading section, I used the method [here](https://github.com/ros2/rclcpp/issues/335)

Port planning components tools

---

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/common_planning_interface_objects/CMakeLists.txt
moveit_ros/visualization/CMakeLists.txt
moveit_ros/visualization/planning_scene_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt

This fixes the undefined symbol error we were getting when loading the RobotState rviz2 plugin
Now loading RobotState plugin gives, which I think is related to rdf_loader (not sure)
```
Thread 1 "rviz2" received signal SIGSEGV, Segmentation fault.
0x00007ffff65af330 in rclcpp::Node::has_parameter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /opt/ros/eloquent/lib/librclcpp.so
```
And loading PlanningSene plugin gives  
```
[INFO] [moveit_rdf_loader.rdf_loader]: Robot model parameter not found! Did you remap 'robot_description'?
[ERROR] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Robot model not loaded
```
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel …

Fix moveit visualization

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp

This fixes two bugs
1- Using the name of the SceneNode was throwing an exception in the destructor [see Mike's comment](https://github.com/ros-planning/moveit2/pull/167/files#r375475440)
2- Having an empty robot description will pass an empty string to rdf_loader which will cause it to throw an `empty parameter name` exception

MoveIt visualization bug fixes

---

moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp

While testing out moveit2 I was unable to configure a planner, so I addressing a couple TODOs necessary for ompl parameter loading to work.
1. Depth=1 was always returning an empty set. depth=2 returned all my parameters
2. The parameters from ros come with full namespace eg. it gives `MAIN.planner_configs.RRTConnectkConfigDefault.type`, so stripping off all but the last piece is necessary before caching. (I didn't see an existing way to do this)

OMPL Parameter Loading

---

moveit2.repos

This should fix failing CI (see #199). Apparently the `ros2-devel` branch of `joint_state_publsher` doesn't exist anymore. I switched it to `ros2`. Not sure if we might want to switch to `eloquent` with the release branch in the future.

Update joint_state_publisher dependency

---

README.md

Per https://github.com/rosin-project/press_kit

Add ROSin as sponsor of MoveIt 2, move source build instructions

---

.clang-tidy
doc/MIGRATION_GUIDE.md
moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_distance_field_types.h
moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
moveit_core/distance_field/include/moveit/distance_field/distance_field.h
moveit_core/distance_field/src/distance_field.cpp
moveit_core/exceptions/src/exceptions.cpp
moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp
moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp
moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.h
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/ogre_helpers/mesh_shape.hpp
moveit_ros/visualization/rviz_plugin_render_tools/src/mesh_shape.cpp

Applied clang-tidy-fix over the full codebase to fix master branch CI.
I disabled `performance-unnecessary-value-param` to suppress fixes for callback functions (see #214), merely adding NOLINT really clutters up the code a lot as there are many multi-line functions.

Apply missing clang-tidy fixes

---

.travis.yml
moveit_kinematics/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py
moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
moveit_kinematics/test/test_ikfast_plugins.sh

eigen_conversion isn't ported yet to ROS2 so I copied the needed function and dropped its dependency
I tested it with panda robot steps are as follow [Source](https://ros-planning.github.io/moveit_tutorials/doc/ikfast/ikfast_tutorial.html)
1- clone https://github.com/JafarAbdi/panda_moveit_config/tree/ros2
2- cd moveit_resources/panda_description/urdf
3- ros2 run moveit_kinematics auto_create_ikfast_moveit_plugin.sh panda.urdf panda_arm panda_link0 panda_link8
4- now move the generated package to the main source path and recompile (the generated package name is panda_panda_arm_ikfast_plugin)

Port Ikfast kinematics solver

---

moveit_core/CMakeLists.txt
moveit_core/background_processing/CMakeLists.txt
moveit_core/collision_detection/CMakeLists.txt
moveit_core/collision_detection_fcl/CMakeLists.txt
moveit_core/collision_distance_field/CMakeLists.txt
moveit_core/constraint_samplers/CMakeLists.txt
moveit_core/distance_field/CMakeLists.txt
moveit_core/exceptions/CMakeLists.txt
moveit_core/kinematic_constraints/CMakeLists.txt
moveit_core/kinematics_base/CMakeLists.txt
moveit_core/planning_scene/CMakeLists.txt
moveit_core/robot_model/CMakeLists.txt
moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_trajectory/CMakeLists.txt
moveit_core/trajectory_processing/CMakeLists.txt
moveit_core/transforms/CMakeLists.txt
moveit_core/utils/CMakeLists.txt
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/collision_plugin_loader/CMakeLists.txt
moveit_ros/planning/planning_pipeline/CMakeLists.txt
moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt

Started looking into dependency issues with the Foxy branch and ended up cleaning up most of the dependencies.

Cleanup CMakeLists target dependencies

---

.docker/ci-testing/Dockerfile
.docker/ci/Dockerfile
.docker/release/Dockerfile
.docker/source/Dockerfile
.travis.yml
moveit2.repos
moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h
moveit_core/collision_detection/src/collision_matrix.cpp
moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp
moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h
moveit_core/package.xml
moveit_core/robot_state/src/robot_state.cpp
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp_fake_controller.launch.py
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_mimic_svd.hpp
moveit_kinematics/package.xml
moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp
moveit_kinematics/test/CMakeLists.txt
moveit_ros/benchmarks/CMakeLists.txt
moveit_ros/benchmarks/src/BenchmarkExecutor.cpp
moveit_ros/planning_interface/package.xml

Once #226 is merged, I will branch off `foxy` and retarget this PR, generate docker images and trigger CI.

Compile on ROS2 Foxy

---

moveit_core/trajectory_processing/CMakeLists.txt

Enable missing unit test in moveit_core package as part of [#216](https://github.com/ros-planning/moveit2/issues/216)

Enable "test_time_optimal_trajectory_generation" unit test

---

moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_mimic_svd.hpp

Otherwise the build fails for `osrf/ros2:nightly` (Ubuntu 20.04) due to the unimplemented virtual function.
Related: https://github.com/ros-planning/moveit2/pull/233

Simplify kdl now that kinetic support is dropped

---

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Executes internal timer callback using a Single Threaded Executor, this is an attempt to mimic the ROS1 behavior that used an Asynch Spinner and an internal Callback Queue to manage the timer callback invocation.  Need some guidance on how best to test this.

Planning Scene Monitor Node Executor

---

moveit_ros/moveit_servo/include/moveit_servo/servo.h
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/teleop_demo/joystick_servo_example.cpp
moveit_ros/moveit_servo/test/test_servo_interface.cpp
moveit_ros/moveit_servo/test/unit_test_servo_calcs.cpp
moveit_ros/moveit_servo/test/unit_test_servo_calcs.hpp

Some changes to the tests to hopefully make them less flaky
1. Integration testing: remove the StaleCommandStop test, and instead add that check to the end of SendJointCommand test
2. Unit testing: Change the ServoCalcs unit test to use shared pointers for the ROS node, planning scene monitor, and Servo parameters so they are only loaded at the start of the unit tests instead of for each individual test
3. Minor change to the teleop demo to use a thread to add the collision objects instead of a future
4. Minor spelling corrections

[Servo] Fixes to Servo tests/demos

---

moveit_core/collision_distance_field/test/test_collision_distance_field.cpp

This was missing from #247, the `ASSERT_TRUE` was succeeding randomly.

Fixup moveit_resources usage in moveit_core test

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Solves #252. I can change the actual node name if desired. The output of the `ros2 node list` during the demo is now

Fix duplicate nodes from planning scene monitor private node

---

moveit_ros/moveit_servo/test/servo_launch_test_common.hpp

I think these changes should make the tests in moveit_servo more robust.
This is based on my theory that the reason we are seeing failures like this: https://travis-ci.com/github/ros-planning/moveit2/jobs/378055726 is that we are locking up the cpu polling for start service to be ready and once we start doing that we stop loading new librarids in the composable node and the start service is never ready and we get a timeout.

Poll for service slower in testing to make moveit_servo tests more robust

---

moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

All parameters are triggering the parameter callback in the PSM node, which results in the PSM rejecting parameters from moveit_servo. I'm not sure if this fix is a good long-term solution, but for now exclusive parameters in the PSM are declared for the private node. Eventually, we might want to reimplement the PSM as a composable node which would allow a cleaner separation.
Additionally, 0a98d55 should fix some warnings with the moveit_servo tests, @AdamPettinger does this make sense to you?

Fix psm/servo parameter conflict

---

moveit2.repos

The [docker build for moveit/moveit2:eloquent-ci is broken](https://hub.docker.com/repository/registry-1.docker.io/moveit/moveit2/builds/ec58a1f2-d86e-4e2f-89c2-510b40f4f93a), because it was still referencing to master branch.

moveit2.repos: fix branch to eloquent

---

moveit2.repos
moveit_ros/moveit_servo/doc/servo_tutorial.md
moveit_ros/moveit_servo/launch/servo_server_demo.launch.py
moveit_ros/moveit_servo/launch/servo_teleop.launch.py
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py

This resets `ros2_controllers` to the last version that worked with FakeJoint and Servo. We'll switch to the latest versions once there are stable APIs. Also, since the last ros2 package sync, running the component nodes in Servo would throw an InvalidServiceNameException becaues the namespace parameter in the launch files were undefined. Setting them to root "/" fixes this. @AdamPettinger

Fix Servo runtime issues

---

moveit2.repos
moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py
moveit_ros/visualization/CMakeLists.txt
moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_context.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_scenes.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_states.cpp
moveit_ros/visualization/package.xml
moveit_ros/warehouse/CMakeLists.txt
moveit_ros/warehouse/package.xml
moveit_ros/warehouse/warehouse/CMakeLists.txt
moveit_ros/warehouse/warehouse/include/moveit/warehouse/moveit_message_storage.h
moveit_ros/warehouse/warehouse/src/broadcast.cpp
moveit_ros/warehouse/warehouse/src/constraints_storage.cpp
moveit_ros/warehouse/warehouse/src/import_from_text.cpp
moveit_ros/warehouse/warehouse/src/initialize_demo_db.cpp
moveit_ros/warehouse/warehouse/src/moveit_message_storage.cpp
moveit_ros/warehouse/warehouse/src/planning_scene_storage.cpp
moveit_ros/warehouse/warehouse/src/planning_scene_world_storage.cpp
moveit_ros/warehouse/warehouse/src/save_as_text.cpp
moveit_ros/warehouse/warehouse/src/save_to_warehouse.cpp
moveit_ros/warehouse/warehouse/src/state_storage.cpp
moveit_ros/warehouse/warehouse/src/trajectory_constraints_storage.cpp
moveit_ros/warehouse/warehouse/src/warehouse_connector.cpp
moveit_ros/warehouse/warehouse/src/warehouse_services.cpp

This PR intends to port moveit_ros_warehouse to ROS2.
- Depends on [warehouse_ros PR#48](https://github.com/ros-planning/warehouse_ros/pull/48) and [warehouse_ros_mongo PR#38](https://github.com/ros-planning/warehouse_ros_mongo/pull/38).
- Run tests:
- `ros2 launch run_move_group run_move_group.launch.py`
- On `Context` tab of motion planning rviz panel, click `connect` button to connect to the mongodb server.
- Please try save robot states or planning scene to the database in their own rviz tabs.

Port moveit_ros_warehouse

---

moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/perception/CMakeLists.txt
moveit_ros/perception/depth_image_octomap_updater/CMakeLists.txt
moveit_ros/perception/depth_image_octomap_updater_plugin_description.xml
moveit_ros/perception/lazy_free_space_updater/CMakeLists.txt
moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp
moveit_ros/perception/mesh_filter/CMakeLists.txt
moveit_ros/perception/package.xml
moveit_ros/perception/point_containment_filter/CMakeLists.txt
moveit_ros/perception/point_containment_filter/include/moveit/point_containment_filter/shape_mask.h
moveit_ros/perception/point_containment_filter/src/shape_mask.cpp
moveit_ros/perception/pointcloud_octomap_updater/CMakeLists.txt
moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.h
moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp
moveit_ros/perception/pointcloud_octomap_updater_plugin_description.xml
moveit_ros/perception/semantic_world/CMakeLists.txt
moveit_ros/perception/semantic_world/include/moveit/semantic_world/semantic_world.h
moveit_ros/perception/semantic_world/src/semantic_world.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

This PR intends to port moveit_ros_perception to ROS2.
The sensors parameter yaml file following the pattern of [this comment](https://github.com/ros-planning/moveit2/pull/148#discussion_r360469027):
```yaml
/**:
ros__parameters:
sensors:  ["sensor1", "sensor2"]
sensor1:
sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
point_cloud_topic: /head_mount_kinect/depth_registered/points
max_range: 5.0
point_subsample: 1
padding_offset: 0.1
padding_scale: 1.0
max_update_rate: 1.0
filtered_cloud_topic: filtered_cloud
sensor2:
sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
image_topic: /head_mount_kinect/depth_registered/image_raw
queue_size: 5
near_clipping_plane_distance: 0.3
far_clipping_plane_distance: 5.0
shadow_threshold: 0.2
padding_scale: 4.0
padding_offset: 0.03 …
```

Porting moveit_ros_perception/pointcloud_octomap_updater

---

moveit_ros/moveit_servo/package.xml

Some tests in moveit_servo were failing because the package
fake_joint_driver was not found.
@tylerjw 

Add fake_joint_driver test_depend

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

By setting the timeout to infinity ensures the move group interface
is will be ready to use. This change is simply a ros2 migration
change.

Server timeout set to infinity

---

moveit_ros/hybrid_planning/global_planner/include/moveit/global_planner/global_planner_component.h
moveit_ros/hybrid_planning/global_planner/src/global_planner_component.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/include/moveit/hybrid_planning_manager/planner_logic_interface.h
moveit_ros/hybrid_planning/hybrid_planning_manager/src/hybrid_planning_manager.cpp
moveit_ros/hybrid_planning/local_constraint_solver_plugins/include/moveit/local_constraint_solver_plugins/decelerate_before_collision.h
moveit_ros/hybrid_planning/local_constraint_solver_plugins/src/decelerate_before_collision.cpp
moveit_ros/hybrid_planning/local_planner/include/moveit/local_planner/local_constraint_solver_interface.h
moveit_ros/hybrid_planning/local_planner/include/moveit/local_planner/trajectory_operator_interface.h
moveit_ros/hybrid_planning/local_planner/src/local_planner_component.cpp
moveit_ros/hybrid_planning/package.xml
moveit_ros/hybrid_planning/planner_logic_plugins/include/moveit/planner_logic_plugins/replan_invalidated_trajectory.h
moveit_ros/hybrid_planning/planner_logic_plugins/include/moveit/planner_logic_plugins/single_plan_execution.h
moveit_ros/hybrid_planning/planner_logic_plugins/src/replan_invalidated_trajectory.cpp
moveit_ros/hybrid_planning/planner_logic_plugins/src/single_plan_execution.cpp
moveit_ros/hybrid_planning/test/hybrid_planning_test_node.cpp
moveit_ros/hybrid_planning/trajectory_operator_plugins/include/moveit/trajectory_operator_plugins/next_waypoint_sampler.h
moveit_ros/hybrid_planning/trajectory_operator_plugins/src/next_waypoint_sampler.cpp

Fixes addressing mostly MoveIt best practices. @sjahr

Pr hybrid planning review

---

moveit_ros/moveit_servo/src/teleop_demo/joystick_servo_example.cpp
moveit_ros/moveit_servo/test/publish_fake_jog_commands.cpp

Fixes #321 by setting the right service topics in the demo clients.

Fix 'start_servo' service topic in demo

---

moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp

Tiny change. Due to wrong ordering of two lines in `MoveItCpp::loadPlanningPipelines` the function will return false when no planning pipelines are present, without logging this specific message.

Solved small issue with a message not being logged due to early return 

---

moveit_core/controller_manager/include/moveit/controller_manager/controller_manager.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.cpp

Bug fixes in main branch

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/test/test_parameter_struct.hpp

Fixes two bugs:
1- Constructing a duration from a double by using `rclcpp::Duration::from_seconds` otherwise the values will cast to int
2- In `insertRedundantPointsIntoTrajectory` function we were starting from the third point, not the second one, so I fixed the index in the for-loop

moveit servo: fix constructing duration from double & fix bug in insertRedundantPointsIntoTrajectory function

---

moveit_common/CMakeLists.txt
moveit_common/cmake/moveit_package.cmake
moveit_common/moveit_common-extras.cmake

This enables (and fixes up issues found by) these linters in the `moveit_common` package:
ament_copyright

Enable linting for moveit_common package

---

.docker/ci-testing/Dockerfile
.docker/ci/Dockerfile

As you can see in https://travis-ci.com/github/ros-planning/moveit_task_constructor/jobs/489509921 having `ROS_WS` is causing the overlay ws to be installed on top of the underlay hence compiling the underlay again

Remove ROS_WS env variable from foxy-ci which is causing the overlay to be installed on top of the underlay

---

.pre-commit-config.yaml
CODE_OF_CONDUCT.md
doc/MIGRATION_GUIDE.md
moveit_demo_nodes/run_move_group/README.md
moveit_demo_nodes/run_moveit_cpp/README.md
moveit_demo_nodes/run_moveit_cpp/config/moveit_cpp.yaml
moveit_demo_nodes/run_ompl_constrained_planning/README.md
moveit_experimental/collision_distance_field_ros/mainpage.dox
moveit_experimental/kinematics_cache/v1/kinematics_cache/mainpage.dox
moveit_planners/pilz_industrial_motion_planner/doc/.gitignore
moveit_planners/pilz_industrial_motion_planner/doc/MotionBlendAlgorithmDescription.tex
moveit_planners/pilz_industrial_motion_planner/test/test_robots/prbt/launch/test_context.launch
moveit_planners/pilz_industrial_motion_planner_testutils/doc/diagrams/diag_class_circ_auxiliary.uxf
moveit_planners/pilz_industrial_motion_planner_testutils/doc/diagrams/diag_class_commands.uxf
moveit_planners/pilz_industrial_motion_planner_testutils/doc/diagrams/diag_seq_testdataloader_usage.uxf
moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch.py
moveit_ros/benchmarks/examples/demo_panda_predefined_poses.yaml
moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py
moveit_ros/move_group/default_capabilities_plugin_description.xml
moveit_ros/moveit_servo/doc/running_the_demos.md
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/test/config/collision_start_positions.yaml
moveit_ros/moveit_servo/test/config/singularity_start_positions.yaml
moveit_ros/moveit_servo/test/launch/test_servo_integration.test.py
moveit_ros/planning/planning_request_adapters_plugin_description.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_controller_manager.launch.xml

This adds a step to the pre-commit test to fix trailing whitespace.  This is one more awesome feature that can cut down on having to fix these through code review comments.

Add fix trailing whitespace check

---

moveit_ros/hybrid_planning/CMakeLists.txt
moveit_ros/hybrid_planning/forward_trajectory_plugin.xml
moveit_ros/hybrid_planning/local_constraint_solver_plugins/CMakeLists.txt
moveit_ros/hybrid_planning/local_constraint_solver_plugins/include/moveit/local_constraint_solver_plugins/forward_trajectory.h
moveit_ros/hybrid_planning/local_constraint_solver_plugins/src/forward_trajectory.cpp
moveit_ros/hybrid_planning/package.xml

This PR adds a local solver plugin to the hybrid planning architecture, that simply forwards the local solution trajectory-point-wise to the underlying controller.

Add forward_trajectory local solver plugin

---

.docker/source/Dockerfile

This's a bug introduced by my previous PR, I forgot to change the directory before building causing the `install`, `build`, and `log` folders to be inside `src`

Fix build directory for foxy-source image

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h

Port [this commit](https://github.com/ros-planning/moveit/pull/2528) from MoveIt1 to MoveIt2

Update doxygen comments for distance() and interpolate()

---

moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h

CI is failing for not being able to find `boost::optional` [see](https://github.com/ros-planning/moveit2/pull/310/checks?check_run_id=2230312292#step:7:450)
```
/home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h:193:10: error: ‘optional’ in namespace ‘boost’ does not name a template type; did you mean ‘conditional’?
```

Include optional in pose_tracking

---

moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_ompl_constrained_planning/launch/run_move_group.launch.py
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/launch/servo_cpp_interface_demo.launch.py
moveit_ros/moveit_servo/launch/servo_server_demo.launch.py
moveit_ros/moveit_servo/launch/servo_teleop.launch.py
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py

Fix: https://github.com/ros-planning/moveit2/issues/399
Use the newly merged spawner https://github.com/ros-controls/ros2_control/pull/310 to load the controllers

Update launch files to use ros2 control spawner

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

We found out the hard way, when the suddenHalt() function was called for a robot in velocity control mode, it would send a command vector of all-zero positions. That could cause a really big joint jump depending what type of ros2_controller is active. This fixes that.
Also (really minor fix) it sets trajectory accelerations to 0 to match the comment.

Servo: do not cause a joint jump when SuddenHalt() is called

---

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

Joint position, velocity, and accleration parameter limits
where not declared in the `robot_model_loader`. This prevented
the use of joint limits. 

Declare joint limit parameters

---

moveit_demo_nodes/run_move_group/CMakeLists.txt

Fixes #384 and #415. 
run_moveit_cpp was already fixed by a previous commit.
run_move_group_interface now correctly launches but does nothing? I am not sure what it supposed to do. @JafarAbdi can you check it

Fix node install directory in run_move_group

---

moveit_demo_nodes/run_move_group/launch/run_move_group.rviz
moveit_demo_nodes/run_ompl_constrained_planning/launch/run_move_group.rviz
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit.rviz

Related to #417, @JafarAbdi and I discussed and looked for solutions. We tried to add ~/ to the nodes though these result in a namespace of move_group_private which we thought would have to change and break quite a bit of stuff. So we thought to leave it the way it is right now and removed move_group namespaces from the relevant files. @henningkayser can you check if it makes sense, or we still want the private node stuff?
If you approve I will send a PR to moveit2_tutorials and moveit_resources related to this. I've tested this with run_move_group, run_moveit_cpp and quickstart rviz (didn't send a PR for this one yet) all seem to work fine.

Remove move_group namespace

---

moveit_core/CMakeLists.txt
moveit_core/package.xml
moveit_core/robot_model/CMakeLists.txt
moveit_ros/visualization/CMakeLists.txt

The ros2 build is failing because it can't find `angles.h` for the robot_model [see](https://build.ros2.org/job/Fdev__moveit__ubuntu_focal_amd64/lastBuild/console), this PR fixes it & exports `rviz_common` `rviz_default_plugins` for moveit_ros_visualization

Fix robot_model & moveit_ros_visualization dependencies

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/test/pose_tracking_test.cpp
moveit_ros/moveit_servo/test/test_servo_interface.cpp
moveit_ros/moveit_servo/test/test_servo_singularity.cpp
moveit_ros/moveit_servo/test/unit_test_servo_calcs.cpp
moveit_ros/planning_interface/test/move_group_ompl_constraints_test.cpp

Ongoing attempt to see what is going with the tests and fixing it

Re-re-enable servo tests.

---

moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
moveit_ros/moveit_servo/CMakeLists.txt

This PR replaces the last remaining  ament_export_libraries() macro calls with ament_export_targets()
I've experienced trouble with missing include directories when trying to use the moveit_servo library in another package. 
To reproduce, try to add
```
#include <moveit_servo/servo.h>
```
to a header file in a package outside of the moveit_servo package (with moveit_servo properly set up as CMake dependency).
When trying to build the package I got the error:
```
fatal error: moveit_servo/servo.h: No such file or directory
```
The problem seemed to be caused by the usage of the "ament_export_libraries" macro which [seems to be outdated](https://answers.ros.org/question/331089/ament_export_dependenciesboost-not-working/?answer=332460#post-id-332460) and replaced (#372 ) in most of moveit2's …

Replace last ament_export_libraries macro calls

---

moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp

Previously the following parameters were not being loaded at all `projection_evaluator` `longest_valid_segment_fraction` `enforce_joint_model_state_space` `enforce_constrained_state_space`
This PR 
1- Fix the parameter prefix
2- Fix the exception being throw by calling `node_->get_parameter(param_name, ...)` due to types mismatch

Fix parameter name & Fix exception about parameter type

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

A small fix to correct logger frequencies.
Prior to this, the messages only printed once.
main branch, message only prints once:  (This is a gif, but nothing changes)
With this PR, prints every 3s:

Fix Servo logging frequency

---

moveit_core/robot_model/src/revolute_joint_model.cpp
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

Previously, the incoming robot state velocity was used to check if the robot would move beyond the joint limit. That was a problem if the robot state did not contain velocity data, i.e. if "copy dynamics" hadn't been turned on.
This PR uses the prospective robot velocity from Servo itself to check if the joint would move beyond the position limit and halt, if so. This velocity should always be available regardless of whether "copy dynamics" is ON.

Improvement on Servo enforcePositionLimits()

---

moveit_planners/ompl/ompl_interface/CMakeLists.txt
moveit_planners/ompl/ompl_interface/src/detail/threadsafe_state_storage.cpp
moveit_planners/ompl/ompl_interface/test/test_threadsafe_state_storage.cpp

This issue is documented in #453 .
I removed line 66 of  /moveit_planners/ompl/ompl_interface/src/detail/threadsafe_state_storage.cpp
`st->setToDefaultValues();`
It seems to me that this line should not be there as it negates intention of intializing the robot state the line before:
`
st = new moveit::core::RobotState(start_state_)
`
I have also added a unit-test for this.

Removed code that sets default values in threadsafe_state_storage.cpp to robot state and added unittests

---

moveit_core/collision_detection_bullet/src/collision_detector_bullet_plugin_loader.cpp
moveit_core/collision_detection_fcl/src/collision_detector_fcl_plugin_loader.cpp
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

This fixes how PlanningScene diffs are created and managed (replaces #463 and #456).
https://github.com/ros-planning/moveit2/pull/364 introduced a bug where a child scene would not copy-construct the collision environments so that it wouldn't include any of the parent's link geometries or attached objects. The link geometries aren't that bad because they would be constructed from the robot model anyway, but there was no way to sync back the attached objects. This PR fixes that by providing a private allocate function that allows passing the parent detector which implements the old behavior. I tested this and it fixes #429 and #407 for me. I didn't test #444 yet.
However, there is still a bug (or irritation) where the start state of the MotionPlanningPanel doesn't include the attached …

Fix PlanningScene CollisionDetector diff handling

---

moveit_core/package.xml

Jenkins is failing otherwise:
https://build.ros2.org/job/Fbin_uF64__moveit_core__ubuntu_focal_amd64__binary/

[moveit_core] Add pluginlib dependency

---

moveit_planners/ompl/ompl_interface/CMakeLists.txt

Disable actually failing flaky OMPL test that causes CI failures all over moveit2. See https://github.com/ros-planning/moveit2/runs/2798018498?check_suite_focus=true for a sample output.

Disable actually failing flaky OMPL test

---

.github/workflows/build_and_test_galactic.yaml
.github/workflows/build_and_test_rolling.yaml
README.md
moveit2_galactic.repos
moveit2_rolling.repos
moveit_core/CMakeLists.txt
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp
moveit_ros/planning/trajectory_execution_manager/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/robot_interaction/src/robot_interaction.cpp

Enables CI for Rolling and Galactic distros. Will fix https://github.com/ros-controls/ros2_controllers/pull/200 from the repos file once it gets merged. The extra repos and CI files for rolling and galactic will be removed once ros2_control and ros2_controllers are released for rolling and galactic and synced (for main repos).

Enable Rolling and Galactic CI

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Replace: https://github.com/ros-planning/moveit2/pull/493
Fix: https://github.com/ros-planning/moveit2/issues/503

Fix stopping the TrajectoryExecutionManager's execution

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

The Motion planning plugin currently ignores parameters for warehouse_ros,
because they are not declared yet.
This can be verified by launching `ros2 launch run_move_group run_move_group.launch.py`
(where some warehouse parameters like `warehouse_plugin` have to be defined before)
and examinig the parameters with `ros2 param dump rviz2`.

[visualization] declare warehouse params in rviz plugin

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

moveit_servo is segfaulting when reaching limits if `publish_joint_velocities` set to `false`. the reason is in [ServoCalcs::enforcePositionLimits](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/moveit_servo/src/servo_calcs.cpp#L780) we do access the velocities despite being an empty vector [see](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/moveit_servo/src/servo_calcs.cpp#L810-L813)

moveit_servo: Fix segfault when publish_joint_velocities set to false and a joint is close to position limit

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection_bullet/CMakeLists.txt
moveit_core/collision_detector_bullet_description.xml

Addresses issue #473
Removed the BULLET_ENABLE flag
Properly installs the bullet collision plugin

Removed the BULLET_ENABLE flag

---

moveit_ros/warehouse/CMakeLists.txt
moveit_ros/warehouse/package.xml
moveit_ros/warehouse/warehouse/CMakeLists.txt

prerelease on Rolling was failing in my fork with current master with SSL errors: https://github.com/vatanaksoytezer/moveit2/runs/2909420963?check_suite_focus=true
I just applied the same solution with https://github.com/ros-planning/warehouse_ros_mongo/pull/63. Now I can confirm that pre-release is passing on Rolling https://github.com/vatanaksoytezer/moveit2/runs/2909699212?check_suite_focus=true.
Galactic prerelease still fails because of geometric shapes failing on Galactic in buildfarm due to a bloom issue I suppose (see https://build.ros2.org/job/Gsrc_uF__geometric_shapes__ubuntu_focal__source/12/console)

Clean OpenSSL dependencies

---

moveit_ros/move_group/src/move_group.cpp

Fix: https://github.com/ros-planning/moveit2/issues/522
We only enter this else statement when `default_planning_pipeline` is empty which will cause to not load any planning pipeline

move_group: Fix default_planning_pipeline for deprecated behavior

---

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

These were accidentally removed during the port to ROS2 due to an ambiguous
`TODO: remove when melodic is no longer supported`
Closes #535 .

add persistent planner support back

---

moveit_core/collision_detection_bullet/src/collision_detector_bullet_plugin_loader.cpp
moveit_kinematics/cached_ik_kinematics_plugin/README.md
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.h
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_service.cpp
moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp
moveit_planners/pilz_industrial_motion_planner/src/planning_context_loader_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/planning_context_loader_lin.cpp
moveit_planners/pilz_industrial_motion_planner/src/planning_context_loader_ptp.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_planning_context_loaders.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_ptp.cpp

Link to the proper pluginlib headers. See [this deprecation warning](https://github.com/ros/pluginlib/blob/galactic/pluginlib/include/pluginlib/class_loader.h#L36)

Pluginlib Deprecation Fix

---

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

Fix the second point of https://github.com/ros-planning/moveit2/issues/541

Fix urdf joint limits being overridden when no joint_limits parameter is loaded

---

moveit_ros/moveit_servo/include/moveit_servo/collision_check.h

If the Servo collision check parameter is set to `false`, `CollisionCheck`'s `rclcpp::TimerBase::SharedPtr` `timer_` member is never initialized. Since `~CollisionCheck()` calls `timer_->cancel()`, requesting that Servo start if collision checking was not enabled causes a crash.
This fixes the crash by checking if `timer_` was actually set before trying to cancel it.

Fix crash if MoveIt Servo collision check is disabled

---

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
moveit_core/collision_distance_field/src/collision_env_distance_field.cpp
moveit_core/robot_state/src/conversions.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_core/utils/src/robot_model_test_utils.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

Fixed some format string errors in logging macros.

Fix some format strings

---

moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h

The informational message referred to the default value even though the parameter was changed internally.

Fixed message when parameter was found

---

moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_ros/planning/planning_request_adapters_plugin_description.xml

Pulling some changes out of #571 so they can be merged separately.
- Document some limitations of TOTG in the plugin description.
- Minor code cleanup.
- Mark iterative spline and iterative parabola plugins as deprecated since they have some known issues (https://github.com/ros-planning/moveit/issues/1711).

Minor documentation and cleanup of TOTG plugin

---

moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py

This error also exists in Foxy, and should be backported to Foxy.

[main] Fix missing include in servo example

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h

Checks for `nullptr` when looking up a link transformation. The `LinkModel*` is set as `nullptr` [here](https://github.com/ros-planning/moveit2/blob/bf6357e895e364fa055da218ad7fcbd9ec3591f2/moveit_core/robot_model/src/robot_model.cpp#L1256-L1280) if the link name isn't known. This PR makes it throw in this case, instead of Seg Faulting. This should probably be backported to Moveit1 as well
I found this by modifying [this line](https://github.com/ros-planning/moveit2_tutorials/blob/9b1e55f2d665d12742388588f9b0ab2d1b9e0cb0/doc/realtime_servo/src/servo_keyboard_input.cpp#L74) to be an unknown frame, then running the [servo teleop demo](http://moveit2_tutorials.picknik.ai/doc/realtime_servo/realtime_servo_tutorial.html) with keyboard (arrow keys) input
[//]: # "You can expect a response from …

Check for nullptr on getGlobalLinkTransform

---

.github/workflows/build_and_test_galactic.yaml
.github/workflows/build_and_test_rolling.yaml

@tylerjw and I realised the CI was taking so much longer than before, and @tylerjw realized our ccache was not being loaded correctly. For eg: https://github.com/ros-planning/moveit2/runs/3233394484?check_suite_focus=true took 1 hour and has a failed `ccache cache` step. For reference https://github.com/ros-planning/moveit2/runs/3206185798?check_suite_focus=true is a normal run with correct `ccache cache` step.
This PR is an attempt to understand / fix our ccaches.
If works, this should be backported to Foxy, and all ros-planning repositories using this action including moveit.

Update ccache action

---

moveit_core/kinematic_constraints/src/utils.cpp

Port fix of reversed constraint assignment in https://github.com/ros-planning/moveit/pull/2815

Port fix of reversed constraint assignment

---

.github/workflows/build_and_test.yaml

Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619

[foxy] Fix ccache

---

moveit_ros/moveit_servo/package.xml

Fixes #597 
Similar to #603 except it missed these runtime dependencies. I think it worked anyway because they were brought in by a different package (transitive dependency)

Add gripper and traj control packages as run dependencies

---

.github/workflows/ci.yaml

I realized after #629, we don't build on rolling-ci images but instead building on rolling-ci-testing twice, this PR fixes that.

rolling-ci-testing to rolling-ci

---

moveit2.repos

ros2_control and ros2_controllers main branches can't compile on Foxy anymore with the recent changes, this PR makes the CI point to correct branches of ros2_control and ros2_controllers.

[foxy] Point CI to  foxy branches of ros2_control and ros2_controllers

---

moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_ompl_constrained_planning/launch/run_move_group.launch.py
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py
moveit_setup_assistant/src/tools/moveit_config_data.cpp

With ros-controls/ros2_controllers#230 ros2_control now removed joint_state_controller in favor of joint_state_broadcaster. This PR migrates our foxy branch to joint_state_broadcaster. Depends on https://github.com/ros-planning/moveit_resources/pull/96 and https://github.com/ros-planning/moveit2/pull/653

[foxy] Migrate to joint_state_broadcaster

---

moveit2.repos
moveit2_galactic.repos
moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_ompl_constrained_planning/launch/run_move_group.launch.py
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py
moveit_setup_assistant/src/tools/moveit_config_data.cpp

With ros-controls/ros2_controllers#230 ros2_control now removed joint_state_controller in favor of joint_state_broadcaster. This PR migrates our main branch to joint_state_broadcaster. Depends on ros-planning/moveit_resources#96.

[main] Migrate to joint_state_broadcaster

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

Until we figure out how we want to change the API to prevent this sort of bug this makes servo error much nicer in the constructor of ServoCalcs.
This also includes a fix for a clang-tidy error I hadn't seen before.  I wonder if our clang-tidy changed since the last time someone made a code change to servo.

Validate return of getJointModelGroup in ServoCalcs

---

.github/workflows/ci.yaml

As per discussion in #651 I think it is a good idea to enforce clang-tidy and move it under galactic-ci job (which is enforced).
Update: @henningkayser or any admin needs to change the required jobs before merging this.

Move clang tidy under galactic-ci

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Fixes the following warning when having multiple PSM for the same node:
```
rcl.logging_rosout: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
```

planning_scene_monitor: Fix warning about having two publisher with the same node

---

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor_middleware_handle.cpp

Essentially just a copy of what is done a few lines down, if no "sensors" are provided.

Error if Octomap 'map_frame' is not provided

---

moveit_ros/visualization/rviz_plugin_render_tools/src/mesh_shape.cpp

Fixes a bug causing RViz to print a ton of error messages about material not existing in the `General` resource group when adding a mesh to the planning scene
```
[rviz2-1] rviz2: Can't assign material Shape94Material to the ManualObject MeshShape_ManualObject0 because this Material does not exist in group General. Have you forgotten to define it in a .material script?
[rviz2-1] rviz2: Can't assign material Shape96Material to the ManualObject MeshShape_ManualObject1 because this Material does not exist in group General. Have you forgotten to define it in a .material script?
[rviz2-1] rviz2: Can't assign material Shape98Material to the ManualObject MeshShape_ManualObject2 because this Material does not exist in group General. Have you forgotten to define it in a .material script?
[rviz2-1] …
```

mesh_shape: Fix resource group for meshes

---

.github/workflows/docker.yaml

Forward ports https://github.com/ros-planning/moveit/commit/0ad09153cadfa92d74354598953d0ff853e52d47 in https://github.com/ros-planning/moveit/pull/2844.
Also I realized we are caching the same docker image in source builds. So although the source code changes the docker image does not get built again. This PR updates source dockers to never use cache. We can still use caching by changing the Dockerfiles to be more cache-able. But I prefer leaving it to another PR.

Forward port 2844, never use cache in source builds

---

moveit_ros/hybrid_planning/CMakeLists.txt

Fix hybrid planning includes

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/src/servo_server_node.cpp

Previously the servo_server node was only available as a component node. This adds a new executable to run the servo_server as a standalone node.

Add standalone executable for Servo server node

---

moveit_core/collision_detection/include/moveit/collision_detection/occupancy_map.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/perception/lazy_free_space_updater/include/moveit/lazy_free_space_updater/lazy_free_space_updater.h
moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/default_warehouse_db.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/edit_configuration_package.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_ompl.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/sensor_manager.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajectory_execution.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/warehouse.launch

- Move OccMapTree to moveit_core/collision_detection
- Implement checkCollision with default ACM as wrapper
- use lockable octomap for MotionPlanningDisplay as well
- Remove gtest include from non-testing source (#2747)
- MSA: kill setup_assistant.launch after MSA finished (#2749)
- use $(dirname) in MoveIt Setup Assistant (#2748)
MoveIt1 -> MoveIt2 sync of smaller size that hopefully is simple enough to review.  I'm sorry about the mess that was the last one.

MoveIt sync

---

moveit2_galactic.repos

Fixes CI by only installing released versions for Galactic. This should also prevent sync issues in the future.

Fix source versions of ros2_control, ros2_controllers

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

Revert to original log levels of some functions that was changed in https://github.com/ros-planning/moveit2/pull/598/files#diff-25706feb6b355123a5ae63dfa987a1cdd5754087392e9623960ed74a31b56d75R59.

Info -> Debug

---

.github/workflows/backport.yaml

Closes #669 and adds a simple backport bot that backports desired PRs. So the backport conditions are:
- PRs should be labeled as in `backport branch` format (ie: `backport foxy` or `backport main`)
- The backport PR will be opened by github-actions bot, after the original PR is merged.
Thus, I appreciate if you can create these labels @henningkayser.
I've tested this in my fork and seemed to work nicely, see https://github.com/vatanaksoytezer/moveit2/pull/20 and https://github.com/vatanaksoytezer/moveit2/pull/19.

Add backport bot

---

moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
moveit_core/profiler/src/profiler.cpp
moveit_kinematics/test/test_kinematics_plugin.cpp
moveit_planners/ompl/ompl_interface/test/test_threadsafe_state_storage.cpp
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_ros/moveit_servo/include/moveit_servo/collision_check.h
moveit_ros/moveit_servo/src/collision_check.cpp
moveit_ros/moveit_servo/test/enforce_limits_tests.cpp

This fixes the build warnings discovered here https://github.com/ros-planning/moveit2/runs/3662305871?check_suite_focus=true#step:8:689. Should we enforce the build to be free of warnings?

Fix cmake warnings

---

moveit_core/collision_detection_fcl/src/collision_common.cpp

Port of https://github.com/ros-planning/moveit/pull/2820 to fix https://github.com/ros-planning/moveit2/actions/runs/1267421632
Because std::make_pair uses the decayed type (std::string), the strings were actually copied into a temporary, which was subsequently referenced by the elements of std::pair, leading to a stack-use-after-scope error.
Explicitly passing const references into std::make_pair via std::cref() resolves the issue mentioned in #2809.

Fix broken test

---

.docker/ci-testing/Dockerfile
.docker/ci/Dockerfile
.docker/release/Dockerfile
.docker/source/Dockerfile
.dockerignore
.github/workflows/docker.yaml

Forward port of dockerfile changes in https://github.com/ros-planning/moveit2/pull/698. Unblocks https://github.com/ros-planning/moveit2_tutorials/pull/120

Forward ports recent dockerfile changes on foxy

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

While the servo update loop currently includes a check to see if the latest messages on the joint and Cartesian command topics are up-to-date, this does not actually stop Servo from continuing to publish joint control messages even if the commands are stale. If both command topics are stale, the `joint_trajectory` message used to create the control messages is [populated with the last-commanded positions and zero velocities](https://github.com/ros-planning/moveit2/blob/d184714751b347a2389cf1e8742b1be94eed63b8/moveit_ros/moveit_servo/src/servo_calcs.cpp#L376-L384). This can cause problems if Servo is paused and another method is used to move the robot, since when Servo is unpaused it will publish a control message to the last-commanded position, which could be a significant distance from …

Skip publishing to Servo topics if input commands are stale

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

https://github.com/ros2/rclcpp/commit/679fb2ba334971d9769b44258df9095025567559 broke the API for `async_send_request`, so using `response.get()` multiple times will throw an exception `std::future_error "No associated state"`

getInterfaceDescription: Fix rclcpp API breakage

---

moveit_core/collision_detection_bullet/CMakeLists.txt

Backporting PR #658 to main branch

[main]: collision_detection_bullet: fix target installation

---

moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_distance_field_types.h

I thought it would be a good idea to scour the codebase for places where the fact that [(rotation matrix transpose) == (rot. matrix inverse)](https://www.google.com/search?channel=fs&client=ubuntu&q=transpose+of+rotation+matrix+is+inverse) could be used to speed up calculations. Since a transpose is cheaper than an inverse.
This is the only place I found where that applies.
Eigen has some internal optimizations for Isometry3d types, but I doubt it's smart enough to look ahead and realize it only needs to invert the 3x3 rotation matrix.
Reviewers will need a slightly advanced background in linear algebra, which is why I tagged @mamoll and @v4hn.

Small matrix calc speedup in collision_distance_field_types

---

MIGRATION.md
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/include/moveit_servo/servo_node.h
moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/moveit_servo/src/servo_node_main.cpp
moveit_ros/moveit_servo/src/teleop_demo/joystick_servo_example.cpp
moveit_ros/moveit_servo/test/config/servo_settings.yaml
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/publish_fake_jog_commands.cpp
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp

Until we figure out how we want to change the API to prevent this sort of bug this makes servo error much nicer in the constructor of ServoCalcs.
This also includes a fix for a clang-tidy error I hadn't seen before.  I wonder if our clang-tidy changed since the last time someone made a code change to servo.
Updated tutorials: https://github.com/ros-planning/moveit2_tutorials/pull/109

Rename ServoServer to ServoNode

---

moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning/planning_components_tools/src/visualize_robot_collision_volume.cpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/warehouse/warehouse/src/save_to_warehouse.cpp

Address https://github.com/ros-planning/moveit2/issues/617
Fix: https://github.com/ros-planning/moveit2/issues/646

Add private buffer & tf listener to PSM

---

moveit_ros/moveit_servo/config/demo_rviz_config.rviz
moveit_ros/moveit_servo/src/servo_node.cpp

Fixes https://github.com/ros-planning/moveit2/issues/770
The bug was caused by me here: https://github.com/ros-planning/moveit2/commit/7e3fdcffbfef79d92a665d6ea2cd631befd872aa, I changed the topic name of the publish_planning_scene topic to be in the private namespace, what I meant to do was change it to be relative to the name of the node.  This PR fixes that so it has a topic name relative to the name of the servo node.

Fix initialization of PSM publisher in servo

---

moveit_commander/src/moveit_commander/move_group.py

- Add CI configuration for cross-platform CI
- CMakeLists.txt and package.xml fixes for cross-platform CI
- Fix windows compilation failures
- Rename near to seed
- Getter for name of CollisionDetectorAllocator
- Use rosdep in cross-platform CI
- Small cleanup, name job based on matrix.os as suggested by @rhaschke
- Add python2 dependency for < noetic, lint and rebase
- use infinity constant instead of divide by zero
- move to cmake gen headers
- Fix dumb bug (#2753)
I took the changes from the last commit.  The rest of them are here only for the git history.

Sync from MoveIt1 (#2753)

---

.github/workflows/ci.yaml
moveit_ros/moveit_servo/include/moveit_servo/collision_check.h
moveit_ros/moveit_servo/include/moveit_servo/servo_parameters.h
moveit_ros/moveit_servo/src/collision_check.cpp
moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp

This fixes two bugs:
1- The collision checking for servo is only using the initial ACM and doesn't reflect the updates PSM is receiving in the scene monitor topic
2- When using servo with move_group, servo's scene monitor should point to the move_group's one, otherwise we can't sync the planning scene between them
For the second point, I'm not sure whether we should have a parameter or always use `monitored_planning_scene` @AndyZe what do you think .? I think this depends on whether the PSM in servo is the primary one or not, right .?

moveit_servo: Fix ACM for collision checking & PSM's scene monitor topic

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

Ported version of https://github.com/ros-planning/moveit/pull/1162 for MoveIt2. This currently does not have any tests. 

RobotTrajectory as standard container

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

Reference to Issue https://github.com/ros-planning/moveit2/issues/751
Tested both with and without the SetPathConstraints

MoveitCpp - path constraints added from PlanningComponent

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

This is a partial replacement for #731 that only includes the changes required to allow MoveIt-managed controller switching to work again while excluding changes to the behavior of the controller manager plugin.
- Discover available controllers when initializing the controller manager plugin.
- Account for changes to `controller_manager_msgs` in ros2_control v1.1.0. The most significant change is that resources that are required but not claimed by the controller (for example, if the controller is not active) are now listed in a separate message field than resources that are actively claimed by the controller.
- Use `scoped_lock` in place of `unique_lock`.
- Add more detailed comments and logging.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard …

Update controller_manager_plugin to fix MoveIt-managed controller switching

---

moveit_common/cmake/moveit_package.cmake
moveit_common/package.xml

This adds backward_ros to all moveit packages that use the moveit_common cmake function.  This is a really useful tool and building it in by default seems like a really nice feature.
https://github.com/pal-robotics/backward_ros/tree/foxy-devel

Add backward_ros to moveit_common

---

moveit/package.xml
moveit_commander/package.xml
moveit_common/package.xml
moveit_core/package.xml
moveit_demo_nodes/run_move_group/package.xml
moveit_demo_nodes/run_moveit_cpp/package.xml
moveit_demo_nodes/run_ompl_constrained_planning/package.xml
moveit_kinematics/package.xml
moveit_planners/moveit_planners/package.xml
moveit_planners/ompl/package.xml
moveit_planners/pilz_industrial_motion_planner/package.xml
moveit_planners/pilz_industrial_motion_planner_testutils/package.xml
moveit_planners/trajopt/package.xml
moveit_plugins/moveit_plugins/package.xml
moveit_plugins/moveit_ros_control_interface/package.xml
moveit_plugins/moveit_simple_controller_manager/package.xml
moveit_ros/benchmarks/package.xml
moveit_ros/manipulation/package.xml
moveit_ros/move_group/package.xml
moveit_ros/moveit_ros/package.xml
moveit_ros/moveit_servo/package.xml
moveit_ros/occupancy_map_monitor/package.xml
moveit_ros/perception/package.xml
moveit_ros/planning/package.xml
moveit_ros/planning_interface/package.xml
moveit_ros/robot_interaction/package.xml
moveit_ros/visualization/package.xml
moveit_ros/warehouse/package.xml
moveit_runtime/package.xml
moveit_setup_assistant/package.xml

This fixes the formatting for all package.xml files and enforces the [format 3 ROS schema](http://download.ros.org/schema/package_format3.xsd).
#697 should be merged first, then I will switch the target to `main`.

Enforce package.xml format 3 Schema

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Two related fixes to avoid some troublesome situations that happen if ros2_control's ROS interface isn't available when MoveIt is initialized (such as if the ros2_control nodes take longer to finish launching than the MoveIt nodes):
- Reload information about controllers whenever `TrajectoryExecutionManager::ensureActiveControllers` is called. Previously, reloading controller info only happened when initializing the TrajectoryExecutionManager and when executing a trajectory. This sometimes caused situations where using `ensureActiveControllers` outside the scope of executing a trajectory failed because the info about the controllers was out of date.
- Allow controller handles derived from `ActionBasedControllerHandle` to completely initialize even if the action server they expect to …

Make controller management logic more tolerant of missing or late ros2_control nodes

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/include/moveit_servo/parameter_descriptor_builder.hpp
moveit_ros/moveit_servo/include/moveit_servo/servo_parameters.h
moveit_ros/moveit_servo/src/cpp_interface_demo/pose_tracking_demo.cpp
moveit_ros/moveit_servo/src/parameter_descriptor_builder.cpp
moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/moveit_servo/src/servo_node_main.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp
moveit_ros/moveit_servo/test/pose_tracking_test.cpp
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp
moveit_ros/moveit_servo/test/unit_test_servo_calcs.cpp

Update servoParameters to use a new declare and get function that uses NodeParametersInterface to declare and get parameters. See #790
This PR  does the following:
- Sets default values for servo parameters based off of panda_simulated_config.yaml
- Replaces the getOrDeclareParam function with individual get and set functions
- These 
- Adds parameter_descriptor_builder, which is used to create the messages used in setting up the descriptions for parameters
TODO:

Change servo parameters to use ros2 interfaces for parameters

---

MIGRATION.md
moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_pr2.h
moveit_core/collision_detection/include/moveit/collision_detection/world.h
moveit_core/collision_detection/src/world.cpp
moveit_core/collision_detection_bullet/src/collision_env_bullet.cpp
moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
moveit_core/collision_distance_field/src/collision_common_distance_field.cpp
moveit_core/collision_distance_field/src/collision_env_distance_field.cpp
moveit_core/collision_distance_field/test/test_collision_distance_field.cpp
moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/robot_state/include/moveit/robot_state/attached_body.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/attached_body.cpp
moveit_core/robot_state/src/conversions.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/test_kinematic_complex.cpp
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/state_validity_checker.h
moveit_ros/manipulation/pick_place/src/place.cpp
moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.cpp
moveit_ros/planning/planning_scene_monitor/demos/demo_scene.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_ros/planning_interface/test/subframes_test.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_manipulation.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

Sync the following commits from MoveIt with merge
```
* [2020-09-11] [b57628ff7] | Unify object scaling in Rviz {{Felix von Drigalski}} 
* [2020-09-12] [d6a714d16] | Add pose to AttachedBody and RobotState {{Felix von Drigalski}} 
* [2020-09-12] [6561fd372] | Add pose to CollisionObject and world {{Felix von Drigalski}} 
* [2020-06-07] [aa88879b5] | Renaming, housekeeping, migration notes {{Felix von Drigalski}} 
* [2021-08-14] [0defef0f2] | more fixes for the clang-tidy job (#2813) {{Michael Görner}} 
* [2021-08-12] [86174f367] | fix clang-tidy CI job (#2792) {{Michael Görner}} 
* [2021-08-11] [823788778] | Bugfix in RDFLoader (#2806) {{werner291}} 
* [2021-08-10] [f0271dc6a] | Merge pull request #2802 from v4hn/pr-master-fix-clang-issues {{Michael Görner}} 
* [2021-07-29] [4daba2636] | …
```

Sync with MoveIt

---

moveit_core/robot_model/src/joint_model_group.cpp

This is a commit that I extracted form #452. The warning should be a debug message, it seems to have been merged as part of some verbose debugging attempt. Related note: Are we missing best practices on how to use and filter log messages properly? I've seen temporarily increased logger levels like this quite often and it should not be necessary.

Revert debug warning

---

moveit_core/online_signal_smoothing/CMakeLists.txt

This fixes this error:
```
CMake Error at online_signal_smoothing/CMakeLists.txt:49 (find_package):
By not providing "Findros_testing.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"ros_testing", but CMake did not find one.
Could not find a package configuration file provided by "ros_testing" with
any of the following names:
ros_testingConfig.cmake
ros_testing-config.cmake
Add the installation prefix of "ros_testing" to CMAKE_PREFIX_PATH or set
"ros_testing_DIR" to a directory containing one of the above files.  If
"ros_testing" provides a separate development package or SDK, be sure it
has been installed.
```

Remove unused dependency from online_signal_smoothing cmake

---

moveit_core/distance_field/CMakeLists.txt
moveit_core/utils/CMakeLists.txt
moveit_ros/occupancy_map_monitor/CMakeLists.txt

There were some weird boost linking errors since yesterday, I was able to reproduce by running industrial_ci locally, and this PR should hopefully fix them. I have yet to know the root cause, so I'm happy to resolve this different ways as well if someone has any suggestion.

Fix boost linking errors

---

.docker/ci/Dockerfile

This should fix docker CI fails in main. I would be happy if someone (that has write access) can test this in a branch before merging.

Docker - Temporarily move moveit_resources under target workspace due to #885

---

moveit_planners/ompl/ompl_interface/CMakeLists.txt

Closes #923. Somehow CI wasn't able to catch this (I'm assuming it was caching that part), but docker action caught this as well (https://github.com/ros-planning/moveit2/runs/4523535433?check_suite_focus=true). This PR just adds a one linn to properly link boost_serialization library in `ompl_interface`. Tested by building the docker locally. I am not sure why we haven't seen this in main though.

[foxy] Link boost serializaiton

---

moveit2.repos

ros2_control and ros2_controllers should be released and synced for rolling and galactic.  We should be able to stop building them from source in our CI system.
@vatanaksoytezer this should fix the latest rolling issue that ros2_control has blocking our CI.  As they've released into rolling I don't forsee us adding it back into the repos file after this unless we work on a feature with them we depend on.

Depend on released versions of ros2_control

---

moveit_ros/moveit_servo/include/moveit_servo/servo_node.h

Fixes a build warning in MoveIt Servo

Servo: fix -Wunused-private-field

---

moveit_ros/planning/package.xml

Fix buildfarm failure: https://build.ros2.org/job/Rbin_ufv8_uFv8__moveit_ros_planning__ubuntu_focal_arm64__binary/47/consoleFull
I don't understand how the prerelease test passed without this.  We'll probably have to create a patch release after this.

Add ros_testsing to moveit_ros_planning for rdf_loader

---

moveit2.repos

These versions have been bloomed and are not yet synced.  The debain versions of moveit_resources, warehouse_ros, and warehouse_ros_mongo should work just fine for our CI.
This is a shift in philosophy on how this file is used, but long term it would be really nice if this repos file only has branch versions in it when there was a change in an upstream repo we control that the main branch that we depend on.  Then after blooming (and before the sync) this file points to the newly released tag, then after it is synced we remove the repo from this file.  That way our CI system is building/caching the least amount possible in the upstream step and those who use moveit from source on the main branch are building the least amount possible in their local workspace.

Depend on the source of our own released repos

---

moveit_core/robot_model/include/moveit/robot_model/joint_model.h
moveit_core/robot_model/src/joint_model.cpp
moveit_core/robot_model/test/test.cpp
moveit_ros/planning/robot_model_loader/CMakeLists.txt
moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

Now that we have some MoveIt capabilities that can process jerk limits, I think we should add jerk limits to the robot model. This simply adds the jerk parameters to joint_limits.yaml and adds the parsing code to robot_model_loader.cpp.
Fixes #574

Add jerk to the robot model

---

.github/workflows/ci.yaml

Hopefully fix: https://github.com/ros-planning/moveit2/issues/783 and https://github.com/ros-planning/moveit2/issues/947

Add rosdistro version to upstream ws cache prefix

---

moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp

I was hitting a compilation error because `_1` wasn't properly available. I think this fixes it for us (RoboStack project).

fix usage of placeholder

---

.github/workflows/docker.yaml
.github/workflows/prerelease.yaml

Moving forward, I think that docker images for Galactic should be based on the `galactic` branch. We can discuss if we still want a separate source-build version based on main, but I don't really see the use of that. The galactic jobs on `main` can stay enabled as long as we want to support it, but I assume that we will drop them over the next months. I also removed the `Foxy` and `Galactic` builds from the pre-release test here. Each branch should only test against the targeted distro.

Only target Rolling in docker and pre-release jobs

---

moveit_planners/pilz_industrial_motion_planner/package.xml
moveit_planners/pilz_industrial_motion_planner_testutils/package.xml

Drop some pilz maintainers in ROS2 version. I am not involved in the ROS2 port moveit2 at all and thus I'd like to remove myself here.

Remove some Maintainers from Pilz Planner

---

moveit2.repos

This updates the repos file on galactic to only build moveit_msgs as that is the only package not yet synced into the main ros repo we depend on.

Update repos file on galactic

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/include/moveit_servo/enforce_limits.hpp
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/enforce_limits.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp
moveit_ros/moveit_servo/test/enforce_limits_tests.cpp

This is a simplified version of #886. It removes the latency compensation parameter that was controversial with reviewers for some reason (despite fixing some hardware issues and being backed as similar to what the robot manufacturers use  :/  ). By splitting it out, I hope the review is faster.
The various fixes here are:
- Re-order the checking of velocity limits. These limits should be checked **after** the other operations that affect velocity. Otherwise they aren't accurate.
- Delete a block of code that was accidentally duplicated.
- Clean up some comments.
- Delete a couple unused things.
You can test this PR with the tutorial:  https://moveit.picknik.ai/main/doc/realtime_servo/realtime_servo_tutorial.html
If you're familiar with the tutorial, you'll notice that motion is faster.

Servo: re-order velocity limit check & minor cleanup

---

moveit_kinematics/test/test_ikfast_plugins.sh

This fixes the IKFast test instead of removing it with #991.
I just moved apt-get update before the install command as suggested in the log error.

Fix IKFast test dependency

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_circ.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_lin.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_ptp.h
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_aggregator.cpp
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_container.cpp
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_validator.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp
moveit_planners/pilz_industrial_motion_planner/test/test_utils.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_joint_limits_container.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_joint_limits_validator.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_ptp.cpp
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp
moveit_ros/moveit_servo/test/test_servo_interface.cpp

- Remove 'using namespace pilz_industrial_motion_planner' from header files.
- Remove 'using namespace std::chrono_literals' from header files.
This PR addresses https://github.com/ros-planning/moveit2/issues/853.

Remove 'using namespace' from header files.

---

moveit_planners/pilz_industrial_motion_planner/package.xml

Once again attempt to fix buildfarm errors: https://build.ros2.org/job/Rbin_uF64__pilz_industrial_motion_planner__ubuntu_focal_amd64__binary/24/console

Add missing test dependencies

---

moveit_core/trajectory_processing/test/test_ruckig_traj_smoothing.cpp

This initializes the robot state before the Ruckig test

Initialize RobotState in Ruckig test

---

moveit_setup_assistant/MIGRATION.md
moveit_setup_assistant/moveit_setup_assistant/include/moveit_setup_assistant/navigation_widget.hpp
moveit_setup_assistant/moveit_setup_assistant/src/navigation_widget.cpp
moveit_setup_assistant/moveit_setup_assistant/src/setup_assistant_widget.cpp

* Disallows user from selecting disabled widgets from navigation widget
* When setting modal mode, do not re-enable steps if they are not ready yet. 

[MSA] Navigation Widget Fixes

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
moveit_ros/hybrid_planning/test/CMakeLists.txt

Just testing out if CI failures are due to upstream workspace caching.
Edit: So if we disable docker and upstream caching together CI issues seem to resolve well. I've written an action that gets the latest edit timestamp of the repos file and generates a new cache if the repos has been changes. By utilizing that we should be able to achieve upstream caching and not worry about broken CIs every time the .repos file change.
Edit 2: It turns out we have flaky behaviour (likely due to ros2_control), I am going to disable hybrid planning test for now and let the CI pass to unblock all the PRs waiting for this. I am going to create a high priority issue to resolve this as soon as possible. I am suspecting a race condition because the failures are not consistent and happens ~50% of the time.

Disable hybrid planning test, don't cache ci docker at all and don't cache upstream_ws if repos file is changed

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml

- Add an explicit setting for `is_primary_planning_scene_monitor` to the Panda MoveIt Servo example config YAML file, since I think this is what most users copy and paste from when setting up Servo in their own projects.
- Add a comment about cases where it should be set to `false` since it defaults to `true` if not explicitly set. While this behavior is OK for the scenario in the example, it can have undesirable side effects in systems where a different node is responsible for managing the planning scene.

Set value for is_primary_planning_scene_monitor in Servo example config YAML

---

moveit_ros/planning/rdf_loader/src/synchronized_string_parameter.cpp
moveit_ros/planning/rdf_loader/test/test_rdf_integration.cpp

- Add a test for RDFLoader where the node is spinning in a different thread.
- Detach the thread.
- Create a new node in SynchronizedStringParameter and use it to create subscriptions.
This PR addresses the issue in https://github.com/ros-planning/moveit2_tutorials/pull/262 where the robot model can't be loaded.  It also represents an improvement on https://github.com/ros-planning/moveit2/pull/1039.  The implementation in https://github.com/ros-planning/moveit2/pull/1039 only worked in the case where `node_` was spinning in a separate thread, and failed when `node_` was not spinning.  The original implementation worked well when `node_` was not spinning, but had a race condition when it was spinning.
`SynchronizedStringParameter` has no control over whether or not `node_` is spinning, so …

Fix race condition in SynchronizedStringParameter::waitForMessage

---

moveit_ros/hybrid_planning/hybrid_planning_manager/planner_logic_plugins/src/replan_invalidated_trajectory.cpp
moveit_ros/hybrid_planning/local_planner/local_constraint_solver_plugins/src/forward_trajectory.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/feedback_types.h
moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp

Get rid of hard-coded string constants

[hybrid planning] Use a map of expected feedback codes

---

.github/workflows/docker.yaml

Fixes the failing docker delete action. I found out GH recently broke REST API and I had to do some minor changes and update github script version. Here is a successful run I tried with this: https://github.com/ros-planning/moveit2/actions/runs/1813877611

Fix docker cleanup action

---

.github/workflows/ci.yaml

Should unblock us from merging PRs until rolling is migrated to jammy.

Temporarily use galactic in main CI

---

moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp

We have a dual-arm project and found there was a deadlock here where the planning scene locks. This change fixes the deadlock and I think it's nice in a couple other ways, too:
- Make the robot state const.
- Eliminate an intermediate variable.
I'm all-ears in case there is a better way that I could test.

[hybrid planning] Adjust planning scene locking

---

.docker/ci/Dockerfile
.docker/release/Dockerfile
.github/workflows/ci.yaml
.github/workflows/docker.yaml
.github/workflows/format.yaml
.pre-commit-config.yaml
moveit2.repos
moveit_kinematics/package.xml
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_planning_context.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_common.cpp
moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp
moveit_ros/moveit_servo/include/moveit_servo/parameter_descriptor_builder.hpp
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/visualization/package.xml
moveit_ros/warehouse/warehouse/src/broadcast.cpp
moveit_ros/warehouse/warehouse/src/import_from_text.cpp
moveit_setup_assistant/package.xml
moveit_setup_assistant/src/collisions_updater.cpp
moveit_setup_assistant/src/setup_assistant_main.cpp
moveit_setup_assistant/src/tools/compute_default_collisions.cpp
moveit_setup_assistant/src/tools/moveit_config_data.cpp

Also updating clang-format to 12 since 10 is not available in Jammy, and is pretty old.

Compilation fixes for Jammy and bring back Rolling CI

---

.github/workflows/ci.yaml
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py

Rolling, ROS and almost everything in Jammy is broken due to [transition of Python version from 3.9 to 3.10](https://discourse.ros.org/t/preparing-for-rolling-sync-delayed-by-python-3-10-transition/24521/9). I am commenting out Rolling and adding Galactic back so we can at least merge PRs.

Temporarily add galactic CI

---

moveit_setup_assistant/moveit_setup_framework/src/package_settings_config.cpp
moveit_setup_assistant/moveit_setup_framework/templates/CMakeLists.txt
moveit_setup_assistant/moveit_setup_framework/templates/package.xml.template

Change the templates (and dependency block generating code) to ROS 2 standards. 

[MSA] Upgrade templates to ROS 2

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
moveit_configs_utils/package.xml

* Fix a minor grammatical error
* Change the ordering in package.xml
* According to the [schema](http://download.ros.org/schema/package_format3.xsd) `author` comes after `maintainer` and `license`. 
* While not a strict requirement, `test_depend`s  come after `exec_depend`

[moveit_configs_utils] Minor fixes

---

MIGRATION.md
moveit_ros/planning/moveit_cpp/src/planning_component.cpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h

Previously there were 2 ways to lock the planning scene:
- `lockSceneRead()` or `lockSceneWrite()`
- Create a `LockedPlanningSceneRO` or `LockedPlanningSceneRW` object. Internally, this uses `lockSceneRead()` or `lockSceneWrite()`
The [tutorials recommend](https://moveit.picknik.ai/galactic/doc/examples/planning_scene_monitor/planning_scene_monitor_tutorial.html#planningscenemonitor) the LockedPlanningSceneRO approach. @v4hn and I [thought](https://github.com/ros-planning/moveit2/pull/1087#discussion_r812298593) it would be a good idea to make `lockSceneRead()` and `lockSceneWrite()` private so they don't get used by mistake.
`lockSceneRead()` and `lockSceneWrite()` don't get used very much in the codebase so this was actually a pretty simple change.
So far, I've tested with the Move …

Make lockSceneRead() and lockSceneWrite() protected member functions

---

moveit/scripts/create_readme_table.py

Copyright must be the first thing in the file, this silences the linter warning

Fix copyright notice in README script

---

moveit_core/robot_trajectory/src/robot_trajectory.cpp

Corrects an off-by-one error in getAverageSegmentDuration
If we have **n** waypoints, we have **n - 1** timesteps
Assume a trivial case of durations = [1, 2, 3] with a timestamp of 1 and a size of 3
getDuration returns:
3 - 1 = 2
The current return is:
2 / 3 = 0.67
The expected return should be: 
2 / (3 - 1)  = 1

Off by one in getAverageSegmentDuration

---

moveit_setup_assistant/moveit_setup_assistant/src/setup_assistant_widget.cpp
moveit_setup_assistant/moveit_setup_core_plugins/include/moveit_setup_core_plugins/start_screen.hpp
moveit_setup_assistant/moveit_setup_core_plugins/include/moveit_setup_core_plugins/start_screen_widget.hpp
moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen.cpp
moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen_widget.cpp
moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/data/srdf_config.hpp
moveit_setup_assistant/moveit_setup_framework/src/package_settings_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/srdf_config.cpp

Undoes https://github.com/ros-planning/moveit2/commit/78896a129a9e9c0bd12601fa45537a17f37edbbc to simplify the loading of new SRDF files, and then some minor other cleanup. 

[MSA] Simplify loading of new SRDF

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/octomap_render.h

It fixes this specific build error on our project's CI setup:
```
--- stderr: moveit_task_constructor_visualization
In file included from /opt/ros/galactic/include/moveit/rviz_plugin_render_tools/render_shapes.h:39,
from /opt/ros/galactic/include/moveit/rviz_plugin_render_tools/planning_scene_render.h:41,
from /home/runner/work/lab0_harvester/lab0_harvester/.work/upstream_ws/src/moveit_task_constructor/visualization/visualization_tools/src/task_solution_visualization.cpp:42:
/opt/ros/galactic/include/moveit/rviz_plugin_render_tools/octomap_render.h:45:10: fatal error: OGRE/OgrePrerequisites.h: No such file or directory
45 | #include <OGRE/OgrePrerequisites.h>
```
@jliukkonen and @tylerjw know the context and more details on the CI situation. I don't know so much about it.

Remove include of OgrePrerequisites header

---

moveit_planners/pilz_industrial_motion_planner/include/joint_limits/joint_limits_rosparam.hpp

The plugin did throw an error that parameters were already declared, at
least when I used it.
This commit fixes this.

[moveit_cpp] Fix double declaration

---

moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp

The issue I had was that MoveItCpp was working with one pipeline but when I wanted to configure a second pipeline, I couldn't use the first one.
Do I really need to write a test for such a change?
Edit: Added PR description

[moveit_cpp] Fix config of multiple pipelines

---

moveit2.repos

Removes launch_param_builder from repos file, since it was bloomed in January (https://github.com/ros/rosdistro/pull/31881) and appears to be part of the rolling build now. 

Remove launch_param_builder

---

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_ros/planning/rdf_loader/test/data/robin.srdf.xacro
moveit_ros/planning/rdf_loader/test/test_rdf_integration.cpp

`RDFLoader` fails to properly load xacro files. This initial PR is for a test that shows the broken functionality. A one character fix will be added once CI completes on the initial test. 

RDFLoader Broken with Xacro Files

---

moveit_core/robot_trajectory/src/robot_trajectory.cpp

Off by one in getAverageSegmentDuration (#1079)

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

This PR enalbes trajectory execution when using simulation.
The PR adds controllers' status before it is checked if all needed controller are activated.
This is neede to use MoveIt with Ignition Simulation (I will link UR example later today for this).
Though, the interesting part is, why trajectory execution is working without this changes when using "FakeSystem" or hardware.
It looks to me that the same checks should fail in any case.
I tested this with and without "moveit_manage_controllers" parameter set. And the changes are required in both cases.
I using "moveit_simple_controller_manager/MoveItSimpleControllerManager" in our setup. Is this maybe an issue?
Should another controller manager be used.
BTW, I see that MoveIs is not activelly checking which controllers are active and …

Set controller status before it is cheked on trajectory execution.

---

MIGRATION.md
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp

Return an `ExecutionStatus` in `MoveItCpp::execute`, which can is
convertible to a bool in the caller code.
This change introduces a forward-compatible API breaking change.
Return an `ExecutionStatus` in `MoveItCpp::execute`, which can is
convertible to a bool in the caller code.
This change introduces a forward-compatible API breaking change.
Follow-up of #1144.

[moveit_cpp] Return `ExecutionStatus` in `execute`

---

moveit_ros/visualization/rviz_plugin_render_tools/src/mesh_shape.cpp

Fixes: https://github.com/ros-planning/moveit2/issues/1164

[foxy]: mesh_shape: Fix resource group for meshes (backport #672)

---

moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/planning/rdf_loader/test/test_rdf_integration.cpp
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py

I think this is the only way to fix the CI, in one single PR. Just want to get this in and unblock everything here.

Disable failing rdf test, merge #1163 and #1168

---

moveit2.repos

* moveit_msgs has been at 2.2.0 since https://github.com/ros/rosdistro/pull/31470
* ompl seems to be up to date in rolling since https://github.com/ros/rosdistro/pull/32292

Remove moveit_msgs and ompl from moveit2.repos

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp
moveit_core/trajectory_processing/test/test_ruckig_traj_smoothing.cpp

Fixes #767 
This fixes some bugs in the Ruckig smoothing plugin and simplifies it. I tried to comment it better and simplify so it will be self-explanatory.
You can test this easily with the MoveIt tutorials.
- Add Ruckig to the list of OMPL adapters. In `panda_moveit_config/config/ompl_planning.yaml`, add `AddRuckigTrajectorySmoothing` to the top of the list like this:
```
request_adapters: >-
default_planner_request_adapters/AddRuckigTrajectorySmoothing
```
- Then launch the Panda with move_group:  `ros2 launch moveit_resources_panda_moveit_config demo.launch.py`
- You will know the Ruckig plugin loaded if you see this in terminal:
`Using planning request adapter 'Add Ruckig trajectory smoothing.`
Representative data from some very large trajectories (1000+ waypoints). We feed 10 …

Ruckig smoothing cleanup

---

moveit2.repos
moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/include/moveit_servo/enforce_limits.hpp
moveit_ros/moveit_servo/include/moveit_servo/servo_parameters.h
moveit_ros/moveit_servo/src/enforce_limits.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp

This adds an option to MoveIt Servo to override the velocity scaling calculation with a constant value. The default behavior has not been changed, but if the user adds a parameter to their servo.yaml that includes `override_velocity_scaling_factor: 0.5` or any other number between 0 and 1 it will use that value for velocity scaling.

[Servo] override velocity scaling with a constant

---

moveit_core/controller_manager/include/moveit/controller_manager/controller_manager.h
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

[CI is failing on #1176](https://github.com/ros-planning/moveit2/runs/5997775137?check_suite_focus=true#step:12:420) with the errors
```
/home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/controller_manager/controller_manager.h:141:67: error: no matching conversion for functional-style cast from 'int' to 'rclcpp::Duration'
virtual bool waitForExecution(const rclcpp::Duration& timeout = rclcpp::Duration(-1)) = 0;
```
and
```
/home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h:152:46: error: no viable overloaded '='
send_goal_options.goal_response_callback =
```
I believe this is caused by https://github.com/ros2/rclcpp/pull/1913 …

RCLCPP Upgrade Bugfixes

---

moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

Add a warning for TOTG time parameterization if a vel/accel limit is not defined and a default is being assumed. This is the same warning the recent Ruckig plugin provides.
I could add something similar to IPTP or ISTP but I hope they get deprecated soon.

Add a warning for TOTG if vel/accel limits aren't specified.

---

moveit_configs_utils/moveit_configs_utils/launches.py

Following up on #1131 and #1176, this PR creates the last new launch file function that I intend to add for use with MSA: `generate_demo_launch`
You can try it out with [my branch of `moveit_resources`](https://github.com/ros-planning/moveit_resources/compare/ros2...DLu:moveit_configs_utils_demos) that has both panda and fanuc configurations. 

Demo launch for moveit_configs_utils

---

.pre-commit-config.yaml
moveit_commander/src/moveit_commander/move_group.py
moveit_commander/src/moveit_commander/planning_scene_interface.py
moveit_commander/src/moveit_commander/robot.py
moveit_ros/planning_interface/test/serialize_msg.py
moveit_setup_assistant/README.md
moveit_setup_assistant/moveit_setup_assistant/src/main.cpp
moveit_setup_assistant/moveit_setup_core_plugins/include/moveit_setup_core_plugins/configuration_files_widget.hpp

Three small edits to get the `feature/msa` 
* Fixes XML rendering in README.md
* Removes a TODO for functionality that has not been needed in the ROS 2 port. 
* Removes a duplicated header inclusion. 

[MSA] Three small edits

---

.docker/ci/Dockerfile
.docker/source/Dockerfile
moveit_core/trajectory_processing/test/test_ruckig_traj_smoothing.cpp

Attempt to fix CI permission issues like this:
```
Could not determine remotes: fatal: unsafe repository ('/home/runner/work/moveit2/moveit2/.work/upstream_ws/src/geometric_shapes' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /home/runner/work/moveit2/moveit2/.work/upstream_ws/src/geometric_shapes
```

Fix CI permission errors

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

This PR does 2 things:
- TOTG usually runs before this algorithm. If the output of TOTG is just a _tiny_ bit above velocity/acceleration limits due to numerical error, Ruckig fails. So, this PR clamps the inputs into Ruckig.
- Use the current waypoint state as input for the next iteration. For our client, this resulted in velocity that tracked the desired velocity much more closely. (Although it seems like it should be very similar either way, to me.)
Clone the MoveIt2 tutorials and add Ruckig to `ompl_planning.yaml`:
```
request_adapters: >-
default_planner_request_adapters/AddRuckigTrajectorySmoothing
default_planner_request_adapters/AddTimeOptimalParameterization
```
Then run one of the tutorials. It should work like normal.
`ros2 launch moveit2_tutorials demo.launch.py …

Clamp inputs to Ruckig. Use current waypoint as input for next iteration

---

moveit_core/CMakeLists.txt
moveit_core/package.xml
moveit_kinematics/CMakeLists.txt
moveit_kinematics/package.xml
moveit_planners/pilz_industrial_motion_planner/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner/package.xml

[orocos_kdl doesn't exist anymore,](https://github.com/ros/rosdistro/pull/33028) there is a [vendor package](https://github.com/ros2/orocos_kdl_vendor) instead.
Related CI failure: https://github.com/ros-planning/moveit2/runs/6294353126?check_suite_focus=true

Use orocos_kdl_vendor package

---

moveit_core/collision_detection/src/collision_octomap_filter.cpp

Fix a clang-tidy warning:
```
moveit_core/collision_detection/src/collision_octomap_filter.cpp:253:23: warning: the variable 'v' is copy-constructed from a const reference but is only used as const reference; consider making it a const reference [performance-unnecessary-copy-initialization]
octomath::Vector3 v = (*it);
```

CI: Fix clang-tidy warning

---

.docker/ci/Dockerfile
.docker/source/Dockerfile

Generalize #1206, disabling git security check for any folder.
We are running our self-generated docker container on GHA. Chances are low that this gets compromised.
This should also solve https://github.com/ros-planning/moveit2_tutorials/pull/355.

CI: More generically fix permission errors

---

moveit_planners/pilz_industrial_motion_planner/src/path_circle_generator.cpp

With https://github.com/orocos/orocos_kinematics_dynamics/commit/d54536898cadf3aed1a75cfed7b7ff14d3c29b20 KDL already takes care of deleting the passed object, so we don't need to do this in case of an exception. This fixes the current CI failure affecting the PILZ tests.

Fix double delete in PILZ CIRC generation

---

moveit_core/package.xml
moveit_kinematics/package.xml
moveit_planners/chomp/chomp_interface/package.xml
moveit_planners/chomp/chomp_motion_planner/package.xml
moveit_planners/chomp/chomp_optimizer_adapter/package.xml
moveit_planners/ompl/package.xml
moveit_planners/pilz_industrial_motion_planner/package.xml
moveit_planners/pilz_industrial_motion_planner_testutils/package.xml
moveit_plugins/moveit_ros_control_interface/package.xml
moveit_plugins/moveit_simple_controller_manager/package.xml
moveit_ros/benchmarks/package.xml
moveit_ros/hybrid_planning/package.xml
moveit_ros/move_group/package.xml
moveit_ros/moveit_servo/package.xml
moveit_ros/occupancy_map_monitor/package.xml
moveit_ros/perception/package.xml
moveit_ros/planning/package.xml
moveit_ros/planning_interface/package.xml
moveit_ros/robot_interaction/package.xml
moveit_ros/visualization/package.xml
moveit_ros/warehouse/package.xml
moveit_setup_assistant/package.xml

Make moveit_common a 'depend' rather than 'build_depend'

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

moveit_configs_utils doesn't seem to respect the `ompl_planning.yaml` in the robot_moveit_config/config folder and instead loads the default planner configs even if they are defined in the robot's `ompl_planning.yaml` - I encountered this issue when trying to use the panda demo launch from moveit_resources.
Not sure if this is the correct way to go about fixing this, but as far as I can tell, if the planning pipeline from [moveit_configs_utils](https://github.com/ros-planning/moveit2/blob/78574bc1459eb34ac0aeecbb04cc96715ce0b713/moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py#L475-L477) is used, the `"move_group"` key is never added to the moveit_configs.planning_pipelines. The `"move_group"` key was added [in the launch …

Change condition for loading default OMPL config

---

moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp

The name `ss` cannot be used with `RCLCPP_INFO_STREAM`.
This is a bug in rclcpp.
This is a backport of #1140, as mergify seems to not allow backporting closed PRs.
The changes only apply to the galactic branch, not to the main branch

[pilz_industrial_motion_planner] Fix logging

---

.docker/source/Dockerfile

Turns out this is just another small syntax error.
Closes #1236.
Tested https://github.com/ros-planning/moveit2/actions/runs/2314423050.

Fix foxy docker

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/iterative_spline_parameterization.cpp
moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp

Fix the errors produced by clang-tidy that's blocking #1240 
(I shake my fist at you @AndyZe !)

Tidy up the mess

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

Additional argument in `MoveItConfigsBuilder` constructor to allow for arbitrary path names, and not just those ending in `_moveit_config`. 

Alternate Package Name Specification

---

moveit_setup_assistant/moveit_setup_framework/src/package_settings_config.cpp

I poorly documented the logic here, so I screwed up the reimplementation in a previous PR (#1212)

[MSA] Fix loading from previous config

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

Backport of https://github.com/ros-planning/moveit/pull/3124

Fix bug in applying planning scene diffs that have attached collision objects (#3124)

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Publishing doesn't require spinning, this is sometimes causing an exception `Node '/move_group_interface_node' has already been added to an executor`

move_group_interface: No need to spin after publishing

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

Fix bug described in https://github.com/ros-planning/moveit2/pull/1254#pullrequestreview-975066006

Flexibility in moveit_configs_utils reading of .setup_assistant

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

- Add options to config for publishing description
- Fix clang-format-12 errors
This fix adds support to moveit_config_utils for the two parameters that determine if the robot description is published on a latched topic. This is useful for reducing the amount of boilerplate in launch files and in some cases making so some launch files don't need to be written at all.
This change is necesary for keeping the tutorials I am writing simple.
I also included two changes from running clang-format-12 over moveit in this. I've tested this change on 22.04 on Rolling.

publish robot description config

---

moveit_core/planning_scene/test/test_planning_scene.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp
moveit_core/utils/src/message_checks.cpp

Fix: https://github.com/ros-planning/moveit_task_constructor/issues/350
The first commit fix `isEmpty` for ROS2 since `w == 1` 
The second commit fix a corner case for TOTG where it might not use the last input waypoint when parameterizing the trajectory
To test run:
```
ros2 launch moveit_task_constructor_demo demo.launch.py
ros2 launch moveit_task_constructor_demo pickplace.launch.py
```

Fix a bug when checking a pose is empty and TOTG corner case

---

moveit_planners/pilz_industrial_motion_planner/CMakeLists.txt

Fix: https://github.com/ros-planning/moveit2/issues/1248

Fix exporting PILZ's move_group capabilities

---

moveit_ros/hybrid_planning/CMakeLists.txt

Humble and Rolling [buildfarm](https://build.ros2.org/job/Hbin_uJ64__moveit_hybrid_planning__ubuntu_jammy_amd64__binary/) has been failing with the following error:
```
14:25:06 CMake Error at CMakeLists.txt:15 (find_package):
14:25:06   By not providing "Findposition_controllers.cmake" in CMAKE_MODULE_PATH this
14:25:06   project has asked CMake to find a package configuration file provided by
14:25:06   "position_controllers", but CMake did not find one.
14:25:06 
14:25:06   Could not find a package configuration file provided by
14:25:06   "position_controllers" with any of the following names:
14:25:06 
14:25:06     position_controllersConfig.cmake
14:25:06     position_controllers-config.cmake
14:25:06 
14:25:06   Add the installation prefix of "position_controllers" to …
```

Remove position controllers from Hybrid Planning CMake

---

moveit_kinematics/cached_ik_kinematics_plugin/README.md
moveit_planners/chomp/chomp_optimizer_adapter/chomp_optimizer_adapter_plugin_description.xml
moveit_ros/perception/moveit_depth_self_filter.xml

Remove the "lib"/ "lib/lib" prefix in the plugin library path names according to ROS2 standard: https://docs.ros.org/en/galactic/Tutorials/Pluginlib.html
This resolves https://github.com/ros-planning/moveit2/issues/1260

Update plugin library paths

---

README.md

- Change MoveIt logo to not have the "2" anymore (2 is default)
- Cleanup links and old references. We now have real tutorials, are not on foxy, and are basically done with migration
- De-emphasize doxygen building (move to bottom)

Update README and emphasize MoveIt 2 as default version

---

moveit_ros/hybrid_planning/CMakeLists.txt
moveit_ros/hybrid_planning/global_planner/global_planner_component/include/moveit/global_planner/global_planner_component.h
moveit_ros/hybrid_planning/global_planner/global_planner_component/src/global_planner_component.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/include/moveit/hybrid_planning_manager/hybrid_planning_manager.h
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/local_planner_component.h
moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
moveit_ros/hybrid_planning/test/CMakeLists.txt
moveit_ros/hybrid_planning/test/cancel_action.cpp
moveit_ros/hybrid_planning/test/launch/hybrid_planning_common.py
moveit_ros/hybrid_planning/test/launch/hybrid_planning_demo.launch.py

Action cancellation wasn't working well, so...
- Move long-running callbacks into new threads
- Make a unique callback group for each action server
- Add a script to test cancellation
Test with:
`ros2 launch moveit_hybrid_planning hybrid_planning_demo.launch.py`
`ros2 run moveit_hybrid_planning cancel_action`
This work is sponsored by RE2 Robotics.

[Hybrid Planning] Improve action cancellation

---

moveit_configs_utils/moveit_configs_utils/launches.py

IT BELONGS IN ~~A MUSEUM~~ THE CONFIG FOLDER

Change default rviz location

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

Fix: https://github.com/ros-planning/moveit2/issues/1292#issuecomment-1144044715, this reduces the duplication and make the class easier to read

Decorate MoveItConfigs with dataclass

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

Add an OMPL print at the DEBUG level. This would have helped us in tracking down a recent bug.
I modified `moveit_resources_panda_moveit_config/launch/demo.launch.py` to print at the DEBUG level:
```
.
.
.
move_group_node = Node(
package="moveit_ros_move_group",
executable="move_group",
output="screen",
parameters=[moveit_config.to_dict()],
arguments=["--ros-args", "--log-level", "debug"],
)
.
.
.
```
Run the demo to see the printout. You will see the printout upon clicking Plan:
`ros2 launch moveit_resources_panda_moveit_config demo.launch.py`
The printout from OMPL looks like this:
```
[move_group-4]   - signature: 2 0 7 
[move_group-4]   - dimension: 7
[move_group-4]   - extent: 33.5633
[move_group-4]   - sanity checks for state space passed
[move_group-4]   - probability of valid …
```

Add a debug print for OMPL

---

moveit_configs_utils/default_configs/trajopt_planning.yaml

Since TrajOpt is [currently out of service in ROS 2](https://github.com/ros-planning/moveit2/blob/99c73e6697927c764ea139bbec32e986563edbf8/moveit_planners/trajopt/README.md?plain=1#L1), remove the default parameters from `moveit_configs_utils`. 

Remove TrajOpt Default Parameters

---

moveit_configs_utils/moveit_configs_utils/launches.py

Because https://github.com/ros-planning/moveit2/pull/1265 added a value for `publish_robot_description_semantic`, the value specified in the [move_group launch](https://github.com/ros-planning/moveit2/blob/7427a8ead23955f69bf9e530bbd06e93f8dcfae0/moveit_configs_utils/moveit_configs_utils/launches.py#L205) is overwritten. 
Either we should fix this by changing the order the parameters are loaded (as in this PR) OR the default value of `publish_robot_description_semantic` should be true. 

Fix moveit_configs_utils parameter ordering

---

.github/dependabot.yml

Add dependabot to keep up to date with changing gh actions and docker action versions.
Inspired by what navigation2 does.

Add dependabot for docker and gh actions

---

moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py

May fix #1335.
This updates the ros2_controller launching to be up-to-date with the latest.
I used the same technique in this moveit2_tutorials PR:  https://github.com/ros-planning/moveit2_tutorials/pull/389

Update Servo ros2_control launching

---

moveit_setup_assistant/moveit_setup_app_plugins/src/perception_config.cpp
moveit_setup_assistant/moveit_setup_controllers/src/moveit_controllers_config.cpp
moveit_setup_assistant/moveit_setup_controllers/src/ros2_controllers_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/srdf_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/urdf_config.cpp
moveit_setup_assistant/moveit_setup_srdf_plugins/src/planning_groups.cpp

I had a lot of extra parentheses because of the bug fixed here: https://github.com/ros2/rclcpp/pull/1820

[MSA] Clean up extra parentheses

---

moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
moveit_core/robot_state/src/cartesian_interpolator.cpp

Overloads of `CartesianInterpolator::computeCartesianPath` may return a distance or a percentage value, while the return type is always `double`. This PR introduces type safety for these return values.

Type safety for CartesianInterpolator

---

moveit_core/robot_model/src/planar_joint_model.cpp

Fixes `PlanarJointModel::satisfiesPositionBounds` to correctly check for all 3 positions instead of the 0-th position 3 times.
Replaces https://github.com/ros-planning/moveit2/pull/1327

Fix PlanarJointModel::satisfiesPositionBounds

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

The noted PR swapped boost::thread to std::thread - however
std::thread will cause the program to crash with a note that
TERMINATE CALLED WITHOUT ACTIVE EXCEPTION if the thread object
goes out of scope while not joinable. Detaching the thread
restores the original workflow prior to the PR and allows
users to send more than one trajectory via the motion planning
plugin in RVIZ (otherwise, it crashes on the first trajectory).

fix regression from #1331

---

moveit_setup_assistant/moveit_setup_framework/src/double_list_widget.cpp
moveit_setup_assistant/moveit_setup_srdf_plugins/src/planning_groups_widget.cpp

Fix two bugs found by @mikeferguson 
* In my helper method `DoubleListWidget::getSelectedValues()`, I was initializing the size of the vector, not reserving it, resulting in blank strings added to the vector. 
* The code for `PlanningGroupsWidget::saveLinksScreen()` had a copy/paste error from `saveJointsScreen`

[MSA] Fix SRDF Initialization Bug / Copy Paste Error

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

this implements #1297 - also requires some changes to the MSA, which will be a separate PR to that feature branch. The changes are namely:
* "sensors" is expected to be a vector of strings (sensor names)
* the sensor config then needs to be namespaced under the sensor name provided
* all of the distance/padding parameters need to be floating point - not integer or string.
Example of changes to get a working configuration: https://github.com/mikeferguson/ubr_reloaded/commit/45b9e52ac6ef04c9a0fd94f8a2d18956739a278f

load sensors_3d.yaml

---

moveit_setup_assistant/moveit_setup_app_plugins/src/perception_config.cpp
moveit_setup_assistant/moveit_setup_app_plugins/src/perception_widget.cpp

This mostly handles https://github.com/ros-planning/moveit2/issues/1388 - it is still possible to enter an integer where a float is required (or to leave a field blank and end up with a string), but it's a big improvement over what we currently have

update format of msa sensors_3d config

---

moveit_setup_assistant/moveit_setup_app_plugins/src/perception_config.cpp

Initial export works, but then we lose the sensor names

msa: fix bug in sensors_3d re-export

---

moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/controller_edit_widget.hpp
moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/controllers.hpp
moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/controllers_config.hpp
moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/moveit_controllers.hpp
moveit_setup_assistant/moveit_setup_controllers/src/controller_edit_widget.cpp
moveit_setup_assistant/moveit_setup_controllers/src/controllers_widget.cpp
moveit_setup_assistant/moveit_setup_controllers/src/moveit_controllers_config.cpp

Fixes #1392 
Maybe a bit overengineered, but adds the `action_ns` and `default` parameters to `moveit_controllers.yaml`. 
Also, changed one thing about outputting the joints. I couldn't find any code to support reading a single value for the `joint` parameter so I removed that. I also deleted the `gains` parameter output. 

[MSA] Add additional parameters to Controller definitions

---

moveit_setup_assistant/moveit_setup_controllers/src/control_xacro_config.cpp

When more than one controller can control a joint, that joint would appear multiple times. Fixes #1390

msa: fix duplicated ros_control joints

---

README.md

https://github.com/ros-planning/moveit2/pull/1307 removed the link and I would like to add it back as reference.
I will also add a more prominent link to the moveit/README.md in a moment.

Add reference to MoveIt for ROS one back

---

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/src/robot_state.cpp

This adds a generic cost function to be utilized by kinematics solvers, `kinematics::KinematicsBase::IKCostFn`. An instance of such may be passed to `KinematicsBase::searchPositionIK`. Additionally, it may be passed to `CartesianInterpolator::computeCartesianPath` and `RobotState::setFromIK`, where it is simply passed through to the kinematics solver.

Add generic cost function to KinematicsBase, CartesianInterpolator, Robot State

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/unit_test_servo_calcs.test.py
moveit_ros/moveit_servo/test/pose_tracking_test.cpp

This changes servo to utilize a kinematics plugin if one is defined. If one is not present or doesn't support the group, default to inverse Jacobian
Also updated servo_example launch file to use MoveItConfigsBuilder.
To test, the current moveit_servo tutorial can be used as is. The modification of the servo_example launch file in this repository also includes a reference to kinematics.yaml for the servo node.
The kinematics plugin used by the servo node is defined via ROS parameters, which may be loaded from a yaml file. If using `MoveItConfigsBuilder` in your servo launch file (as is done in `servo_example.launch.py` in this PR), you can pass the necessary parameters as such:
```python
moveit_config = (
MoveItConfigsBuilder("moveit_resources_panda") …
```

Use kinematics plugin instead of inverse Jacobian for servo IK

---

moveit_ros/planning/rdf_loader/CMakeLists.txt
moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h
moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/synchronized_string_parameter.h
moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_ros/planning/rdf_loader/src/synchronized_string_parameter.cpp
moveit_ros/planning/rdf_loader/test/boring_string_publisher.cpp
moveit_ros/planning/rdf_loader/test/data/gonzo.srdf
moveit_ros/planning/rdf_loader/test/data/gonzo.urdf
moveit_ros/planning/rdf_loader/test/data/kermit.srdf
moveit_ros/planning/rdf_loader/test/data/kermit.urdf
moveit_ros/planning/rdf_loader/test/data/robin.srdf.xacro
moveit_ros/planning/rdf_loader/test/launch/test_rdf_integration.test.py
moveit_ros/planning/rdf_loader/test/test_rdf_integration.cpp
moveit_ros/visualization/robot_state_rviz_plugin/include/moveit/robot_state_rviz_plugin/robot_state_display.h
moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp

#765 for foxy (with a little bit of #1050 and #1132)

[foxy] Latched Strings for URDF and SRDF

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Provided a fix for [issue  #1239](https://github.com/ros-planning/moveit2/issues/1239#issue-1232732923).

Changed 'return false' in plan, move and execute such that MoveItErrorCode is returned

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

The initial implementation with the private node allowed for concurrent spinning of the same node, producing runtime exceptions.     This change removes the need for a private node by letting MGI manage its own CallbackGroup and Executor thread.
Fixes #1302

Fix Callback execution in MGI

---

moveit_runtime/package.xml

Uncomment a dependency since the package is available now.
The comment referred to `moveit_ros_perception` which has been available for awhile now, already.  (https://github.com/ros-planning/moveit2/pull/307)

Uncomment moveit_ros_perception dependency

---

moveit_core/kinematic_constraints/src/utils.cpp
moveit_planners/ompl/ompl_interface/scripts/generate_state_database.cpp
moveit_planners/ompl/ompl_interface/src/detail/constraints_library.cpp

On galactic the generate_state_database script is not working. 
This PR solves 3 issues that were blocking it from working properly.
To reproduce simply run the generate_state_database node as follows
```shell
ros2 run moveit_planners_ompl generate_state_database --ros-args -p planning_group:=mygroup
```
The error you get is
```
[FATAL] [1656670955.089432190] [moveit.planners_ompl.generate_state_database]: ~planning_group parameter has to be specified.
```
This happens because none of the parameters that this node uses are declared before the `get_parameter` method is called.
The first commit simply adds the `automatically_declare_paramters_from_override(true)` to the node option.
This should be fine for such an isolated script. 
Once the previous issue is fixed, you get the following …

Fixes for using generate-state_database

---

moveit_setup_assistant/moveit_setup_controllers/src/moveit_controllers_config.cpp

MoveIt Setup Assistant should write the controller namespace to the yaml file, like this:
```
arm_controller:
type: FollowJointTrajectory
action_ns: follow_joint_trajectory
joints:
- J1
...
- J6
```
Fixes #1514

MSA: write the default controller namespace

---

moveit_core/version/version.h.in
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast.h
moveit_planners/pilz_industrial_motion_planner/include/joint_limits_copy/joint_limits.hpp
moveit_planners/pilz_industrial_motion_planner/include/joint_limits_copy/joint_limits_rosparam.hpp
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/include/ikfast.h
moveit_ros/visualization/rviz_plugin_render_tools/include/ogre_helpers/mesh_shape.hpp

The changes replace ifndef header include guards with pragma once.
See #882 

Use pragma once as header include guard

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

Attempt to solve https://github.com/ros-planning/moveit2/issues/1328 by checking if Pilz is being used before trying to load pilz_cartesian_limits.yaml. If Pilz is not being used, there shouldn't be a need to have this file.

Only require Cartesian limits if Pilz is used

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/planning/rdf_loader/CMakeLists.txt

`test_servo_singularity` and `test_servo_singularity` are flaky, we should disable them for now. I've created an issue #1531

Disable flaky test_servo_singularity + test_rdf_integration

---

moveit_core/utils/include/moveit/utils/moveit_error_code.h

Adds convenience function to print a MoveItError code

Add error_code_to_string function

---

moveit_core/planning_interface/include/moveit/planning_interface/planning_interface.h
moveit_planners/chomp/chomp_interface/src/chomp_plugin.cpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.h
moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp

Right now it is not possible to use planners other than OMPL with the moveit_cpp interface. The reason for this is the following:
When the plan() method of the planning component gets called, all available planning pipelines are searched based on their name [[1]](https://github.com/ros-planning/moveit2/blob/e89526de24d88fb05eb646a7925de69ba480bfe8/moveit_ros/planning/moveit_cpp/src/planning_component.cpp#L163). These names are provided by moveit_cpp [[2]](https://github.com/ros-planning/moveit2/blob/e89526de24d88fb05eb646a7925de69ba480bfe8/moveit_ros/planning/moveit_cpp/src/planning_component.cpp#L81). The moveit_cpp function that provides the planning pipeline names reads them from an internal map [[3]](https://github.com/ros-planning/moveit2/blob/e89526de24d88fb05eb646a7925de69ba480bfe8/ …

Add planner configurations to CHOMP and PILZ

---

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h

Signed-off-by: Tyler Weaver <tyler@picknik.ai>
This shouldn't break anything and is more consistent with the use of jmg. @wyattrees did you have some reason to make this a non-const ptr?
Also, @wyattrees why does this cost function take a single pose and not a vector of poses?

Const ptr to jmg arg for cost function

---

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/src/joint_model_group.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h

Signed-off-by: Tyler Weaver <maybe@tylerjw.dev>
Use size_t for the index type used by bijection. https://en.cppreference.com/w/cpp/types/size_t is the type returned by `size` methods in the stl and is the standard type for use when indexing.

size_t bijection index type

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection/CMakeLists.txt
moveit_kinematics/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
moveit_planners/ompl/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner_testutils/CMakeLists.txt
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/CMakeLists.txt
moveit_plugins/moveit_ros_control_interface/CMakeLists.txt
moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt
moveit_ros/benchmarks/CMakeLists.txt
moveit_ros/hybrid_planning/CMakeLists.txt
moveit_ros/move_group/CMakeLists.txt
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/occupancy_map_monitor/CMakeLists.txt
moveit_ros/perception/CMakeLists.txt
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/robot_interaction/CMakeLists.txt
moveit_ros/visualization/CMakeLists.txt
moveit_ros/warehouse/CMakeLists.txt
moveit_setup_assistant/moveit_setup_app_plugins/CMakeLists.txt
moveit_setup_assistant/moveit_setup_controllers/CMakeLists.txt
moveit_setup_assistant/moveit_setup_core_plugins/CMakeLists.txt
moveit_setup_assistant/moveit_setup_framework/CMakeLists.txt
moveit_setup_assistant/moveit_setup_simulation/CMakeLists.txt
moveit_setup_assistant/moveit_setup_srdf_plugins/CMakeLists.txt

Trying to build branch `main` on `Galactic`, I ran into the following compiler error:
```
collision_matrix.cpp: In constructor ‘collision_detection::AllowedCollisionMatrix::AllowedCollisionMatrix(const srdf::Model&)’:
collision_matrix.cpp:62:39: error: ‘const class srdf::Model’ has no member named ‘getNoDefaultCollisionLinks’
```
There were actually two issues (having srdfdom part of the current workspace):
- `srdfdom` was missing as an explicit dependency. Its includes were only found accidentally in /opt/ros
- The include order was screwed because moveit_planning_scene's include directories (not comprising srdfdom but /opt/ros) were included before all other includes. The latter are pulled in via `ament_target_dependencies()`, which handles correct ordering for the overlay. Thus srdfdom …

Fix moveit_core building

---

moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_parameters.h

The Doxygen documentation is generated incorrectly due to incorrect comment syntax. This PR corrects the issue

updated comment formatting for correct doxygen generation

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

After #1571, if MoveIt Configs Utils is used and `self.pilz_cartesian_limits` is not set (which can happen if not using Pilz), I get this error when  launching
`[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: 'robot_description_planning'`
This can be seen in https://github.com/ros-planning/moveit2_tutorials/pull/492.
This PR adds a condition checking if `self.pilz_cartesian_limits` is populated before adding parameters.

Do not add Pilz parameters to MoveIt Configs Utils if Pilz is not used

---

.docker/source/Dockerfile

This should fix failing CI for PRs that add dependencies.
CI jobs that trigger the docker builds do not push to docker-hub, they just test building the docker images. This causes a problem when a dependency is added because the step that previously installed all dependencies `ci` is not pushed so the `source` job that attempts to build can use those dependencies.

Install from rosdep in source Docker build

---

moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

The new rolling update has deprecated the usage of function parameter of type `rmw_qos_profile_t` when calling `create_client` function. 
Related issue - https://github.com/ros2/rclcpp/pull/1964
CI fails due to this warning which GCC will promote to an error and fails the build.
```
rclcpp::CallbackGroup::SharedPtr = std::shared_ptr<rclcpp::CallbackGroup>]’ is deprecated: use rclcpp::QoS instead of rmw_qos_profile_t [-Werror=deprecated-declarations]
164 |     query_service_ = node_->create_client<moveit_msgs::srv::QueryPlannerInterfaces>(
|                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
165 |         rclcpp::names::append(opt_.move_group_namespace_, move_group::QUERY_PLANNERS_SERVICE_NAME),
| …
```

Fix deprecated declaration usage

---

.github/workflows/ci.yaml
moveit2.repos
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

Get better detail from planning errors by converting OMPL codes to MoveItErrorCode and returning them.
OMPL code documentation:  https://github.com/ompl/ompl/blob/main/src/ompl/base/PlannerStatus.h
MoveItErrorCode documentation:  https://github.com/ros-planning/moveit_msgs/blob/master/msg/MoveItErrorCodes.msg

Convert OMPL status to MoveItErrorCode in the OMPL interface

---

moveit_ros/robot_interaction/CMakeLists.txt
moveit_ros/robot_interaction/package.xml

This PR addresses the core issue in https://github.com/ros-planning/moveit2/issues/1594, which is a missing dependency that makes moveit2's `robot_interaction` package build successfully if building with a single worker, but fail at linking time otherwise against some functions available in `moveit_core`.

Add moveit_core dependency to robot_interaction

---

moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp

When compiling on macOS, Apple clang (version 13.1.6) throws the same compilation error as the one reported https://github.com/ros-planning/moveit/issues/3157 in MoveIt for ROS1 with the cause being invalid destructor call for C array type. So I made a simple change from C array to `std::array` to make the code more compatible with different C++ STL implementations.

Replace C array with std::array in std::vector template argument

---

moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
moveit_core/collision_distance_field/src/collision_common_distance_field.cpp
moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
moveit_core/collision_distance_field/src/collision_env_distance_field.cpp

Added brace intialization in moveit_core/collision_detection_fcl & moveit_core/collision_detection_field

---

moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

- Express Humble/Rolling differences in #if
- Remove commented out line of code
Instead of disabling the warning for deprecations in CMake, I looked into a way to support both Humble and Rolling in main so we can continue to get the warnings that will help us stay up to date with Rolling.
I found this ROS Answers post about how to write an #if pre-processor statement for detecting the ROS version: https://answers.ros.org/question/9562/how-do-i-test-the-ros-version-in-c-code/
That lead me to this ament package that is used by rclcpp to create a variable based on its version here: https://github.com/ament/ament_cmake/tree/rolling/ament_cmake_gen_version_h/cmake
The code in that generated file has changed over time and isn't exactly what is in the first ROS Answers post and on my machine is …

Express Humble/Rolling differences in #if

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_container.h
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_container.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp

While developing, I found a bug in Pilz where not setting joint acceleration limits causes us to directly access a map with a non-existent key and segfault while validating a trajectory against joint limits.
This had already been handled for the position and velocity limits by first checking the existence of this key using `hasLimit()`, so it just required a little bit of copy-paste for the acceleration / deceleration case.
NOTE: As this work is doing in service of MoveIt Studio, it should be backported to Humble.

Add joint acceleration validator methods to Pilz limits container

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h

Clock is never set or used by any of the methods.

Remove clock from RobotTrajectory

---

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

Fixes #1552, change to logic when enforcing constrained planning state space in the mixed constraint case.
When running the constrained planning tutorial with:
`ros2 launch moveit2_tutorials ompl_constrained_planning.launch.py`
You should see the following log for the last example (required debug log level):
`[moveit.ompl_planning.planning_context_manager]: planning_context_manager: Using OMPL's constrained state space for planning.`

Fix logic with enforcing constrained planning state space

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

This avoids hiding the (likely) bug where an incorrect state name is given
Replaces https://github.com/ros-planning/moveit2/pull/1579

Log when named target does not exist

---

moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
moveit_core/robot_state/src/cartesian_interpolator.cpp

Port from Noetic of https://github.com/ros-planning/moveit/pull/3197.
Prepares addressing https://github.com/ros-planning/moveit_task_constructor/issues/359 (see https://github.com/ros-planning/moveit_task_constructor/issues/380 as well.)

Improve Cartesian interpolation

---

moveit_commander/src/moveit_commander/planning_scene_interface.py
moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/path_circle_generator.h
moveit_ros/planning/launch/collision_checker_compare.launch

- Load robot_description via planning_context.launch
- auto_create_ikfast_moveit_plugin.sh: allow xacro input
- Fix run_quiet()
- Adjust python PSI to new CollisionObject.pose interface (#3176)
- Add missing header for std::unique_ptr (#3180)
These are changes that do not have a moveit2 PR associated with them as they were forward ports from moveit1.

Backport to Humble

---

.github/workflows/ci.yaml
moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h
moveit_core/planning_request_adapter/src/planning_request_adapter.cpp
moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/add_ruckig_traj_smoothing.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/empty.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_collision.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_path_constraints.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_workspace_bounds.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/resolve_constraint_frames.cpp

Previously, if one of the planning request adapters failed, the pipeline would continue onward anyway. Also, only a `bool` was returned, although `moveit_msgs::MoveItErrorCodes.msg` has some enums to report more detail.
This PR short-circuits in case there is an adapter failure and reports the actual error code.
For example, here's the output when there are 6 adapters and `FixStartStateCollision` fails:
```
[moveit_cpp_tutorial-4] [ERROR] [1665063576.588225372] [moveit_ros.fix_start_state_collision]: Running 'Fix Start State In Collision'
[moveit_cpp_tutorial-4] [WARN] [1665063576.588230842] [moveit_ros.fix_start_state_collision]: Unable to find a valid state nearby the start state (using jiggle fraction of 0.020000 and 100 sampling attempts).
[moveit_cpp_tutorial-4] [ERROR] …
```

Planning request adapters: short-circuit if failure, return code rather than bool

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/lma_kinematics_plugin/CMakeLists.txt
moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/lma_kinematics_plugin.h
moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_parameters.yaml
moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp

Use `generate_parameter_library` to load LMA kinematics parameters
TODO:

Use generate_parameter_library to load LMA kinematics parameters

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/srv_kinematics_plugin/CMakeLists.txt
moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.h
moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_parameters.yaml
moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp

Use `generate_parameter_library` to load srv kinematics parameters

 Use generate_parameter_library to load srv kinematics parameters

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_parameters.yaml
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin-inl.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h

Use `generate_parameter_library` to load cached ik kinematics parameters

Use generate_parameter_library to load cached IK kinematics parameters

---

.github/workflows/ci.yaml

This cleans up the TODO [here](https://github.com/ros-planning/moveit2/blob/66a64b4a72b6ddef1af2329f20ed8162554d5bcb/.github/workflows/ci.yaml#L39):  
```
AFTER_SETUP_UPSTREAM_WORKSPACE_EMBED: sudo apt remove -y ros-${{ matrix.env.ROS_DISTRO }}-moveit-msgs || true
```

Switch back to the moveit_msgs debian

---

moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/CMakeLists.txt
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_ikfast_kinematics_parameters.yaml
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp

Use `generate_parameter_library` to load prbt ikfast kinematics parameters

 Use generate_parameter_library to load prbt ikfast kinematics parameters

---

moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py
moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast_kinematics_parameters.yaml

Use `generate_parameter_library` to load ikfast kinematics parameters

 Use generate_parameter_library to load ikfast kinematics parameters

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_kinematics/kdl_kinematics_plugin/CMakeLists.txt
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h
moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_parameters.yaml
moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp
moveit_kinematics/package.xml

Use `generate_parameter_library` to load KDL kinematics parameters
How to assign the KDL parameters in `kinematics.yaml` file
```
panda_arm:
kinematics_solver: "kdl_kinematics_plugin/KDLKinematicsPlugin"
kinematics_solver_search_resolution: 0.005
kinematics_solver_timeout: 0.05
joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
joint1:
weight: 2.0
joint5:
weight: 1.5
max_solver_iterations: 200
epsilon: 0.0001
orientation_vs_position: 0.2
position_only_ik: false
```
TODO:

Use generate_parameter_library to load KDL kinematics parameters

---

moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/package.xml

This should fix the build error for the `moveit_resources_prbt_ikfast_manipulator_plugin` package

Add missing depend in package.xml

---

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h

Remove the function once the following PRs are merged
https://github.com/ros-planning/moveit2/pull/1671
https://github.com/ros-planning/moveit2/pull/1673
https://github.com/ros-planning/moveit2/pull/1674
https://github.com/ros-planning/moveit2/pull/1675
https://github.com/ros-planning/moveit2/pull/1677
https://github.com/ros-planning/moveit2/pull/1680
Update - We have decided to deprecate it instead

Deprecate lookupParam function

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/plan_solutions.hpp
moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.h
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

This PR ports addressed reviews from @rhaschke to MoveIt2. Most importantly, `bool generatePlan(...)` becomes const again :+1: 

Port parallel planning reviews from MoveIt1

---

moveit_ros/moveit_servo/README.md

When we refactored the tutorials site it looks like we killed some links. Do we not have a CI job to catch dead links?
The link was dead. Not it is not. :pray:

Fix dead tutorial link

---

.clang-tidy

... after #214 was fixed in rclcpp.

Re-enable clang-tidy check `performance-unnecessary-value-param`

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h

This lonely function declaration is useless, let's remove it.

Remove unused function in Servo

---

moveit_core/kinematic_constraints/src/utils.cpp

We can use the input orientation here since, as the comment says:
> // orientation of constraint region does not affect anything, since it is a sphere

Small optimization in constructGoalConstraints()

---

moveit2.repos

The latest main version of generate_parameter_library depends on RSL. The changes in that version are unnecessary for moveit2, so moveit2 should depend on a hash.

Use hashed version of generate_parameter_library

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

Noticed this when I was looking at #611 originally. Servo should check the frames it needs to do TF math with exist in the robot state before trying to look them up. 
Can test this before/after by: modifying [this line](https://github.com/ros-planning/moveit2_tutorials/blob/9b1e55f2d665d12742388588f9b0ab2d1b9e0cb0/doc/realtime_servo/src/servo_keyboard_input.cpp#L74) to be an unknown frame, then running the[ servo teleop demo](http://moveit2_tutorials.picknik.ai/doc/realtime_servo/realtime_servo_tutorial.html) with keyboard (arrow keys) input. After this change, Servo will not crash if the command frame is invalid, but will instead print a warning and skip the command.
Note that this might break the test on `checkValidCommand()` when it is re-enabled with #603. If that is merged first, I …

Servo: Check frames are known before getting their TFs

---

moveit2.repos
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/GreedyKCenters.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighborsGNAT.h
moveit_kinematics/package.xml
moveit_planners/chomp/chomp_interface/CMakeLists.txt
moveit_planners/chomp/chomp_motion_planner/CMakeLists.txt
moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/multivariate_gaussian.h
moveit_planners/chomp/chomp_motion_planner/package.xml
moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
moveit_planners/chomp/chomp_optimizer_adapter/CMakeLists.txt
moveit_planners/chomp/chomp_optimizer_adapter/package.xml

`rsl::rng()` seeds a Mersenne twister to the full extent allowed by the `<random>` API so that we can ensure we're getting the highest quality randomness possible. Using this global random number generator also lets us remove a few member variables that existed for this same purpose.
`std::random_shuffle` has been deprecated and removed from the standard so I also replaced the remaining uses of that function with `std::shuffle`.

Use a stronger source of randomness

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h

`future.wait_for()` should not be used with a time obtained from `node_->now()` because of the mix between simulated and system time. This PR fix the issue that the action server would time out with a very slow simulated time.
Note that for technical reasons (cf. below) I cannot compile `main` but that same changes compile when based on `foxy`.
PS: can someone point me to the documentation to test a PR on the `main` branch? I use Foxy and I'm struggling with compiling the `main` branch. The [documentation](https://moveit.ros.org/documentation/contributing/pullrequests/) states that I could base my PR on `foxy` but my last [PR](https://github.com/ros-planning/moveit2/pull/793#pullrequestreview-803865316) was rejected because of this. …

Use emulated time in action-based controller

---

moveit2.repos

With the new sync, this shouldn't be necessary any longer.

moveit_msgs no longer needs to be built from source

---

moveit_common/cmake/moveit_package.cmake
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/ros_bullet_utils.h
moveit_core/collision_detection_bullet/src/bullet_integration/ros_bullet_utils.cpp

This function is regarded as unused in some translation units because it's marked `static` but not used in every single TU where it's included. `static` free functions are typically only used within a single TU as a way to tell the compiler that no other TUs will link to this function.

Add `-Wunused-function`

---

moveit_common/cmake/moveit_package.cmake
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/CMakeLists.txt

Turns out there was no code violating this warning so it's trivial to add this warning back. Not using a parameter is often a sign of bugged code so it's a valuable warning to add. 

Add `-Wunused-parameter`

---

moveit_commander/CMakeLists.txt
moveit_experimental/collision_distance_field_ros/CMakeLists.txt
moveit_experimental/kinematics_cache/v1/kinematics_cache/CMakeLists.txt
moveit_experimental/kinematics_cache/v1/kinematics_cache_ros/CMakeLists.txt
moveit_planners/trajopt/CMakeLists.txt

Most of MoveIt already requires CMake 3.22 but there were a few projects that seemingly missed getting updated. `main` includes 42 instances of `cmake_minimum_required(VERSION 3.22)` and this PR only adds 5 more.

Require CMake 3.22 everywhere

---

moveit_ros/visualization/rviz_plugin_render_tools/src/planning_link_updater.cpp

When building, I get the following message:
```
In file included from /workspaces/ros2-rolling-ws/src/moveit2/moveit_ros/visualization/rviz_plugin_render_tools/src/planning_link_updater.cpp:38:
/opt/ros/rolling/opt/rviz_ogre_vendor/include/OGRE/OgreVector3.h:2:62: note: ‘#pragma message: /opt/ros/rolling/opt/rviz_ogre_vendor/include/OGRE/OgreVector3.h is deprecated, migrate to Ogre.h’
2 | #pragma message( __FILE__ " is deprecated, migrate to Ogre.h")
```
This PR uses Ogre.h instead of the deprecated OgreVector3.h as per the message suggests.

Migrate to Ogre.h

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp

Add a version of TOTG computeTimeStamps() for a fixed num waypoints

---

.github/workflows/ci.yaml

Disable running IK Fast test in CI until https://github.com/ros-planning/moveit2/issues/1773 is fixed.

Disable IK Fast test in CI

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection/CMakeLists.txt
moveit_core/collision_detection_bullet/CMakeLists.txt
moveit_core/collision_detection_fcl/CMakeLists.txt
moveit_core/collision_distance_field/CMakeLists.txt
moveit_core/constraint_samplers/CMakeLists.txt
moveit_core/controller_manager/CMakeLists.txt
moveit_core/distance_field/CMakeLists.txt
moveit_core/dynamics_solver/CMakeLists.txt
moveit_core/exceptions/CMakeLists.txt
moveit_core/kinematic_constraints/CMakeLists.txt
moveit_core/kinematics_base/CMakeLists.txt
moveit_core/kinematics_metrics/CMakeLists.txt
moveit_core/macros/CMakeLists.txt
moveit_core/online_signal_smoothing/CMakeLists.txt
moveit_core/planning_interface/CMakeLists.txt
moveit_core/planning_request_adapter/CMakeLists.txt
moveit_core/planning_scene/CMakeLists.txt
moveit_core/python/tools/CMakeLists.txt
moveit_core/robot_model/CMakeLists.txt
moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_trajectory/CMakeLists.txt
moveit_core/trajectory_processing/CMakeLists.txt
moveit_core/transforms/CMakeLists.txt
moveit_core/utils/CMakeLists.txt
moveit_core/version/CMakeLists.txt

I changed where headers get installed to fix issues with building MoveIt from source when another copy is already installed. By installing all headers inside a `moveit_core` directory, we add an extra layer of indirection that ensures we know what headers are getting used at any given time.
While I was at it, I also made sure to stop using `include_directories` inside moveit_core. CMake best practices are to avoid using `include_directories`, particularly in large projects like this because it makes it difficult to understand what targets have access to what include directories. Removing them from moveit_core makes it easier for us to know what headers we need to install plus it revealed an issue where kinematics_base and robot_model depended on each other. This makes me wonder if perhaps …

Install moveit_core headers within additional moveit_core directory

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h

Tiny readability optimization - makes it a little easier for people to figure out what `path_tolerance_` does

Better TOTG comments

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

I believe TOTG can't handle mixed units well because the `path_tolerance_` parameter is just a scalar value. So there's no good way to measure angular error mixed with linear error. Best just to fail and print a nice warning for the user.

Print a warning from TOTG if the robot model mixes revolute/prismatic joints

---

moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

The first commit seems to show something unexpected - an extra timestep of 0.1s is appended at index 5. The second commit fixes it.
```
/home/andy/ws_ros2/src/moveit2/moveit_core/robot_trajectory/test/test_robot_trajectory.cpp:217: Failure
Expected equality of these values:
initial_trajectory->getWayPointCount()
Which is: 9
10
/home/andy/ws_ros2/src/moveit2/moveit_core/robot_trajectory/test/test_robot_trajectory.cpp:219: Failure
Expected equality of these values:
initial_trajectory->getWayPointDurationFromPrevious(5)
Which is: 0.2
EXPECTED_DURATION
Which is: 0.1
```

Bug fix: RobotTrajectory append()

---

moveit_core/package.xml

This is a proper dependency, and not only a test dependency. It is still needed when building moveit_core with -DBUILD_TESTING=OFF.
The dependency is unconditionally referenced here:
https://github.com/ros-planning/moveit2/blob/fca8e9bd3f41e6bff5aadbf75c494b5cc3fa25ee/moveit_core/CMakeLists.txt#L50

Fix moveit_core dependency on tf2_kdl

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_parameters.yaml
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

Before converting to generate_parameter_library there was no default IK solver. This meant that if you did not specify an IK solver for a given joint group it wouldn't create one. This restores that behavior.

No default IK solver

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

Addresses #1439.
This feeds waypoints into Ruckig in batches of min(100 waypoints, 10% of waypoints).
- If you feed in too many waypoints at once, the output trajectory will have a longer duration than it needs to.
- If you feed in too few waypoints at once, and the trajectory is very long (like 100,000 waypoints), the runtime will be very slow.
Hopefully this is a happy medium. @swiz23 are you able to test this?
This can be tested easily by adding [this line](https://moveit.picknik.ai/main/doc/examples/time_parameterization/time_parameterization_tutorial.html?highlight=ruckig#jerk-limited-trajectory-smoothing) to [moveit_resources/panda/ompl_planning.yaml](https://github.com/ros-planning/moveit_resources/blob/ros2/panda_moveit_config/config/ompl_planning.yaml), then run any of the motion …

Use adjustable waypoint batch sizes for Ruckig

---

moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp
moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp

- Change output level of some prints in CHOMP from INFO to DEBUG to avoid a wall of text at runtime
- Remove newline in kdl_kinematics from
```bash
[moveit_run_benchmark-1] [INFO] [1671539632.233486591] [moveit_kinematics_base.kinematics_base]: Joint weights for group 'panda_arm':
[moveit_run_benchmark-1] 1 1 1 1 1 1 1
```
to
```
[moveit_run_benchmark-1] [INFO] [1671540088.585070396] [moveit_kinematics_base.kinematics_base]: Joint weights for group 'panda_arm': 1 1 1 1 1 1 1
```
I was confused of the old version because this is the only place in MoveIt2 where a new line is added to print the values and I failed to connect `1 1 1 1 1 1 1` to the line above.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the …

Small terminal output adjustments

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/projection_evaluators.h
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

Found this when reviewing something in the OMPL plugin. We don't need these anymore.

Remove ancient OMPL version directives

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp
moveit_ros/planning/plan_execution/src/plan_execution.cpp

This PR fixes some unwinding/bounds issues for continuous joints.
1. If a trajectory that is being unwound from a reference-state starts (i.e. has an initial waypoint) where the continuous joint has a value above 2PI or below -2PI as could be the case when a trajectory from MTC is generated, I have noticed in a project that I was working on that the `running_offset` can be off by a multiple of 2PI leading to 2PI jumps in the command for that continous joint. This occurs because in the current implementation, the running_offset is not only being calculated using the offset between the reference state and the unwound reference state but also the offset between the initial waypoint (**which may not be unwound**) and the unwound current state which is not valid and is like comparing apples …

Fix trajectory unwind bug

---

moveit_ros/move_group/src/move_group.cpp

I found that the `printf` statements were not actually resetting colors in the terminal. So this is a change to keep `printf` color change on the same line. This ensures the color reset is applied because printing the color reset after new lines seems to prevent the color from actually being reset.
Example before making this change:
Example after this change:

keep printf color change on the same line

---

moveit_core/distance_field/src/propagation_distance_field.cpp
moveit_core/robot_state/test/test_aabb.cpp
moveit_core/utils/include/moveit/utils/moveit_error_code.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraint_approximations.h
moveit_ros/hybrid_planning/global_planner/global_planner_component/src/global_planner_component.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/local_constraint_solver_interface.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

You inconsistently use C++ and C msg headers! This PR fixes all occurrences of wrong C header usage.
I'm really wondering why you didn't run into issues due to this before. When including `moveit/utils/moveit_error_code.h`, I'm getting these errors:
```
/opt/ros/rolling/include/moveit/utils/moveit_error_code.h:48:1: error: expected class-name before ‘{’ token
48 | {
| ^
/opt/ros/rolling/include/moveit/utils/moveit_error_code.h:54:43: error: ‘MoveItErrorCodes’ in namespace ‘moveit_msgs::msg’ does not name a type
54 |   MoveItErrorCode(const moveit_msgs::msg::MoveItErrorCodes& code)
```
That's not surprising as the C++ and C types are fundamentally different, e.g.
`moveit_msgs::msg::MoveItErrorCodes` vs. `moveit_msgs__msg__MoveItErrorCodes`.
I guess you include the corresponding `.hpp` …

Fix wrong use of C msg headers

---

moveit_core/distance_field/src/propagation_distance_field.cpp
moveit_core/robot_state/test/test_aabb.cpp
moveit_core/utils/include/moveit/utils/moveit_error_code.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraint_approximations.h
moveit_ros/hybrid_planning/global_planner/global_planner_component/src/global_planner_component.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/local_constraint_solver_interface.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Cleanup msg includes: Use C++ instead of C header (backport #1844)

---

moveit2.repos
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/servo_calcs.cpp

Update the location of the `thread_priority` library which was previously lumped in with the `controller_manager` package

Update the Servo dependency on realtime_tools

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

One of our projects has had some difficulty in switching between a joint trajectory controller and an admittance controller. This adds a parameter so the user can specify which controller they want to execute the trajectory.

Add optional list of controllers to MoveItCpp::execute()

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

Merge with https://github.com/ros-planning/moveit2_tutorials/pull/563
MoveItCpp and PlanningComponent have very similar `execute()` functions. ~~One does not call the other.~~ Here, I advocate for deleting the PlanningComponent version because I don't think something focused on planning should handle execution. If you like this, there are some small updates to make in moveit_tutorials but that is the only effect I foresee.
```
bool PlanningComponent::execute(bool blocking)
MoveItCpp::execute(const std::string& group_name, const robot_trajectory::RobotTrajectoryPtr& robot_trajectory,
bool blocking)
```
If you do NOT like this PR, then can we flip it to delete the MoveItCpp version of `execute()`? AFAIK it is not used anywhere

Do not allow traj execution from PlanningComponent

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

This speedup removes the 100ms delay during a planning time, which increases planning times by a substantial amount. 
For example, my 2 robot arms without this takes 600ms+ to plan. By reducing this sleep to 1ms the plans are then in the 150ms range. 

gigantic speed up to move group interface

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_parameterization.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

In an effort to use dynamic joint velocity, acceleration, or jerk limits it was mentioned by @henningkayser in my moveit_msgs PR here https://github.com/ros-planning/moveit_msgs/pull/144#discussion_r972178123 that scaling should be applied regardless if using default limits or custom limits. This PR creates the necessary changes to accomplish this. 
@AndyZe 
EDIT
This PR also adds another overloaded `computeTimeStamps` function for passing in a vector of JointLimit messages. I found this to be easier to work with in my implementation for integrating dynamic joint limits.

Add velocity and acceleration scaling when using custom limits in Time Parameterization

---

moveit2.repos

Let's stick to stable branches for stable distros. Fixes #1852

Use humble branches for workspace dependencies

---

moveit_ros/planning/moveit_cpp/CMakeLists.txt
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/parallel_planning_callbacks.hpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/plan_solutions.hpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/parallel_planning_callbacks.cpp
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

Add a parallel planning stop condition that will be commonly used. It stops at the first solution from any planner.

Add a default stopping criterion for parallel planning

---

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/utils.h
moveit_core/kinematic_constraints/src/utils.cpp

The first commit is minor cleanup.
The second commit adds a new function, `updateConstraints()`. The idea is, it's annoying and inefficient to construct a new Constraint object every time. This allows the user to update only the important information. If you like the idea, I'll add the other versions, like:
`bool updateConstraints(moveit_msgs::msg::Constraints& constraints,  const geometry_msgs::msg::PoseStamped& pose);`
and so on.

Clean up kinematic_constraints/utils

---

moveit_core/kinematic_constraints/src/utils.cpp

When updating kinematic constraints, the header ought to be updated too.

kinematic_constraints: update the header, too

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection_bullet/CMakeLists.txt

- Sort exports from moveit_core
- Install collision_detector_bullet_plugin from moveit_core
Fixes #1858

Don't use ament_export_targets from package sub folder

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

The ros_control_namespace cant be used with the current code.
It was needed to execute a dual arm demo using two separated namespaces for ros2_control controller manager and move_group node.

reading namespace from parameter

---

.docker/ci-testing/Dockerfile
.docker/source/Dockerfile
.github/workflows/ci.yaml

CI has been failing for a while and I have a feeling that we run out of pulls or ghcr is just broken now (though I haven't find any bug reports with a quick search). This PR switches CI jobs to use dockerhub instead of ghcr, I will try to switch back in the first of Feb to see if that was a pull issue.

Temporarily switch to dockerhub for CI jobs

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

There is a bug where the wrong IK solver plugin is assigned to the planning groups defined in the SRDF. I noticed this issue because I had multiple kinematic plugins defined in my yaml file with different IK solvers and after doing some debug logging, it was definitely apparant that groups that shouldn't be having an IK solver had one and that groups that were supposed to have an IK solver sometimes had the wrong one.
Turns out that in this for loop here within the [`allocKinematicsSolver`](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp#L143) function, we essentially try to assign the first solver within `possible_kinematics_solvers_` to the joint group passed into the function **without even checking to see …

Fix kinematics plugin loader bug

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

There is currently a bug within the `getLoaderFunction` where...even if a planning group does not contain a kinematics solver, it is still added to the `groups_` member variable. This variable as specified [here](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/planning/kinematics_plugin_loader/include/moveit/kinematics_plugin_loader/kinematics_plugin_loader.h#L68) is meant to only hold those planning groups that have a solver specified for them.
This bug can be fixed by moving the line of code that adds a planning group to the `groups_` variable to be after the check to see if that group has a kinematics solver associated with it.
This fixes Issue #1633 (verified by testing on a local project).
@mechwiz, @AndyZe , @nbbrooks 
[//]: # "You can expect a response from a …

Only add planning group if it has a kinematics solver

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/include/moveit_servo/utilities.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp
moveit_ros/moveit_servo/src/utilities.cpp

Likely fixes #1036, #1885 
There are a lot of simplifications here:
- Always keep publishing zero-velocity commands. Previously, we kept track of the number of zero-velocity commands published to try to  prevent spammy messages. I think the extra complexity wasn't worth it.
- If there is not a valid command, don't jump back to the previously-commanded state. This was causing issue #1885. Instead, come to a gradual halt based on the robot's current position.
This was tested by the bug reporter here:  https://github.com/ros-planning/moveit2/issues/1885#issuecomment-1406923402

Servo: always keep publishing zero-velocity cmds. Eliminate possibility of joint jumps

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
moveit_configs_utils/moveit_configs_utils/substitutions/__init__.py
moveit_configs_utils/moveit_configs_utils/substitutions/xacro.py
moveit_configs_utils/setup.py
moveit_configs_utils/test/robot.urdf.xacro
moveit_configs_utils/test/test_xacro.py

This make it possible to pass `LaunchConfiguration` (or any other complex launch substitutable) to the xacro mappings, which remove the need to use an `OpaqueFunction` to access the context (see https://github.com/AndyZe/tiago_moveit_config/commit/054900ae668e0bcf11e831da5affd4fb061c82e4 for an example)
Another thing worth doing is making all the `file_path`s accept `SomeSubstitutionsType`

Add xacro subsititution class and use it for loading urdf & srdf

---

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor_middleware_handle.hpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp
moveit_ros/planning/planning_scene_monitor/test/current_state_monitor_tests.cpp
moveit_ros/planning/planning_scene_monitor/test/trajectory_monitor_tests.cpp

CurrentStateMonitor::waitForCurrentState() was getting stuck in an endless loop when use_sim_time==True and joint_states is not being received, also, it could not be terminated by SIGINT.
Now it should always properly check for the timeout and also checks that the rcl context is still up.
(Originally made for humble branch: see [https://github.com/ros-planning/moveit2/pull/1894](https://github.com/ros-planning/moveit2/pull/1894))

Fix timeout in waitForCurrentState

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

This fixes a bug when no controller_manager is specified and there are no declared class found.
We only create a node when `!controller.empty()` but we access it always later in the code which is causing a segfault.
Same for the executor, I added a check before accessing it otherwise it segfaults for the same reason

TEM: Fix segfault when no manager is specified

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/include/moveit_servo/status_codes.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

This pull request adds paused status code to moveit_servo as suggested by @AndyZe since currently there is no way to know when servo is paused. This is a breaking change as servo status will now be `StatusCode::PAUSED` instead `StatusCode::NO_WARNING` when servo is paused. Also removed `resetServoStatus` which serves no purpose.

Servo: Reflect Servo Paused Status

---

moveit_kinematics/CMakeLists.txt

Also sort `find_package` entries alphabetically.
I had an issue when trying to compile a package that depended on `moveit_kinematics`. IIRC the issue was with `tf2_kdl` but I added also all other packages except `orocos_kdl` which is added separately as `orocos_kdl_vendor` for some reason.
I didn't change and `find_package` line, just sorted them alphabetically.

Add ament export

---

.clang-tidy

Augments #1939 by enforcing the new rule by clang-tidy.
[Here](https://github.com/rhaschke/moveit2/actions/runs/4185935378) is a CI job running clang-tidy on all source files (not only the diff as usually done for PRs).

Limit underscore suffix to non-public members

---

moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp

Currently, the `blocking` arg of `MoveItCpp::execute()` must be true. The case where it's false wasn't handled well.

moveit_cpp: handle the case where blocking==false

---

Doxyfile
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h

I'm working on fixing the dead links in the tutorials, and making it easier to reference the API using [doxylink](https://github.com/sphinx-contrib/doxylink). We need to install a tag file for that to work. Also, the QT property is breaking the references because of the identical naming, with the attached fixed everything works fine.

Doxygen tag

---

moveit_setup_assistant/moveit_setup_app_plugins/package.xml
moveit_setup_assistant/moveit_setup_controllers/package.xml

when installing ros-humble-moveit-setup-assistant from debs, the package cannot currently run due to this missing depend

add missing dependencies on config utils

---

.docker/ci-testing/Dockerfile
.github/workflows/docker.yaml

Fixes https://github.com/ros-planning/moveit2/issues/1970.
The underlying issue was that ci-testing was based on ros-base which didn't provide the same package dependencies. Apt can fix removed or added packages with `dist-upgrade`, but that command is discouraged by hadolint, and it also wouldn't make much sense in the context of reusing image layers in docker.
The fix is to rely on osrf's testing image and to manually install the base dependencies directly from testing. This adds more work to our testing build, but by splitting it out into a separate RUN command we can rely on the build cache most of the time (testing is updated very rarely).
New docker images have already been created pushed from this branch.

Fix ci testing

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

Fixes #1995 by updating the deprecated and now removed message fields https://github.com/ros-controls/ros2_control/pull/948.

Update SwitchController API usage

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

Adds a warning message to the `Ros2ControlManager` when timestamps from the controller manager are out of date. Handy for debugging why the moveit plugin does not activate controllers that are available in a `controller_manager` with misconfigured sim time.

Add Warning Message for Out of Date Controller Information

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp
moveit_core/trajectory_processing/test/test_ruckig_traj_smoothing.cpp

Previously I didn't understand the difference between `ruckig::Finished` and `ruckig::Working` so I focused only on `ruckig::Finished`. There's not much documentation but here it is:  https://github.com/pantor/ruckig/blob/master/include/ruckig/result.hpp
This corrects that error and adds a comment. Fixes #1960 
This should significantly speed up Ruckig-smoothed trajectories. I'm seeing speedups in the range of 50% although it depends on the specific robot configuration.
Fixes #1960. It is a port of this MoveIt1 PR:  https://github.com/ros-planning/moveit/pull/3348
@swiz23 @mechwiz @nbbrooks
Plots. The performance is close to optimal but not quite optimal. This makes sense because the iterative process for multiple waypoints involves extending durations in 10% increments -- so it could be …

Fix Ruckig termination condition

---

moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_pr2.h
moveit_core/collision_detection_bullet/src/bullet_integration/bullet_utils.cpp
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp

Changed C-style cast to C++-style cast for the `main` branch. Implemented for void data type.
Changed (data_type)(expression) to static_cast<data_type>(expression) in multiple files and tested by building the packages via colcon.

Changed C-style cast to C++-style cast for void data type

---

moveit_planners/pilz_industrial_motion_planner/test/integration_tests/src/integrationtest_command_list_manager.cpp
moveit_planners/pilz_industrial_motion_planner/test/integration_tests/src/integrationtest_plan_components_builder.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_get_solver_tip_frame.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_pilz_industrial_motion_planner_direct.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_ptp.cpp

Got rid of "new" operator calls by using std::make_shared instead of std::shared_ptr (similarly for std::unique_ptr).
Solves issue #868.

Remove "new" from smart pointer instantiation

---

moveit_planners/ompl/ompl_interface/test/test_planning_context_manager.cpp

This test has become flaky since it was modified to use the OMPL constrained state space. #2015 tracks the flaky test issue.

Temporarily disable TestPathConstraints with the Panda robot

---

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/src/joint_model_group.cpp
moveit_core/robot_model/src/robot_model.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

Made some modifications to TOTG and joint model group to reason in *active* joints, which solves issues with TOTG with mimic joints. I can confirm this change fixed things for a robot configuration with a Robotiq 2f-85 gripper that has mimic joints.
Fixes https://github.com/ros-planning/moveit2/issues/586.

Fix mimic joints with TOTG

---

moveit_planners/ompl/CMakeLists.txt
moveit_planners/ompl/ompl_interface/CMakeLists.txt
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/CMakeLists.txt
moveit_py/src/moveit/moveit_py_utils/CMakeLists.txt

Referred the examples and docs suggested in #1928

Fix overriding binary install 

---

.github/workflows/stale.yaml

Enables a [stale action](https://github.com/marketplace/actions/close-stale-issues) that labels issues and PRs as stale after 45 days, and closes issues after another 45 days. The action also takes care about warning the author appropriately, and it ignores a set of persistent labels. The intention of this is to really only keep issues open that are persistent explicitly (there is a new label for that), or that belong to a roadmap, milestone, etc.. All other issues should require at least some activity within the 3 months of time it would take for this GHA to close them.
Fixes https://github.com/ros-planning/moveit2/pull/2022

Add stale GHA

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/include/moveit_servo/servo_parameters.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_parameters.cpp

This PR originally sought to add a dynamic parameter callback for the `override_velocity_scaling_factor` parameter, but then I realized that the entire dynamic param callback structure wasn't working because we were never setting the `ns` member variable of `ServoParameters` when instantiating.
Confirming this fixes things for me.

Add callback for velocity scaling override + fix params namespace not being set

---

moveit_py/CMakeLists.txt
moveit_py/package.xml
moveit_py/src/moveit/moveit_core/robot_model/joint_model.cpp
moveit_py/src/moveit/moveit_core/robot_model/joint_model_group.cpp
moveit_py/test/unit/test_robot_model.py
moveit_py/test/unit/test_robot_state.py

The unittests for the Python library were in a broken state due to incorrect imports. This fixes issues with import statements and any broken test cases. 
Note: a follow up item is to further develop the test cases for the Python library. I plan to address this at some point but will prioritise API documentation over this.
Closes #1976

Fix python tests

---

.docker/ci-testing/Dockerfile
.github/workflows/docker.yaml

~~The humble Dockerfiles had the ROS distro set to rolling, causing issues in downstream repositories (for example, CI on https://github.com/ros-planning/moveit2_tutorials/pull/644 would fail since there's a mismatch of ROS versions when trying to build the tutorials). This PR fixes the ROS version for the humble Dockerfiles, hopefully resolving any unexpected errors for users of these Dockerfiles as well.~~
Edit: The [`ci-testing` Dockerfile](https://github.com/ros-planning/moveit2/blob/main/.docker/ci-testing/Dockerfile) uses [`osrf/ros2:testing`](https://github.com/osrf/docker_images/blob/master/ros2/testing/testing/Dockerfile) as its base image. This base image has the `ROS_DISTRO` environment variable set to rolling. This PR updates the `ci-testing` Dockerfile to allow overwriting of …

fix humble Dockerfiles - use humble, not rolling

---

moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen_widget.cpp
moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/utilities.hpp
moveit_setup_assistant/moveit_setup_framework/src/urdf_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/utilities.cpp

This PR fixes [Issue 1944](https://github.com/ros-planning/moveit2/issues/1944). When selecting a URDF from a file path, MSA would hang forever before needing to be killed if the URDF was not in a ROS package; with no error messages printed. This was due to an infinite while-loop in the moveit_setup_framework/src/utilities.cpp file when extracting the package name from the file path. This fixes that while-condition to check against the root file path when truncating the path. Also added a catch so if ament throws an error finding the package it will just return an empty filepath instead. 
This PR also adds some error handling to the start screen widget to propagate URDF loading errors to the user via the GUI, rather than just crash. Previous behavior was that when selecting an invalid …

Add URDF Loader Exceptions and Fix Infinite While-Loop when URDF file isn't in a ROS Package

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h

Previously I was confused about whether collision checking for a specific group included descendent links, like end effectors. Henning pointed out, descendent links _are_ included.

Document how collision checking includes descendent links

---

moveit_py/CITATION.cff
moveit_py/README.md

Adds citation to README.md to enable those who use the library to cite it within their work.
Note: the authors list needs to be expanded upon.

Add MoveIt Python Library Citation

---

.docker/ci-testing/Dockerfile
.docker/source/Dockerfile
.github/workflows/ci.yaml
.github/workflows/docker.yaml

Replaces #2042 
In attempt to make CI green on the humble branch as well, we are backporting #2039 (see #2040). However, #2040 is currently blocked by a backport of #1908 (https://github.com/ros-planning/moveit2/pull/2040#issuecomment-1481799820). I also believe that we should backport #2035 so that Docker images behave as expected and don't break CI.
Once this PR is merged into `humble`, we should re-trigger the CI on #2040 to make sure it's green. If so, we can merge #2040 as well.

Backport #1908 and #2035

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_functions.cpp

Within PILZ we call `->getSolverInstance()->getTipFrame()` without checking that `getSolverInstance() != nullptr`. Calling [getSolverTipFrame](https://github.com/ros-planning/moveit2/blob/a622feefe4c2221299132538b55160efec245a3b/moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/tip_frame_getter.h#L75) fixes that

PILZ: Throw if IK solver doesn't exist

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp

This is a port of the MoveIt1 PR:  https://github.com/ros-planning/moveit/pull/3394
The trajectory in the new test looks like this:
Position:
Velocity:
Acceleration:

Fix: TOTG can return vels/accels greater than the limits

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

This PR changes the calculations in `ServoCalcs` to use the central difference to compute the joint velocities more accurately.
Fixes #2077

Compute velocity using central difference

---

moveit_core/robot_model/include/moveit/robot_model/joint_model.h
moveit_core/robot_model/src/joint_model.cpp

This is a port of this MoveIt1 PR:  https://github.com/ros-planning/moveit/pull/3396
We already have versions for satisfiesPositionBounds() and satisfiesVelocityBounds(), why not Acceleration and Jerk too?

Add JointModel::satisfiesAccelerationBounds()

---

moveit_kinematics/package.xml

This dependency is unconditionally used even if tests are disabled.
The dependency is referenced here:
https://github.com/ros-planning/moveit2/blob/3e847e1a3b5548824db8c8ffcd74adcf4513c828/moveit_kinematics/CMakeLists.txt#L16

Fix moveit_kinematics dependency on moveit_ros_planning

---

moveit_py/src/moveit/moveit_core/collision_detection/collision_matrix.cpp
moveit_py/src/moveit/moveit_core/planning_scene/planning_scene.cpp
moveit_py/src/moveit/moveit_core/robot_state/robot_state.cpp
moveit_py/src/moveit/moveit_core/robot_trajectory/robot_trajectory.cpp
moveit_py/src/moveit/moveit_ros/moveit_cpp/planning_component.cpp

Fixing warnings that occur when running [htmlproofer](https://github.com/ros-planning/moveit2_tutorials/blob/main/htmlproofer.sh) against Python API sphinx documentation.

[WIP] Fix Formatting in Python Documentation

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

The variable `ik_base_to_tip_frame_` was being initialized in `ServoCalcs::start()` and  `ServoCalcs::calculateSingleIteration()`  and both places checked if `use_inv_jacobian` was `False`.
Since this variable is only used in [this block](https://github.com/ros-planning/moveit2/blob/dc7643502adbeaa41dfd370605460cfd45f26b7f/moveit_ros/moveit_servo/src/servo_calcs.cpp#L616) which is already inside a ` if (!use_inv_jacobian_)` check. 
The previous 2 initializations can be removed and replaced with a single initialization at the place it is used.

[Servo] Avoid unnecessary checks for initializing `ik_base_to_tip_frame`

---

moveit_ros/moveit_servo/include/moveit_servo/utilities.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/utilities.cpp

Should be merged after #2146 
This PR makes the following conversions into free functions and moves them into utilities.
1. Converting from command frame to MoveGroup frame
2. Converting change in cartesian position (delta_x) to a `Pose` 
These changes help in keeping the code more readable and will make writing tests easier.

[Servo] Make conversion operations into free functions

---

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp

Previously, planning with the VisibilityConstraint could cause segfaults because modifying collision objects in the collision environment is not thread-safe. The planning threads would interfere with each other by trying to add and remove the visibility cone collision object out of sync.
This PR fixes that by creating a local collision environment within `VisibilityConstraint::decide`.
I also modified how VisibilityConstraints are evaluated so that if a negative or zero `target_radius` value is used but valid `max_range_angle` and `max_view_angle` are provided, then the visibility cone check is skipped and the range and view angle checks are performed as usual. Previously setting an invalid `target_radius` value would cause the entire constraint evaluation to be skipped.
While I was at it …

Fix collision checking in VisibilityConstraint

---

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp
moveit_ros/move_group/src/default_capabilities/move_action_capability.h

Removed `margin` argument when checking bounds. 
Raising a new PR with `remove_margin_arg` branch.
Fixes #2090

Fix the `margin` argument for joint bounds checking

---

moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/launch/servo_example.launch.py
moveit_ros/moveit_servo/src/cpp_interface_demo/pose_tracking_demo.cpp
moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/moveit_servo/test/pose_tracking_test.cpp
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp
moveit_ros/moveit_servo/test/test_servo_interface.cpp

Fixes #2162 
This PR adds the `moveit_servo` namespace to MoveIt Servo parameters.

[Servo] Restore namespace to parameters

---

moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h
moveit_core/planning_request_adapter/src/planning_request_adapter.cpp

- Documentation & Cleanups for PlanningRequestAdapter & PlanningRequestAdapterChain classes

Add documentation and cleanups for PlanningRequestAdapter and PlanningRequestAdapterChain classes

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

Update MoveIt Config Builder to parse xacro_args parameter from MSA generated MoveIt 2 configs that use xacro generated robot descriptions.

Parse xacro args from .setup_assistant config in MoveIt Configs Builder

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_parameters.yaml
moveit_ros/moveit_servo/test/config/servo_settings.yaml
moveit_ros/moveit_servo/test/servo_launch_test_common.hpp

This PR removes the following functionalities and related code from `ServoCalcs` as they will be made obsolete by better support in IK solver through cost functions.
- Drift Dimensions
- Control Dimensions

[Servo] Remove soon-to-be obsolete functions

---

sonar-project.properties

Use gcov config type for the code coverage file.

Use gcov instead of lcov for sonar

---

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

The planner id in the motion plan response does not seem to be set by our planner plugins (I tested stomp and OMPL). This fixes it plugin agnostic without overwriting whatever the plugin sets.

Ensure that planner id is set

---

moveit_py/CMakeLists.txt
moveit_py/src/moveit/moveit_py_utils/CMakeLists.txt

To use moveit_py_utils in downstream projects (e.g. MTC), its targets need to be exported.

Export moveit_py_utils' cmake target(s)

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/include/moveit_servo/utilities.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/utilities.cpp

This is effectively a revert of https://github.com/ros-planning/moveit2/pull/2080, just that flat out reverting the commit had a lot of merge conflicts due to newer PRs that landed.
We found this was affecting us in MoveIt Studio in that the velocity scaling was not kicking in correctly. For example, going from `override_velocity_scaling_factor` value of `0.1` to `1.0` did not actually increase the target velocity 10x; it was being damped out by the central difference.
After a bunch of debugging and thinking, I've convinced myself that central differencing is not what we need here -- it's useful for state estimation, but not when we're trying to calculate a command given a known current state and a desired next state. We know exactly what our target velocity should be.
To test:
* Start …

Revert central differencing calculation in servo

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

Currently, if you specify an optimization objective that does not match any of the expected values, the path length optimization objective will be used without warning the user. This can lead to unexpected behaviour if you have mistyped the optimization objective name. This PR adds a warning for this case.

Warn if optimization objective does not match expected values

---

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp

The CSM would spam the log if /joint_states messages includes unkonwn joints. RobotModel::hasJointModel() allows for verifying joint names in a safe way without the error message.

Suppress redundant error message in CSM

---

moveit_ros/move_group/CMakeLists.txt
moveit_ros/move_group/package.xml

- Alphabetic ordering of dependencies
- Using THIS_PACKAGE_INCLUDE_DEPENDS for find_package
- build and install interface target_include_directories
- consistent formatting in CMake
- commented out tests in if test block instead of separate one

Cleanup move_group CMake

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

Found this bug against MoveIt Studio, where hitting a joint limit would make the arm continue moving since we were grabbing `internal_joint_state_` and not `previous_joint_state_` for the `suddenHalt()` function.
Even the comment a few lines above says:
```
// Set the position to the original position, and velocity to 0 for input joints
```

Fix Servo `suddenHalt()` to halt at original state, not commanded

---

moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp
moveit_planners/stomp/src/stomp_moveit_planning_context.cpp
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

Follow up to #2202: Explicitly set the `planner_id` in all the available planner plugins + warn if we're making assumptions about the ID because the planner plugin does not handle it correctly.

Set response planner id in planner plugins and warn if it is not set

---

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

Currently, if `planner_plugin_name_.empty()` & multiple planner plugin classes are defined, we default to the first one (In many cases that is CHOMP because the elements seem to be alphabetically ordered :shrug: ). This PR changes that to throw in case no planner plugin name is defined and multiple options are available because it is more useful to throw here rather than loading a random pipeline.
Also, I added throw statements at the end of the plugin lib exception catch blocks to propagate the exception upwards. Please correct me if that is not correct.

Don't default to random algorithm if no plugin is defined

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h

I was looking through this file in effort to gain some more understanding about #2143, and found a small typo.

Fix typo in model_based_planning_context.h

---

moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp

On ROS humble and rviz2, I realized that collision scenes are not transparent even if their alpha value is not 1.0
This MR fixes this bug.

bug fix: no transparency in collision scenes on rviz

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Resolves #1631 
Currently, if controller `a` is active , `nractive[a]` will be `1`. If it is inactive, `nractive[a]` will be `0`. Assuming controller `a` is active (`nractive[a] = 1`) and controller `b` is inactive (`nractive[b] = 0`), we would follow the second condition (`nractive[a] > nractive[b]`)and return `false`. This means that preference is given to inactive controllers.
In practice, if two controllers A and B are able to control the same number of joints and only controller A is active, `TrajectoryExecutionManager` will select the inactive controller B first and activate it. For a subsequent move, we select the now-inactive controller A, and use that, switching between controller A and B for each move.
This change prioritizes the active controller first, such that if controller …

Prefer to use the active controller if multiple controllers apply

---

moveit_core/kinematic_constraints/src/utils.cpp

Minor change to properly parse the constraints parameter loaded from a yaml file.  As described in the `kinematic_constraints::constructConstraints` function the yaml file needs to have the following structure:
```
name: constraint_name
constraint_ids: [constraint_1, constraint_2]
constraints:
constraint_1:
type: orientation
frame_id: world
link_name: tool0
orientation: [0, 0, 0]  # [r, p, y]
tolerances: [0.01, 0.01, 3.15]
weight: 1.0
constraint_2:
type: position
frame_id: base_link
link_name: tool0
target_offset: [0.1, 0.1, 0.1]  # [x, y, z]
region:
x: [0.1, 0.4]  # [min, max]
y: [0.2, 0.3]
z: [0.1, 0.6]
weight: 1.0
```
Prior to this change this yaml structure fails to load.
- [ x] **Required by CI**: Code is auto formatted using …

fix for kinematic constraints parsing

---

moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Resolve #1632 
This PR adds the ability to execute via MGI while specifying a controller name. This can be useful for more fine control over controller-switching applications for which multiple controllers apply, and it is undesirable to let TrajectoryExecutionManager selet the controller for you.
Related and required change in moveit_msgs: https://github.com/ros-planning/moveit_msgs/pull/160

Specify controller name in MGI execution

---

moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
moveit_ros/moveit_servo/test/pose_tracking_test.cpp
moveit_ros/perception/semantic_world/src/semantic_world.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning/rdf_loader/src/synchronized_string_parameter.cpp
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
moveit_ros/robot_interaction/src/robot_interaction.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
moveit_ros/warehouse/src/save_to_warehouse.cpp

This PR replaces "magic numbers" with SystemDefaultsQos(), making it more readable and possibly more stable.
Fixes #2225

Replaced numbers with SystemDefaultsQos()

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h

Small fix to comment formatting
We probably don't want the word "brief" showing up before the description like this...

Fix comment formatting

---

.github/workflows/ci.yaml

Fixes #2280.
The installed PR branch has been removed by GitHub, so CI silently switched to the official ament/googletest release at version 1.10 producing compiler warnings. This fixes the version to a more recent one by installing a later release tag of the vendor package directly.

Humble: Use googletest 1.11.9000

---

.github/workflows/ci.yaml

The PR branch has been removed by GitHub so that CI was using the official release. The compile warnings have been fixed in a more recent version.

Remove source install of gtest branch in CI

---

moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/src/servo.cpp

This PR adds some info for the users about the limitations of twist frame conversion currently used in Servo.
Ping : @AndyZe  @sea-bass

[Servo] Add additional info about twist frame conversion 

---

moveit_ros/move_group/CMakeLists.txt
moveit_ros/move_group/package.xml
moveit_ros/move_group/src/list_capabilities.cpp
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/package.xml
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp
moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/warehouse/CMakeLists.txt
moveit_ros/warehouse/package.xml
moveit_ros/warehouse/src/save_to_warehouse.cpp
moveit_setup_assistant/moveit_setup_app_plugins/include/moveit_setup_app_plugins/launch_bundle.hpp
moveit_setup_assistant/moveit_setup_core_plugins/src/configuration_files.cpp
moveit_setup_assistant/moveit_setup_framework/CMakeLists.txt
moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/templates.hpp
moveit_setup_assistant/moveit_setup_framework/package.xml
moveit_setup_assistant/moveit_setup_framework/src/templates.cpp
moveit_setup_assistant/moveit_setup_framework/src/urdf_config.cpp

This PR replaces `boost::algorithm::join` with `fmt::join` for string formatting to reduce boost dependencies.
Fixes #2227 

Replaced boost::algorithm::join with fmt::join

---

moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt

This fixes a bug caused by #1677 which accidentally inverted the dependency between the plugin and the base library. This fixes it by making the plugin again depend on the base library, and adding missing dependencies to the base library.
I'm not sure why the base library is necessary. It seems like we could add `ik_cache.cpp` to the plugin library, but I fixed it this way because I would like to request this fix be backported to ROS Iron.
Steps to reproduce (sorry I didn't spend the time to make an MRE)
1. Launch a `moveit_ros_move_group move_group` node with parameters that includes
```yaml
robot_description_kinematics:
some_group_name:
kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
```
2. Observe that it errors with:
```
symbol lookup error: …
```

Fix linking error with cached_ik_kinematics_plugin

---

moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_joint_limits_aggregator.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_pilz_industrial_motion_planner.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_planning_context.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_planning_context_loaders.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_blender_transition_window.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_ptp.cpp

When running pilz unit tests, class_loader reports the following warning:
```
Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
```

Fix class_loader warnings in pilz unit tests

---

moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_scenes.cpp

`rviz_rendering::MovableText` can only display non-mono font family currently, it is pointless to format the values with width (and the length of some label is greater than 10).
```
ss << boost::format("%-10s %-4.2f") % value.first % value.second << '\n';
```
so we can remove `boost` from dependencies.

Remove boost from motion_planning_rviz_plugin

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/config/test_config_panda.yaml
moveit_ros/moveit_servo/demos/servo_keyboard_input.cpp
moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/tests/test_integration.cpp

Fixes #2150 
Previous discussions on https://github.com/ros-planning/moveit2/pull/2301
The problem had boiled down to:
> How do we reconcile that some users (like myself) want the rotation-only part of the twist, whereas others (like those who reported https://github.com/ros-planning/moveit2/issues/2150) want the actual translation+rotation portion of twisting the EE frame w.r.t. the base frame?
This PR addresses  the  above by adding the option for proper twist conversion while preserving the existing method of twist conversion (which is wrong).
The selection is made using the parameter  `apply_twist_commands_about_ee_frame`.
@sea-bass 
@AndyZe

[Servo] Fix Twist transformation 

---

.github/workflows/docker.yaml
.github/workflows/prerelease.yaml

This removes redundant humble tags for the docker images and the pre-release test. Both should be run from the humble branch only.

Remove humble tags from main branch GHA jobs

---

moveit_core/package.xml
moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/test/robot_state_jacobian_benchmark.cpp

I'd like to evaluate some future changes to `getJacobian` that should speed-up the computation. The first step is to measure performance as it is now. This change adds a benchmark for `getJacobian`. This is the current output in my system.
```
-----------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_MoveItJacobian        425 ns          426 ns      1585349
```

Add a benchmark for 'getJacobian'

---

moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/src/collision_monitor.cpp

Fixes #2367 
Many parameters in servo should not be changed during runtime.
This PR sets such parameters as read-only through the generate_parameter_library.
The parameters have also been grouped in a more meaningful manner.
Ping: @sea-bass  @AndyZe

[Servo] Set static parameters as `read-only`

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

This change makes `getJacobian` a little bit more readable (hopefully!), while also making it 2x faster, by removing string comparisons where possible and other little optimizations.
The jacobian benchmark shows a ~2x improvement with respect to HEAD (>500ns), and ~4x with respect to the KDL Jacobian, for the panda robot:
```
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_MoveItJacobian        248 ns          249 ns      2867707
BM_KDLJacobian          1099 ns         1100 ns       634762
```
The recently added Jacobian tests for the different types of joints are also passing.
Also manually tested this with Servo, which I know uses the MoveIt! …

Make getJacobian simpler and faster

---

moveit_ros/benchmarks/src/BenchmarkOptions.cpp

Small fix to disable the need to always configure single and parallel planning pipelines for benchmarks.

Enable running parallel or single pipeline benchmarks

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

When creating the PlanningSceneMonitor a private node is created. (This was done here: #266)
This however doesn't use the declared parameters in the main node. 
I added a check if the parameters exist and updated the default value of the parameter in the private node to this value.

[PSM] Get the parameter values of the main node when declaring them in the private node.

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_interface_extension.h

When using the Pilz motion planner, the following message is printend multiple times:
`Failed loading deceleration limits`
This is due to redeclaration of these parameters.
I check if the parameter is already decalared, and if so, the value is get. Otherwise we declare the parameters.

Fix for already declared deceleration parameters when using Pilz

---

moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_solver.cpp

Modified version of this: https://github.com/RoboStack/ros-humble/blob/main/patch/ros-humble-moveit-resources-prbt-ikfast-manipulator-plugin.patch
Quoting @traversaro
> This seems a use of variable length array (that is not supported on MSVC) and hack to implement a static assert that can be substituted with a C++11's static_assert ?
I used a std::vector as we tend to use C++ types to avoid raw new/delete here in MoveIt.
On the version of ikfast changing in that static_assert. I searched for copies of the ikfast.h header, and it is in two places in our repo, and in both places, the version is 61. When I set the version to what it was in that hack, it failed, complaining that the version is 61 so the old test wasn't working anyway, and we've been compiling with version 61.

PRBT IkFast patch from robostack

---

moveit_core/distance_field/include/moveit/distance_field/distance_field.h
moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h
moveit_core/distance_field/src/distance_field.cpp
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/robot_state/include/moveit/robot_state/attached_body.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
moveit_ros/hybrid_planning/test/hybrid_planning_demo_node.cpp
moveit_ros/move_group/src/move_group.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Issue: [1933](https://github.com/ros-planning/moveit2/issues/1933)
Removed old deprecated functions that are not used anymore (older than 10 months)

Remove old deprecated functions

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection_fcl/CMakeLists.txt

The version of fcl we use has a find module. We should just use it.
See https://github.com/ros-planning/moveit2/issues/2391

Use find_package for fcl

---

moveit_core/collision_detection_bullet/CMakeLists.txt

Attempt to fix https://github.com/ros-planning/moveit2/issues/2402.
- `collision_detection_bullet` was the only subfolder whose install path was updated to `include/moveit_core/moveit` in the 2.5.5 release.
- In this update, the `target_include_directories` was not updated accordingly, causing the issue associated with this PR.

Update `collision_detection_bullet` install path

---

moveit_ros/moveit_servo/tests/test_utils.cpp

This PR makes the servo singularity scaling factor unit tests deterministic by initializing the full robot state (not just active positions) to default values before geting the Jacobian.

Fix Servo singularity scaling unit tests

---

moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/include/moveit_servo/utils/command.hpp
moveit_ros/moveit_servo/include/moveit_servo/utils/datatypes.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/utils/command.cpp

This PR enables using a subgroup of the move_group at runtime without the need to stop servo or switch controllers.

Enable using a subgroup of the move group in servo

---

moveit_ros/planning/planning_pipeline/res/planning_pipeline_parameters.yaml
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

Two small patches for the PlanningPipeline class
- Improve error logging in constructor
- Change default value of request adapter parameter to empty so that a minimal valid pipeline config just requires a planner plugin

Small planning pipeline class fixes

---

moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt

This PR fixes this build error introduced by https://github.com/ros-planning/moveit2/pull/2292, but uncaught because the `trac_ik` plugins are not tested in our CI:
```
The keyword signature for target_link_libraries has already been used with the target `moveit_cached_ik_kinematics_plugin`. 
All uses of target_link_libraries with a target must be either all-keyword or all-plain.
```
See [this link](https://stackoverflow.com/questions/59522267/cmake-rejects-a-second-target-link-libraries-talking-about-keyword-vs-plain) for details why.

Fix CMake error when building cached_ik_kinematics_plugin with trac_ik present

---

moveit_ros/planning/planning_scene_monitor/src/trajectory_monitor_middleware_handle.cpp

I was seeing a stack trace in the tutorials on rolling when trying to execute a motion with the Kinova Gen3 robot.
Turns out the issue was trying to construct an `rclcpp::Rate` with zero frequency in the `TrajectoryMonitorMiddlewareHandle` class, so this PR fixes that.

Protect against zero frequency in TrajectoryMonitorMiddlewareHandler

---

moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp

I don't recall why exactly this has been commented out, but this is ancient and there have been several related fixes to the CSM. I tested this and didn't run into any issues, works as intended.

Re-enable waiting for current state in MoveItCpp

---

moveit_setup_assistant/moveit_setup_framework/src/rviz_panel.cpp

MSA was crashing under certain conditions (#1971) when attempting to interact with the RViz Panel. 
[It seems like the `rviz_common::VisualizationManager`'s `ToolManager` assumes there is at least one tool.](https://github.com/ros2/rviz/blob/59c1485398238551645cf047e93e888995171309/rviz_common/src/rviz_common/tool_manager.cpp#L146), and when none are defined, it will attempt to pass a keypress to a null pointer. 
This PR adds a `MoveCamera` tool, which removes the crash AND means you can pan/zoom the rviz panel to look at the model. 

Fix #1971 - MSA RViz Panel can pan/zoom

---

moveit_ros/moveit_servo/src/collision_monitor.cpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/servo_node.cpp
moveit_ros/moveit_servo/src/utils/command.cpp

We were getting spammed by the servo velocity scaling factor because something was using `RCLCPP_WARN` instead of `RCLCPP_DEBUG`.
Decided to comb through the Servo code and change other possible logging levels that.

Fix logging levels in servo logs

---

moveit_ros/warehouse/src/broadcast.cpp

Simple case of the #2376 refactoring.

Use node logging in warehouse broadcast

---

.docker/tutorial-source/Dockerfile
.github/workflows/tutorial_docker.yaml

Here is the docker job we talked about yesterday. This should build a docker image on the main branch in CI for rolling, humble, and iron and push to the github container registry on pushes to main. The docker tag will be `ghcr.io/ros-planning/moveit2:main-tutorial-${ROS_DISTRO}`. I made it a separate workflow from the docker one because I want this to also run in PRs as a CI job and separate from the normal CI one because I only want it to run on pushes to the main branch.

CI job for building docker images for tutorial on main

---

.docker/tutorial-source/Dockerfile
.github/workflows/tutorial_docker.yaml

main-tutorial-humble-tutorial-source -> main-humble-tutorial-source

Rename tutorial docker

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

ompl's `APPROXIMATE_SOLUTION` is not suitable for actual execution. It just states that we [got closer to the goal](https://ompl.kavrakilab.org/classompl_1_1base_1_1ProblemDefinition.html#a612902cacc3b1a2bcc367a9e82739132):
> If the top found solution is approximate, does not actually reach the desired goal, but hopefully is closer to it
As the most prominent reason for an approximate solution is a timeout, also checking for this case.
Fixes https://github.com/ros-planning/moveit_task_constructor/issues/485

Map ompl's APPROXIMATE_SOLUTION -> TIMED_OUT / PLANNING_FAILED

---

moveit_core/planning_request_adapter/CMakeLists.txt
moveit_core/planning_request_adapter/src/planning_request_adapter.cpp
moveit_core/planning_request_adapter/test/test_planning_request_adapter_chain.cpp

https://github.com/ros-planning/moveit/pull/3464 fixed an issue in the numbering of added path indices.
This PR ports this fix to MoveIt2. As the `added_path_index` vector was moved into the `MotionPlanResponse` struct in #2285, I had to choose a slightly different approach.
The first commit ports the (failing) unit test.
The second commit fixes the bug (and the test).

Port #3464 from MoveIt1

---

moveit_planners/stomp/CMakeLists.txt
moveit_planners/stomp/include/stomp_moveit/math/multivariate_gaussian.hpp
moveit_planners/stomp/package.xml

Getting rid of boost for sampling from a gaussian distribution and instead using standard library functions, wherever available.
Fixes #2166 

Using std types instead of boost for Gaussian sampling

---

moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/collision_env_bullet.h
moveit_core/collision_detection_bullet/src/collision_env_bullet.cpp

Change `addAttachedOjects` to `addAttachedObjects`.
This function is a protected member of `CollisionEnvBullet`, so this may lead to breakages if a user is inheriting from `CollisionEnvBullet`. If we think it's best to deprecate the typo version, I'm also not against making the change in that way.

Fix typo in bullet function name

---

moveit_py/src/moveit/moveit_core/robot_trajectory/robot_trajectory.cpp

This is weird, but the changes in https://github.com/ros-planning/moveit2/pull/2411 that merged without issue ended up breaking the `moveit2_tutorials` repo with this htmlproofer error:
```
Warning, treated as error:
docstring of moveit.core.robot_trajectory.PyCapsule.apply_ruckig_smoothing:2:Block quote ends without a blank line; unexpected unindent.
Error: Process completed with exit code 2.
```
See https://github.com/ros-planning/moveit2_tutorials/actions/runs/6617124169/job/17972803048?pr=796#step:7:20084
I think it has to do with the indents added to the block quotes in some of the new functionality added in this PR.

Fix docstring indentation in newly added trajectory Python bindings

---

moveit_planners/stomp/include/stomp_moveit/cost_functions.hpp

This enables STOMP to optimize on the more precise distance gradient of a constraint set instead of the very imprecise const penalty.

Use constraint distance instead of bool validity in STOMP cost function

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h

Updates structs in `collision_common.h` to use default initialization, instead of constructors.
This should be less error-prone and safer, since it ensures all atomic types have been initialized, but it also enables designated initialization,  e.g.:
```
collision_detection::CollisionRequest request{ .contacts = true };
```

Use default initializers in collision_common.h

---

moveit_py/src/moveit/moveit_core/robot_trajectory/robot_trajectory.cpp

This is the one that will actually fix the `htmlproofer` CI on `moveit2_tutorials`, along with https://github.com/ros-planning/moveit2_tutorials/pull/798... I finally found how to test it locally.

Finally fix errors building new RobotTrajectory Python bindings docs

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/planning_component.cpp

In 63e0c3a the name of set_start_state was changed to set_goal_state.

Fix wrong rename of set_start_state in 63e0c3a

---

moveit_py/src/moveit/moveit_core/collision_detection/collision_common.cpp

the constructor of `CollisionResult` is missing, so we can't use it in python.

[moveit_py] add missing constructor of CollisionResult

---

moveit_py/src/moveit/moveit_ros/planning_scene_monitor/planning_scene_monitor.cpp
moveit_py/src/moveit/moveit_ros/planning_scene_monitor/planning_scene_monitor.h

Removed unused `applyPlanningScene` function.

(moveit_py) remove unused applyPlanningScene

---

moveit_ros/moveit_servo/src/collision_monitor.cpp

We found a bug today where the collision distances were not actually being returned by servo's collision checker. So basically, the distance scaling was never working and you could servo right into a binary "is colliding" state.
For reference, these parameters were on before the refactor: https://github.com/ros-planning/moveit2/blob/humble/moveit_ros/moveit_servo/src/collision_check.cpp#L62-L64
@ibrahiminfinite

Add distance to servo collision checker requests

---

moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/test/test_cartesian_interpolator.cpp
moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp

This change factors out the path joint-space jump detector of `CartesianInterpolator` into a separate function called `hasJointSpaceJumps()`, so that it can be used in a different context.
The new function returns an `std::optional<int>` with the path index where the jump happens, or nothing if there are no jumps.
The `CartesianInterpolator::checkJointSpaceJump` function is then updated to use the free function underneath, and truncate the path, etc, i.e., it keeps the same behavior.
In addition to this, there's two API-breaking changes:
1) Remove the public `CartesianInterpolator::checkRelativeJointSpaceJump` and `CartesianInterpolator::checkAbsoluteJointSpaceJump`, since these can be easily achieved with the more general `CartesianInterpolator::checkJointSpaceJump`, therefore exposing a …

Factor out path joint-space jump check

---

moveit_ros/moveit_servo/src/collision_monitor.cpp

Fixes a thread safety issues in the collision monitor in MoveIt Servo. Basically, the shared atomic double `collision_velocity_scale_` was being reset to `1.0` at the start of each collision check loop, which would sometimes be picked up in the `Servo::getNextJointState`, so the robot ends up moving even though the scene is in collision. E.g.,
```
[component_container_mt-7] ERH TEMP: Servo::getNextJointState, collision_velocity_scale_=1                                                                                                    
[component_container_mt-7] ERH TEMP: CollisionMonitor::checkCollisions, collision_velocity_scale_=1      
```
To fix this, we should use a local variable to compute the new scaling factor, and only set the shared variable at the end of the collision …

Fix threading issue for collision velocity scaling in MoveIt Servo

---

moveit_core/CMakeLists.txt
moveit_core/package.xml

- This should fix #2516
- Several moveit2 packages already depend on rsl
- PR #2482 added a depend in moveit_core
This is only broken when building all of moveit2 deps in one colcon workspace And not using rosdep because colcon uses the package.xml and rsl might not have been built

add rsl depend to moveit_core

---

moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/servo_node.cpp

This fixes another Servo issue we found when resuming Servo after moving through another means, e.g., by running the motion planner to move to a completely different waypoint.
With this fix, the robot shouldn't teleport in these situations.
@ibrahiminfinite

Ensure to reset the smoothing plugin when resuming Servo

---

moveit_core/robot_model/src/floating_joint_model.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

From debugging some strange trajectory tests, we found a bug in the angular distance calculation of floating joints. Eigen to the rescue!

Fix angular distance calculation in floating joint model

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp

This PR adds a mechanism for the planning scene to remember objects' original colors when first added, which helps restore colors to the original when attaching/detaching in RViz.
See the video below. Prior to this PR, the blue object would have turned green when being placed.
https://github.com/ros-planning/moveit2/assets/4603398/ba72dc59-5490-426f-a75e-b765a00880fa

Remember original color of objects in planning scene

---

moveit_ros/planning/planning_response_adapter_plugins/res/default_response_adapter_params.yaml

The default topics for `display_path` and `display_contacts` are the same. This will create a problem since they both construct publishers using the same topic name with different msg types which will produce a segfault.
```
[move_group-4] [INFO] [1701373538.471684625] [move_group]: Try loading adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-4] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[move_group-4]   what():  could not create publisher: create_publisher() called for existing topic name rt/display_planned_path with incompatible type moveit_msgs::msg::dds_::DisplayTrajectory_, at ./src/publisher.cpp:145, at ./src/rcl/publisher.c:117
[move_group-4] Stack trace (most recent call last):
[move_group-4] #22   Object "", at …
```

Change default topic name for display contacts

---

moveit_py/moveit/policies/__init__.py
moveit_py/moveit/policies/policy.py

This pull request begins to add tooling to `moveit_py` that will enable the deployment of learnt policies using the `moveit_servo` package.
Initial example of API usage is being developed [here](https://github.com/ipab-rad/lite6_ws/tree/rolling/src/tutorials/policy_deployment).
Related feature request to help enable registering sensors and `moveit_servo` interface from config: [here](https://github.com/PickNikRobotics/generate_parameter_library/issues/155)

moveit_py: Add Policy Class 

---

moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

Sync with the MoveIt1 commits given in the commit messages.

Sync Ruckig with MoveIt1

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/config/test_config_panda.yaml
moveit_ros/moveit_servo/include/moveit_servo/utils/common.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/utils/common.cpp

Related Issue: #2570
Enabling individual joint_limit_margins for each joint. This is useful, for example, when different types of joints are used. One value for all  margins (as before) is not necessarily suitable for all joints. E.g. when revolute and prismatic joints exist.

Replaced single value joint_limit_margin with list of joint_limit_margin

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

This change updates some methods to avoid an out-of-bounds access after the recent changes to use `std::vector` as the underlying storage in `RobotState` (https://github.com/ros-planning/moveit2/pull/2546).
Before that change, there was nothing stopping us from passing or returning invalid memory addresses. But now that will trigger `range_check` exceptions.
This change fixes an out-of-bounds access that can happen with fixed joint models with a variable count of 0, by special-handling that case where needed. It also moves the implementation of those functions to the source file, to not clutter the header file further.

fix out-of-bounds memory access with zero-variable joints

---

moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

Fixes an issue I introduced in https://github.com/ros-planning/moveit2/pull/2546 and adds a test for it.

reset accelerations on setToDefaultValues

---

moveit_ros/moveit_servo/src/servo.cpp

Trying to make the error messages of moveit_servo::validateParams more expressive.

Making the error messages of moveit_servo::validateParams more expressive.

---

moveit_configs_utils/moveit_configs_utils/launches.py
moveit_planners/test_configs/prbt_moveit_config/launch/demo.launch.py
moveit_planners/test_configs/prbt_support/urdf/prbt.ros2_control.xacro
moveit_ros/hybrid_planning/test/launch/hybrid_planning_common.py
moveit_ros/moveit_servo/launch/demo_joint_jog.launch.py
moveit_ros/moveit_servo/launch/demo_pose.launch.py
moveit_ros/moveit_servo/launch/demo_ros_api.launch.py
moveit_ros/moveit_servo/launch/demo_twist.launch.py
moveit_ros/moveit_servo/tests/launch/servo_cpp_integration.test.py
moveit_ros/moveit_servo/tests/launch/servo_ros_integration.test.py
moveit_ros/moveit_servo/tests/launch/servo_utils.test.py
moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py

Address ros2_control deprecation warnings. More info here: https://github.com/ros-controls/ros2_control/blob/89c8658a3419e4d23aea37eda7b17a0d1eecb840/controller_manager/src/controller_manager.cpp#L276

Update ros2_control usage

---

moveit_core/collision_detection/CMakeLists.txt

It is included by src/collision_plugin_cache.cpp, so it should be set as a dependency.
Add a target_dependency from collision_detection to pluginlib, which is required for building.  This should fix the build on Rolling: https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__moveit_core__ubuntu_jammy_amd64__binary/166/
- [N/A] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [N/A] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [N/A] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [N/A] Create tests, which fail without this PR …

Add collision_detection dependency on pluginlib

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/utils/common.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Following from https://github.com/ros-planning/moveit2/pull/2601, the [`RCLCPP_ERROR` log message when no 3D sensor plugins are available](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor_middleware_handle.cpp#L91) has been loud -- so I put this addition behind a new boolean parameter called `check_octomap_collisions`.
@amalnanavati sharing with you since you made this original PR and would appreciate your input behind this change.
In the process, I also cleaned up a few things I saw.

[Servo] Make listening to octomap updates optional

---

moveit_core/CMakeLists.txt
moveit_core/package.xml

Remove all references to python wrapper from the core pkg

(core) Remove all references to python wrapper from the core pkg

---

moveit2.repos

Turns out we were cloning a pretty old version of `ros2_control` here -- 2.13 when it's now at 2.36.
Maybe this will be the thing to fix the `humble_ci` job on `main` which uses the generated Docker image from this branch since https://github.com/ros-planning/moveit2/pull/2284?

[Humble] Remove ros2_control 2.13 source build

---

moveit_configs_utils/moveit_configs_utils/launches.py

When generating demo launch, allow for separate launch and config packages. If launch_package_path is not provided, default to moveit_config.package_path as previously done. 
This removes the need to have identical duplicate launch files when testing multiple robots.

Use different packages for launch and config packages in generate_demo_launch

---

moveit_planners/stomp/CMakeLists.txt
moveit_planners/stomp/include/stomp_moveit/cost_functions.hpp
moveit_planners/stomp/test/CMakeLists.txt
moveit_planners/stomp/test/test_cost_functions.cpp
moveit_planners/stomp/test/test_noise_generator.cpp

This adds several test cases for STOMP's noise generation and cost functions, and provides the following fixes:
* out-of-bounds vector access when tail states of trajectory are invalid
* smoothed costs overriding values of previous invalid groups
* missing validity check of last state in trajectory
* inability to disable cost function interpolation steps
* total cost of trajectory not summing up to sum of state penalties
* bug in Gaussian producing infinite values with invalid start states
Fixes #2462, #2554

Fix penalty-based cost function in STOMP

---

moveit_ros/move_group/CMakeLists.txt
moveit_ros/move_group/default_capabilities_plugin_description.xml
moveit_ros/move_group/include/moveit/move_group/capability_names.h
moveit_ros/move_group/src/default_capabilities/get_group_urdf_capability.cpp
moveit_ros/move_group/src/default_capabilities/get_group_urdf_capability.h
moveit_ros/move_group/src/move_group.cpp

Requires: https://github.com/ros-planning/moveit_msgs/pull/174
This PR adds the move_group capability to request a urdf containing links and joints of a specific joint model group
1. Launch move_group with the plugin loaded
2. Call service and request urdf of an existing group
```bash
ros2 service call /get_urdf moveit_msgs/srv/GetGroupUrdf group_name:\ \'MY_GROUP\'\
```

Add get group urdf capability

---

moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp

The Cartesian path capability request can have a `jump_threshold` of zero. A 'relative' jump of 0.0 is not allowed. Therefore we need to catch that case and disable the jump threshold if needed.
This became an issue after the changes to the JumpThreshold API.
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/864

avoid a relative jump threshold of 0.0

---

moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp

Backport of #2307 to humble. The [original backport](https://github.com/ros-planning/moveit2/pull/2309) by Mergify included a failing test (`testSingleDofDiscontinuity`), unrelated to the functionality changes in the backport, that's not included in this one.

Exit loop when position can't change. (backport #2307) 

---

moveit_core/robot_model/src/joint_model_group.cpp

I was working on an MTC task a while ago where I was manually modifying the planning scene. In my program I was calling  `getLinkModelNamesWithCollisionGeometry()` on the `JointModelGroup` to get the links of the manipulator that had collision geometry and noticed that the base link of the group is never included. This caused planning problems like this while I was debugging...
To test this change out I modified the moveit2_tutorial `Robot Model and Robot State` where I asked it to print the results of `getLinkModelNamesWithCollisionGeometry` and with this new change it now includes `panda_link0` :1st_place_medal: 
```
RCLCPP_INFO(LOGGER, "Joint model group `panda_arm` collision links:");
std::vector<std::string> collision_link_model_names = …
```

Fix getLinkModelNamesWithCollisionGeometry to include the base link

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Turns out that if the planning scene already had an active publisher, the new options from MoveItCpp would not take effect.
This PR ensures that publishing to a planning scene from MoveItCpp first shuts down other publishers, and if this check fails I added a few warnings that helped me debug this issue.
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/869

Shut down PSM publishing before starting to publish on a potentially new topic

---

moveit_ros/move_group/src/default_capabilities/get_group_urdf_capability.cpp
moveit_ros/move_group/src/default_capabilities/get_group_urdf_capability.h
moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h

If robot description is not passed as a parameter to the move_group node, this service will fail.
The robot description will now be acquired from the `robot_description` topic

Get robot description from topic in GetUrdfService

---

.github/workflows/ci.yaml
.github/workflows/sonar.yaml

Migrate back actions/cache@v4. Which now also supports save-always, but is maintained much better. See https://github.com/pat-s/always-upload-cache/issues/2

(actions) migrate back actions/cache@v4

---

moveit_core/CMakeLists.txt

FCL version of acda563
Make sure the collision_detector_fcl_plugin library is installed.

(core) Install collision_detector_fcl_plugin

---

moveit_core/utils/include/moveit/utils/moveit_error_code.h

Update moveit::core::error_msg_to_string to match updates to moveit_msgs/msg/MoveItErrorCodes.msg. Simply pulled down the file from Iron.
Fixes #2688 

Update moveit::core::error_msg_to_string in Humble

---

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

With this change, the `PlanningPipeline::generatePlan()` exits as soon as a failure is detected. Before this, `break` was used to exit the current loop of request adapters, planners, or response adapters, but the function continued to the next loop. For example, if a planner would fail, the response adapters would still be executed.

Exit earlier on failure in `generatePlan`

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

This avoids a warning `PlanningPipeline::generatePlan()` that `res.planner_id` is not set.

Set `planner_id` in reponses with OMPL interface

---

moveit_ros/planning/planning_pipeline_interfaces/src/planning_pipeline_interfaces.cpp

Return the `MotionPlanResponse` as-is, also in case of error.
The error code was forced-set to `FAILURE` in case of error, preventing the caller to get the correct information in case of error.

Do not overwrite the error code in planWithSinglePipeline

---

moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_collision.cpp

The CheckStartStateCollision adapter does return failure when links are in collision but it currently does not say which links are in collision. This PR adds the links in collision to the MoveItErrorCode message so it can help with debugging.

Print links in collision

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

In case of failure, set the error code to the one returned by the planning pipeline's `solve` method rather than overwriting it with `PLANNING_FAILED`.

Do not overwrite the error code with OMPL interface

---

moveit_ros/move_group/src/default_capabilities/get_group_urdf_capability.cpp

Gets rid of an RCLCPP_ERROR invocation that doesn't have any clear benefit and is making my terminal fill up with the names of joints.

Remove extraneous error message from URDF service

---

moveit_ros/moveit_servo/include/moveit_servo/collision_monitor.hpp
moveit_ros/moveit_servo/src/collision_monitor.cpp

This PR introduces a slight fix to the MoveIt Servo collision checker to make it work with attached objects.
Turns out Current State Monitor has some issues, but Planning Scene Monitor works fine: https://github.com/ros-planning/moveit2/issues/2748

[Servo] Fix collision checking with attached objects

---

moveit_setup_assistant/moveit_setup_controllers/src/ros2_controllers_config.cpp

With the addition of https://github.com/ros-planning/moveit_resources/pull/198/, the YAML equivalence tests in the `moveit_setup_controllers` package was failing. So this adds that line to the exported configs, which is probably a good default if we want users to use MoveIt Servo easily.

Add `allow_nonzero_velocity_at_trajectory_end` parameter to exported `ros2_controllers` config file

---

moveit_ros/moveit_servo/src/servo.cpp

Was debugging something and realized this error message is swapped.
I'll add this later when I'm on a dev computer, but looks like we should also add a check for `  if ((servo_params.command_out_type == "std_msgs/Float64MultiArray") && !servo_params.publish_joint_positions && !servo_params.publish_joint_velocities)`  - The previous check would not trigger that as it is specific to Float64 type.

Fix error message text about invalid servo parameters

---

.docker/ci/Dockerfile
.docker/release/Dockerfile

When installing `rmw-connextdds` within a humble docker image, e.g. via rosdep, this fails, because interactive acceptance of the license is required despite common flags like `--yes`:
https://github.com/ros-planning/moveit_task_constructor/issues/558
https://github.com/ros-planning/moveit_task_constructor/actions/runs/8680352798/job/23800710624#step:4:177
Declaring the environment variable `RTI_NC_LICENSE_ACCEPTED=yes` resolves that issue:
https://github.com/ros-planning/moveit_task_constructor/actions/runs/8680352798

CI: Allow non-interactive installation of rmw-connextdds

---

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh

Ignore missing authentication for Indigo packages using `--force-yes`.
Fixes https://github.com/ros-planning/moveit2/pull/2790#issuecomment-2056545176

CI: Fix building of ikfast plugins

---

moveit2.repos

This PR adds generate_parameter_library as a source build to fix the current build failure. This will be needed until the latest release is fixed.

Add generate_parameter_library source build 0.37 until latest release is fixed

---

moveit_ros/benchmarks/src/BenchmarkExecutor.cpp

Remove a 4 year old TODO and attempt to fix this CI error:
https://github.com/ros-planning/moveit2/actions/runs/8811912791/job/24186660042

Update deprecated include of boost/progress.hpp to boost/timer/progress_display.hpp

---

moveit_ros/planning/planning_request_adapter_plugins/res/default_request_adapter_params.yaml

Currently, the `default_workspace_bounds`  is arbitrarily set to 10. This value can lead to confusion, especially when using a mobile robot. I think setting it to a large number may be a more appropriate default, e.g. no workspace bound exists unless explicitly specified.

Change `default_request_adapter_parameters.default_workspace_bounds` value

---

.github/workflows/ci.yaml
.github/workflows/format.yaml
.github/workflows/tutorial_docker.yaml

This should allow us to begin adopting GitHub Merge Queues so that maintainers can hit "merge when ready" on every approved PR and CI will sort itself out to get all those things merged.

Add `merge_group` event type to all PR CI jobs

---

moveit_ros/planning/planning_scene_monitor/test/launch/planning_scene_monitor.test.py

Skips a PSM launch test that has failed in a number of branches, including #2740, that appears to be performance/latency-related.
Opened an issue #2821 to track re-enabling this once we track down why it's failing.

Skip flaky PSM launch test

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp

Wrapped scene_transforms_, robot_state_, acm_ and object_types_ in std::optional to handle missing data instead of checking for nullptr.
Fixes #2131 

Use std::optional instead of nullptr checking

---

moveit_setup_assistant/moveit_setup_assistant/package.xml

moveit_setup_assistant [attempts to import moveit_configs_utils in its launch file](https://github.com/moveit/moveit2/blob/2.9.0/moveit_setup_assistant/moveit_setup_assistant/launch/setup_assistant.launch.py#L2), but does not declare it in its `package.xml`.

Add dependency on moveit_configs_utils to moveit_setup_assistant

---

.docker/source/Dockerfile
.github/workflows/docker.yaml
moveit2_rolling.repos
moveit_ros/benchmarks/src/BenchmarkExecutor.cpp

CI builds for rolling are broken since a month or so. This PR fixes the docker images as well as some deprecated code.
I am surprised that nobody from the MoveIt2 maintainer team attempted to fix those issues yet.
Essentially, it was just about adding packages to moveit2.repos, which are not yet binary-released.
The `ci-testing` docker file, building upon `osrf/ros2:testing` is broken upstream. I skipped building this image for now as I don't know the intention of using `osrf/ros2:testing`.

Fix CI for Rolling / Ubuntu Noble

---

moveit_ros/perception/mesh_filter/src/gl_renderer.cpp

The misusage of std::map is fixed.

Fix segmentation fault in mesh_filter/gl_renderer

---

moveit_kinematics/cached_ik_kinematics_plugin/README.md

At least on Humble, without explicit double formatting, errors are:
<details>
<summary>stack trace</summary>
```bash
[move_group-4]   what():  parameter 'robot_description_kinematics.robot.min_joint_config_distance' has invalid type: expected [double] got [integer]
[move_group-4] Stack trace (most recent call last):
[move_group-4] #24   Object "", at 0xffffffffffffffff, in 
[move_group-4] #23   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x561c4934c724, in 
[...]
[...]
[...]
[move_group-4] #22   Source "../csu/libc-start.c", line 392, in __libc_start_main_impl [0x7fda8016be3f]
[move_group-4] #21   Source "../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main [0x7fda8016bd8f]
[move_group-4] #20   Object …
```

Fix typo on Cached IK Kinematics Plugin doc

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h

Fails currently on Windows with:
```
error C2146: syntax error: missing ')' before identifier 'and' [%SRC_DIR%\build\moveit_simple_controller_manager.vcxproj]
```

Make compatible with Windows

---

moveit_core/package.xml
moveit_ros/occupancy_map_monitor/package.xml

This is so that we have a consistent ABI between these packages and anything else in the system that depends on octomap.  We'll eventually be removing the ROS-provided version of octomap to make sure we don't have these problems in the future.
This should solve the issue in https://github.com/ros/rosdistro/issues/41622 , and was enabled by the merging of https://github.com/ros/rosdistro/pull/41623
- [N/A] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [N/A] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [N/A] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit2/blob/main/MIGRATION.md) notes
- [N/A] Create tests, which …

Switch to system version of octomap.

---

moveit_py/src/moveit/moveit_ros/planning_scene_monitor/planning_scene_monitor.cpp

Added the new_planning_scene_message function to the planning_scene_monitor in moveitpy.

[Moveitpy] new planning scene message

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp

To allow multiple MoveitPy instances which do not interfere with each other, i've added the namespace parameter. This way it is possible to have multiple, independent planning scene's, each in its own namespace.
If you add the namespace parameter to the launch file, you will also need to add it to the Python constructor.

[MoveitPy] Added namespace to MoveitPy

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

[Port #3610](https://github.com/moveit/moveit/pull/3610/files)

PSM: Correctly handle full planning scene message

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp

This is a forward port of https://github.com/moveit/moveit/pull/3615
* Fix constrained-based planning
Constrained-based planning enables the PoseModelStateSpace by default, meaning that state samples are created by sampling in SE(3) and then performing IK. This state space frequently caused issues, eventually leading to the introduction of the ROS parameter enforce_joint_model_state_space in PR #541 as a work-around.
A more detailed analysis shows that the state space's interpolation approach is the culprit - performing interpolation in Cartesian space. If the two interpolation ends are close in Cartesian but distant in joint space, the interpolated state (obtained from IK) can be far away from both start and end (particularly for redundant arms), while its Cartesian pose is naturally …

Fix constrained-based planning / PoseModelStateSpace

---

moveit_core/planning_scene/src/planning_scene.cpp

The child planning scene should behave as its parent, so the state- and motion- feasibility predicates should be copied as well.
The copy of the collision update callback is treated in a separate commit because I'm not quite sure how to do it properly. I guess that the cloned planning scene should not call the collision update callback to avoid confusion.
Often in the planning scene implementation, the child planning scene uses members of its parent when it doesn't have its own but this is not the case for the predicates so I did copy them.

Copy planning scene predicates in the copy constructor

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

Hello!
This PR aims to start using the non-deprecated fields of the ros2_control service to switch the controllers. If the changes look good, can this be merged and tagged as well?. It's just there is no release of MoveIt2 in Humble since September 2023. Thank you

Use the non-deprecated service fields for switching controllers

---

moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

Address the [newly failing rolling build](https://github.com/moveit/moveit2/actions/runs/10008006352/job/27663837261). They deprecated the use of `rmw_qos_profile_t` in favour of `rclcpp:QoS`.
Unfortunately, fixing the rolling build now invalidates the humble and jazzy builds.
Is there a compile-time version check available to handle this?

Fix deprecation warning

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_setup_assistant/moveit_setup_controllers/templates/config/ros2_control.xacro

Removes deprecation warning 
```
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
```
by updating the template for ros2_control.xacro

Replace deprecated load_yaml with xacro.load_yaml in ros2_control.xacro template

---

moveit_core/planning_scene/src/planning_scene.cpp

Fix segfault caused by https://github.com/moveit/moveit2/pull/2858

Don't set reset observer callback & set CB after world_ is initialized

---

.docker/tutorial-source/Dockerfile
.github/workflows/tutorial_docker.yaml

This is the equivalent of https://github.com/moveit/moveit2_tutorials/pull/937, but for this repo. Should hopefully make CI green.

Install Gazebo in tutorial image Dockerfile

---

moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp

Currently, the ComputeFK service only works for robot links. By using `getFrameTransform` we can also consider attached collision objects and their subframes.

Consider attached collision objects in the ComputeFK service

---

moveit_setup_assistant/moveit_setup_controllers/src/moveit_controllers_config.cpp

Moveit Setup Assistant generates duplicated keys action_ns, default for the type FollowJointTrajectory, e.g.
```
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
controller_names:
- steering_controller
steering_controller:
type: FollowJointTrajectory
action_ns: follow_joint_trajectory
default: true
joints:
- front_left_steer_joint
- front_right_steer_joint
action_ns: follow_joint_trajectory
default: true
```
This PR deletes the redundant keys

Fix key duplication in moveit_setup_assistant for moveit_controllers.yaml for typeFollowJointTrajectory

---

moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp
moveit_planners/pilz_industrial_motion_planner/src/plan_components_builder.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_blender_transition_window.cpp

Found the issue!
Turns out that Pilz's `appendWithStrictTimeIncrease()` function had a single if-statement that encompassed two conditions:
1. If trajectory is empty
2. If the end state of one segment is not equal to the start state of the second segment
In both cases, the whole trajectory segment was appended with a `dt=0`.
The problem is that in case 1, it's appropriate to add a `dt=0` (as the trajectory is empty, the first point should be at `t=0`). In case 2, we needed to apply a non-zero sample time offset dictated by the actual `dt` of that trajectory's first waypoint.
Closes https://github.com/moveit/moveit2/issues/2945

Fix Pilz blending times... the right way

---

moveit_ros/moveit_servo/tests/launch/servo_cpp_integration.test.py
moveit_ros/moveit_servo/tests/launch/servo_ros_integration.test.py
moveit_ros/moveit_servo/tests/test_ros_integration.cpp

I just realized in analyzing servo integration tests that they were pulling from the `panda_simulated_config.yaml` (which currently uses the Acceleration filter plugin), but still had the old parameters from the Butterworth filter plugin in the launch files.
As a consequence, the smoothing plugin was not loading correctly in these tests; see, e.g., [this CI run](https://github.com/moveit/moveit2/actions/runs/10342130968/job/28624714548#step:11:4130).
This happens specifically because the Acceleration filter parameters *do not* have defaults, so they are required. Butterworth, on the other hand, has a default parameter value for its one coefficient.
@AndyZe FYI if you are switching the default in `panda_simulated_config.yaml` to the new Ruckig plugin in your PR, you will need to make …

Correctly load smoothing plugins in Servo integration tests

---

.github/workflows/ci.yaml

This is a workaround for a CI error that has been cropping up once in awhile recently:
>    Error while processing /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/moveit_servo/src/utils/common.cpp.
error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [clang-diagnostic-unknown-warning-option]
From https://github.com/moveit/moveit2/actions/runs/10335417126/job/28609933300 for one example
I don't think there's actually a potentially uninitialized variable there, at least not a new one in this PR. I think what happened is, `clang-tidy` was cached previously for this `cpp` file. That PR happened to touch that `cpp` file, which caused `clang-tidy` to re-run for it. And something about `clang-tidy` has changed since the last time …

Unknown compiler options for clang shouldn't be show-stoppers

---

moveit_ros/moveit_servo/demos/cpp_interface/demo_joint_jog.cpp
moveit_ros/moveit_servo/demos/cpp_interface/demo_pose.cpp
moveit_ros/moveit_servo/demos/cpp_interface/demo_twist.cpp
moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/servo_node.cpp

Previously we didn't wait to get a current robot state before servoing began. That caused the initial joint angles to be all-zero, which caused a small jump at the beginning of motion. This is a fix.
Test with:
`ros2 launch moveit_servo demo_ros_api.launch.py`
`ros2 run moveit_servo servo_keyboard_input`

Ensure the robot state is up-to-date before Servoing

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/config/test_config_panda.yaml
moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/include/moveit_servo/utils/common.hpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/utils/common.cpp

This PR allows the `joint_limit_margins` parameter of MoveIt Servo to be a single-element vector (and changes the defaults accordingly, so it works off-the-shelf with every robot).
It also fixes a not-yet-seen issue in which the joint halting logic would have failed if there were multi-DOF Joints. For those who were spammed by this PR, I was making sure this fix was correct, so please give it a look!
Closes https://github.com/moveit/moveit2/issues/2843.

[Servo] Support single-element joint limit margins vector and fix joint halting logic for multi-DOF Joints

---

moveit_ros/move_group/CMakeLists.txt
moveit_ros/move_group/default_capabilities_plugin_description.xml
moveit_ros/move_group/include/moveit/move_group/capability_names.h
moveit_ros/move_group/src/default_capabilities/load_geometry_from_file_service_capability.cpp
moveit_ros/move_group/src/default_capabilities/load_geometry_from_file_service_capability.h
moveit_ros/move_group/src/default_capabilities/save_geometry_to_file_service_capability.cpp
moveit_ros/move_group/src/default_capabilities/save_geometry_to_file_service_capability.h
moveit_ros/move_group/src/move_group.cpp

This PR adds services which can be used to save/load CollisionObjects  to/from files. This depends on https://github.com/moveit/moveit_msgs/pull/181.

Add `SaveGeometryToFile` and `LoadGeometryFromFile` services

---

moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.h

Fix failing CI
```
--- stderr: moveit_ros_perception
In file included from /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.h:42,
from /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp:38:
/opt/ros/rolling/include/message_filters/message_filters/subscriber.h:18:2: error: #warning This header is obsolete, please include message_filters/subscriber.hpp instead [-Werror=cpp]
18 | #warning This header is obsolete, please include message_filters/subscriber.hpp instead
|  ^~~~~~~
```
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard …

Replace obsolete header

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp

Backport to Humble: Pass more distance information out from FCL collision check #2572

---

.github/ISSUE_TEMPLATE/config.yml

Disables the blank issue button in GitHub issues to funnel issues through the provided templates. This is particularly useful to make sure people use the new bug report form that includes numerous mandatory fields for things like DDS implementation.

Disable blank issues on GitHub

---

moveit_core/robot_state/src/robot_state.cpp

Simplify function using `getFrameInfo()` to yield the link corresponding to the given frame.
The order of frame resolution was wrong here:
If a _link_ frame containing a _slash_ was given, the code was expecting an attached body with a subframe. As these didn't exist, the function falsely returned `NULL`.
@sjahr: Maybe this is the error you recently observed? Note, that the function was already fixed in MoveIt1.

Fix RobotState::getRigidlyConnectedParentLinkModel()

---

moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt

This exports an IKFast plugin library correctly. I got a strong hint from the comment here:
https://github.com/moveit/moveit2/issues/2144#issuecomment-1547967425

Export the IKFast library correctly

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml
moveit_ros/moveit_servo/config/servo_parameters.yaml
moveit_ros/moveit_servo/config/test_config_panda.yaml
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/utils/command.cpp
moveit_ros/moveit_servo/tests/launch/servo_cpp_integration.test.py
moveit_ros/moveit_servo/tests/test_integration.cpp
moveit_ros/moveit_servo/tests/test_ros_integration.cpp

This PR seeks to apply max linear/angular velocity scaling properly in the Cartesian and pose tracking commands. Specifically:
* Max linear/angular speeds were not being honored at all in Cartesian mode; they were just used for unitless command scaling
* **Important**: In pose tracking mode, even if a pose was far away, no efforts were made to limit the speed at that pose. The Cartesian delta was whatever joint angle difference was computed between the current state and target pose IK solution.
* Singularity scaling was only applied in Cartesian, but not Pose tracking mode (probably an oversight)

[Servo] Use velocity scaling properly in Cartesian and pose tracking commands

---

moveit_planners/moveit_planners/package.xml

By default, the packages generated by moveit_setup_assistant now include a chomp configuration - but do not depend on chomp. the packages do depend on moveit_planners, so it makes sense to include chomp here.

have moveit_planners depend on chomp

---

.github/workflows/ci.yaml
moveit_core/constraint_samplers/test/pr2_arm_ik.h
moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h
moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/data/urdf_config.hpp

The old header is marked obsolete.

Update urdf/model.h -> urdf/model.hpp

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

most of the other stuff was removed as part of #1177 - we can also now get rid of the support surface stuff which is unused. This code was noted in #3013

remove dead pick and place code

---

moveit_ros/planning/CMakeLists.txt

I think the plugin that are intended to be loaded by classloader or pluginlib should not be exported as the same exportset as the libraries that are intended to be dynamically linked. I ran into an issue where `libmoveit_ompl_planner_plugin.so` is being dynamically linked to `libmoveit_default_planning_response_adapter_plugins.so`, which breaks `MultiLibraryClassLoader`.

Remove plugins from export set

---

.github/workflows/ci.yaml
.github/workflows/format.yaml
.github/workflows/sonar.yaml
moveit2.repos

This should fix [current CI issues](https://github.com/moveit/moveit2/actions/runs/11313105568):
- [srdfdom not linking against tinyxml2](https://github.com/moveit/moveit2/pull/3020#issuecomment-2408993712)
- `save-always` option being deprecated in `actions/cache`

Fix CI issues

---

moveit_core/robot_state/src/cartesian_interpolator.cpp

This is a follow-up on #2916, fixing a bug reported in https://github.com/moveit/moveit/issues/3651.

Fix Cartesian interpolation

---

moveit_ros/moveit_servo/src/servo.cpp

If I use the moveit_servo servo_node in combination with Gazebo simulation, the `moveit_ros.current_state_monitor` complains that it doesn't receive robot state with recent timestamp. I launch all nodes with the 'use_sim_time' set to True, however the current_state_monitor still seems to use wall time. A similar problem was explained in this issue, although not for moveit_servo:
https://github.com/moveit/moveit2/issues/2906
My solution is to change the code from `rclcpp::Clock(RCL_ROS_TIME).now()` to `node_->now()`, such that the time is obtained from the node, which is launched with 'use_sim_time' set to True, so that it gives the sim time. This fixes my problem for the moveit_servo node, but will probably not fix the problem in the issue I mentioned.
This is my first contribution. I …

Obtain time from node.

---

moveit_setup_assistant/moveit_setup_framework/src/srdf_config.cpp

Cast of "max_velocity" and "max_acceleration" values to double (backport #2803)

---

moveit_configs_utils/moveit_configs_utils/launches.py

If you run the default generated configs for MoveIt on a headless system where `DISPLAY` isn't defined in the environment, this code crashes with a `KeyError`. Switch to use `dict.get(DISPLAY, "")` which returns `""` instead of
throwing.

Switch to get for Dict lookup to prevent KeyError

---

moveit_ros/planning/package.xml
moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning/planning_scene_monitor/test/launch/planning_scene_monitor.test.py
moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor_test.cpp

This is a backport of #2745 from `main` to `humble`. The original PR was a port from MoveIt1.

PSM: keep references to scene_ valid upon receiving full scenes

---

moveit_core/robot_model/include/moveit/robot_model/joint_model.h

I was reading a file and noticed the comments were backwards. Tiny change.

Fix flipped comments in `joint_model.h`

---

moveit_ros/moveit_servo/src/utils/command.cpp

When calculating jointDeltaFromPose after receiving a pose target for moveit servo, the `ee_pose` is not always on `planning_frame`.
This patch will ensure the `ee_pose` is based on right frame.

[moveit_servo] fix: ensure ee_pose on planning_frame

---

moveit_ros/moveit_servo/src/collision_monitor.cpp
moveit_ros/moveit_servo/tests/servo_cpp_fixture.hpp
moveit_ros/moveit_servo/tests/test_integration.cpp

I finally chased down the source of the flakiness of the servo integration tests in #3005... I think.
Turns out that the collision monitor thread gets the robot state with the following due to https://github.com/moveit/moveit2/pull/2747 / https://github.com/moveit/moveit2/issues/2748:
```cpp
robot_state_ = planning_scene_monitor_->getPlanningScene()->getCurrentState();
```
However, the Servo integration CPP tests were using
```cpp
/// Helper function to get the current pose of a specified frame.
Eigen::Isometry3d getCurrentPose(const std::string& target_frame) const
{
return planning_scene_monitor_->getStateMonitor()->getCurrentState()->getGlobalLinkTransform(target_frame);
}
```
Switching to the first implementation in the tests caused our "flake" to be a consistently reproducible …

Wait for nonzero joint states in PSM in Servo CPP integration test

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_base.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_functions.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_circ.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_lin.h
moveit_planners/pilz_industrial_motion_planner/src/trajectory_blender_transition_window.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_lin.cpp

Ports https://github.com/moveit/moveit/pull/3519 to ROS2. This may partially fix https://github.com/moveit/moveit2/issues/2857 for the LIN planner

Ports moveit/moveit/pull/3519 to ros2

---

moveit_ros/moveit_servo/tests/servo_cpp_fixture.hpp

Addresses https://github.com/moveit/moveit2/pull/3056#pullrequestreview-2412960165.

Cleanup #3056

---

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_core/kinematic_constraints/src/utils.cpp
moveit_core/kinematic_constraints/test/test_orientation_constraints.cpp
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp

This is a port of two fixes in MoveIt1 (see PR descriptions there for details):
- https://github.com/moveit/moveit/pull/3655
Partially reverts #2910.
- https://github.com/moveit/moveit/pull/3656
Interprets tolerance _vector_ w.r.t. given `frame_id`.

Port fixes for handling orientation constraints

---

moveit_ros/moveit_servo/include/moveit_servo/servo_node.hpp
moveit_ros/moveit_servo/src/servo_node.cpp

`pauseServo` and `servoLoop` are running in two different threads, we should use a mutex to avoid race condition.
here is a core dump sample of race condition, when `pauseServo` and `servoLoop` both calling `joint_cmd_rolling_window_.clear()`
```text
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Core was generated by `/packages/moveit_servo/lib/moveit_servo/servo_node --ros-args -r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffff9f32dbf4 in __GI___libc_free (mem=0xfff097f6d2fb) at ./malloc/malloc.c:3368
3368	./malloc/malloc.c: No such file or directory.
[Current thread is 1 (Thread 0xffff94aae8e0 (LWP 454))]
(gdb)
(gdb)
(gdb)
(gdb)
(gdb) bt
#0  0x0000ffff9f32dbf4 in __GI___libc_free …
```

[moveit_servo] avoid race condition when calling ~/pause_servo

---

moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

@marioprats and I encountered an error in the Jacobian calculation for a link that is not the tip link. In that case all joint in the chain after the reference link don't have any impact on it's motion and thus, the related Jacobian entries need to zero. This PR fixes that + adds a unittest to catch this in the future.

Fix jacobian calculation

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp

Fixes humble backport issues (#3070)

---

moveit2.repos

This change was formerly needed (and reverted on main), but not in the Humble branch.

Remove source build of generate_parameter_library on Humble

---

.github/workflows/tutorial_docker.yaml

These jobs have been failing as optional for a while, and the `main` branch of `moveit2` just will not work with these older tutorial versions. So I opt for removing them here.
If anything, the tutorial job should be added into the `humble` branch to test that specific pipeline -- doing in https://github.com/moveit/moveit2/pull/3082.

Remove Humble and Iron from tutorial Docker CI job

---

moveit_configs_utils/moveit_configs_utils/launches.py

Rviz now loads the moveit joint limits, enabling cartesian planning from rviz.
Addresses issue #2989 by having the rviz generator use the joint limits provided by the MoveItConfigsBuilder.
Currently, these joint limits are not added as parameters to rviz, which can break behavior such as cartesian path planning.

Added joint limits to rviz launch file.

---

moveit_core/robot_state/src/robot_state.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_functions.cpp

Fixes merge conflicts in the backport PR

Fixes merge conflicts (humble backport 3077)

---

.github/workflows/docker.yaml

Turns out the `moveit/moveit2:humble-***` images have not been pushed in 7 months.
https://hub.docker.com/r/moveit/moveit2/tags

[Humble] Use same Docker CI actions as main

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

This PR aims to resolve missing functionality from Moveit1 which allowed for attached collision objects to become transparent through the setting of an alpha value in `robot_state_visualization.cpp`. It also defaults the alpha value to match the Scene Robot Alpha value which was default behaviour for Moveit1.
If this could be backported to Humble it would be much appreciated

Attached Collision Object Transparency

---

moveit_core/robot_state/test/robot_state_test.cpp

Fixes #3103 by ensuring that the `dirty_link_transforms_` member is cleared before querying the `RobotState`
See #3102 for more details on the cause. 
TLDR: 
Setting the build type to Release causes tests to silently fail, whereas Debug does not (some tests rely on assert calls, which are enabled / disabled based on the presence of the `NDBUG` macro variable, which is set by CMake depending on the build type). 
See the SonarScan pipeline call to ros-industrial/industrial_ci@master, which sets DCMAKE_BUILD_TYPE to Debug (and where the tests fail), and the same call in the rolling-ci pipeline (where the tests pass), which sets the same variable to Release.
I've also added a comment (and demonstration of the fix, at least for this test) locally.
[//]: # "You can expect a response from a …

Fixes flaky RobotState test

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml

Missed a few more in https://github.com/moveit/moveit2/pull/3101... this is hard to do from a phone.
Also generally brought in all the relevant CI changes from `main`, for parity.
NOTE: This may fail until merged because this will finally upload the `humble-ci` image to Docker Hub. Took me forever to figure this out.

[Humble] Replace more ros-planning with moveit2

---

.docker/ci/Dockerfile
.github/workflows/ci.yaml
moveit2_humble.repos
moveit2_iron.repos

The only dependency that was in these files was an old version of `generate_parameter_library` which we do not need to be on at the moment.
I still kept the logic in the Dockerfiles in case there ever needs to be distro-specific repos files in future.

Remove moveit2_humble.repos and moveit2_iron.repos files

---

MIGRATION.md
moveit_core/CHANGELOG.rst
moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_py/src/moveit/moveit_core/planning_scene/planning_scene.cpp
moveit_ros/benchmarks/src/BenchmarkExecutor.cpp
moveit_ros/planning/plan_execution/src/plan_execution.cpp

I wanted to perform a padded self-collision check with a robot state and realized that this is not possible with the current API. So I decided to enable it + clean-up the checkCollision API of the planning scene a bit. This PR:
- Adds use_padded_collision_environment & use_padded_self_collision flags to choose the environment to be used for collision checks
- Clean up & update checkCollision(): Move all implementations into header make transform update more consistent
- Deprecate checkCollisionUnpadded() since they become redundant with the new flags
- Clean up & update checkSelfCollision(): Move all implementations into header make transform update more consistent
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping …

Add use_padding flag + deprecate checkCollisionUnpadded() functions

---

.github/workflows/ci.yaml
.github/workflows/sonar.yaml

Attempt to fix #3110 and #2866.

CI: Silent lcov errors

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Accepts all incoming changes.

---

moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp

Replaced `ReentrantCallbackGroup` with `MutuallyExclusiveCallbackGroup` in `MoveGroupSequenceAction::initialize` to prevent race conditions during stress testing.
This change ensures sequential execution of callbacks, avoiding issues caused by concurrent execution.
Reference: https://github.com/moveit/moveit2/issues/3117

Fix: Resolve race condition in MoveGroupSequenceAction

---

moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor_test.cpp

This is the Humble version of https://github.com/moveit/moveit2/pull/3124, in which the test was never disabled and continued to be flaky.
See my log of successful retries: https://github.com/moveit/moveit2/actions/runs/11966024737?pr=3126

[Humble] Add sleep in setup of flaky PSM test fixture

---

moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/test/launch/planning_scene_monitor.test.py
moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor_test.cpp

Re-enables a flaky Planning Scene Monitor test, adding a wait between the thread being started in the `SetUp()` to avoid race conditions I could reproduce locally.
Terminal 1:
```
stress -c 16 --vm 20 --vm-bytes 256M --timeout 10000 
```
Terminal 2:
```
ros2 test /home/sebastian/workspace/moveit_ws/src/moveit2/moveit_ros/planning/planning_scene_monitor/test/launch/planning_scene_monitor.test.py test_binary_dir:=/home/sebastian/workspace/moveit_ws/build/moveit_ros_planning/planning_scene_monitor
```
See log of retries being tracked here: https://github.com/moveit/moveit2/actions/runs/11966295919/job/33361693036?pr=3124 -- humble CI failing for other reasons on main as of the last few days.
Mitigates (but does not close) https://github.com/moveit/moveit2/issues/2821
[//]: # "You can expect …

Re-enable flaky PSM test

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
.github/workflows/tutorial_docker.yaml

This is a complementary PR to https://github.com/moveit/moveit2/pull/3141.
Jazzy Docker and tutorial images will now be built off the `jazzy` branch.

Do not perform most Jazzy CI jobs on main branch

---

moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt
moveit_ros/planning/planning_request_adapter_plugins/res/default_request_adapter_params.yaml
moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp
moveit_ros/planning/planning_request_adapter_plugins/test/test_check_start_state_bounds.cpp

This PR aims to fix the logic in the `CheckStartStateBounds` adapter, as @chama1176 pointed out.
It also adds some basic unit tests to prevent further breakages and maintain expected behavior.
Closes #2924

Fix logic in CheckStartStateBounds adapter

---

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.hpp
moveit_core/robot_model/src/joint_model_group.cpp

The RevoluteJointModel returns -pi/pi as position joint limits for continuous joints, which are not position bounded.
This PR fixes `getLowerAndUpperLimits` to check the `position_bounded_` flag and return joint limits accordingly.

handle continuous joints in getLowerAndUpperLimits

---

README.md

Updates the codecov badge to use the new `moveit` org, as it still pointed to `ros-planning`.

Fix URL to coverage badge

---

.github/workflows/ci.yaml

I think we should be able to do this now

re-enable cmake warnings (#3028)

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

When removing collision objects from a planning scene, we need to also remove their corresponding entries from the allowed collision matrix. Previously, these entries would remain in the ACM even after the object was removed, which could cause inconsistencies if an object with the same name was added later.

Remove ACM entries when removing collision objects

---

moveit_setup_assistant/moveit_setup_framework/templates/CMakeLists.txt

This pull request addresses issue #3189 where the `CMakeLists.txt` file always attempts to install the `launch` directory, even if it does not exist. This can cause the installation process to fail when no launch files are created in the setup assistant.
1. **CMakeLists.txt**:
- Added a condition to check if the `launch` directory exists before attempting to install it. This ensures that the installation process does not fail when the `launch` directory is not present.
```cmake
// filepath: /ros2_humble/src/moveit2/moveit_setup_assistant/moveit_setup_framework/templates/CMakeLists.txt
// ...existing code...
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/launch")
install(
DIRECTORY launch
DESTINATION share/${PROJECT_NAME}
PATTERN "setup_assistant.launch" EXCLUDE)
endif()
// ...existing code...

Fix: Conditionally install launch directory in generated MoveIt config package

---

.docker/tutorial-source/Dockerfile

Seems like  Rolling has now shifted to using Gazebo Ionic... seeing if this fixes the build. (EDIT: it does.)

Use Gazebo Ionic in tutorial images

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Fixes issue #3174.
When motion planning and executing solutions with MTC I have stages where objects are attached/removed and deleted from the scene at the beginning or end of a task. I have been having issues with the planning scene not updating correctly and the final state of the robot in the planning scene having offsets compared to the final state of trajectory given.
When executing an MTC solution that contains changes to the planning scene they are sent to the `planning_scene_monitor_` with [no robot_state information](https://github.com/moveit/moveit_task_constructor/blob/master/capabilities/src/execute_task_solution_capability.cpp#L173-L176). When MoveIt receives this `newPlanningSceneMessage` that is not marked as a scene_diff (because things are being added or removed from the …

Fix planning_scene_monitor sync when passed empty robot state

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Updates changes applied in #3187 to match the [back port to MoveIt1](https://github.com/moveit/moveit/pull/3683).

Simplify scene update that does not include new robot_state

---

moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.hpp
moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

MutuallyExclusive callbackgroup has been added to `point_cloud_subscriber_` to allow updating octomap during robot motion. See https://github.com/moveit/moveit2/issues/2192
---
-  I was not able to do the same fix to the `depth_image_octomap_updater` since `image_transport::create_camera_subscription` seems to not allow passing `SubscriptionOptions`.
- I noticed that there is a big computational time mismatch between the two approaches (depth/pointcloud). After digging in a bit i found that the main computational time difference comes from `lazy_free_space_updater` but unfortunately I have not time to fix it. I will use the pointcloud instead._

fix: OctoMap and Filtered_Cloud Not Updating During Movement Execution

---

moveit_core/distance_field/include/moveit/distance_field/distance_field.hpp
moveit_core/distance_field/src/distance_field.cpp
moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.hpp
moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.hpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

This PR adds const specifiers to methods of some classes in moveit_core subdir as proposed in https://github.com/moveit/moveit2/issues/879. 

[Issue-879] Add const specifier to moveit_core

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp
moveit_ros/planning/plan_execution/src/plan_execution.cpp

When an object is added to the scene and immediately attached to the gripper it gets marked as [collision_detection::World::DESTROY](https://github.com/moveit/moveit2/blob/main/moveit_core/planning_scene/src/planning_scene.cpp#L372) in the `world_diff_`. When this happens the [ACM is modified](https://github.com/moveit/moveit2/blob/main/moveit_core/planning_scene/src/planning_scene.cpp#L377) and the attached object is not allowed to touch anything. 99% of the time this does not cause issues when executing a trajectory because the [scene diff](https://github.com/moveit/moveit2/blob/main/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L502) is not applied until after the trajectory starts, but is still updating the ACM incorrectly. Sometimes the scene diff is …

Don't destroy objects on attach

---

moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
moveit_planners/pilz_industrial_motion_planner/include/joint_limits_copy/joint_limits_rosparam.hpp

While compiling this package on Windows (see https://github.com/RoboStack/ros-humble/pull/241), the Windows compilation was failing as depending on the compilation options `not` may not be supported in MSVC depending on the compilation options. 
Anyhow, as everywhere else in the code `!` is used, I think it make sense to be consistent and use `!` also here.

Use ! in place of not keyword for Pilz and CHOMP planners

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp

I was compiling pilz_industrial_motion_planner on Windows, and I was obtaining a strange template error:
~~~
D:/src/testpilz/ros-humble/output/bld/rattler-build_ros-humble-pilz-industrial-motion-planner_1736462231/h_env/Library/include/tf2\tf2/impl/convert.hpp(60,1): error C2668
: 'tf2::fromMsg': ambiguous call to overloaded function [C:\Users\straversaro\build\trajectory_generation_common.vcxproj]
~~~
<details>
<summary> 
Click to see the rest of the error.
</summary>
~~~
D:/src/testpilz/ros-humble/output/bld/rattler-build_ros-humble-pilz-industrial-motion-planner_1736462231/h_env/Library/include/tf2\tf2/impl/convert.hpp(60,1): error C2668
: 'tf2::fromMsg': ambiguous call to overloaded function [C:\Users\straversaro\build\trajectory_generation_common.vcxproj] …

pilz_industrial_motion_planner: Use tf2::fromMsg instead of tf2::convert

---

moveit_planners/moveit_planners/package.xml

moveit_planners_chomp depends on chomp_motion_planner - both are needed - I missed that in #3015 

fix chomp depend, closes #3228

---

moveit_py/src/moveit/moveit_ros/trajectory_execution_manager/trajectory_execution_manager.cpp
moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
moveit_ros/planning/plan_execution/src/plan_execution.cpp
moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.hpp

previously discussed here https://github.com/moveit/moveit2/pull/3198#issuecomment-2577368278

move TrajectoryExecutionManager::clear() to private

---

moveit_setup_assistant/moveit_setup_assistant/src/collisions_updater.cpp
moveit_setup_assistant/moveit_setup_assistant/src/setup_assistant_widget.cpp
moveit_setup_assistant/moveit_setup_core_plugins/include/moveit_setup_core_plugins/configuration_files.hpp
moveit_setup_assistant/moveit_setup_core_plugins/src/configuration_files_widget.cpp
moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen.cpp
moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen_widget.cpp
moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/data/srdf_config.hpp
moveit_setup_assistant/moveit_setup_framework/src/srdf_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/urdf_config.cpp
moveit_setup_assistant/moveit_setup_framework/src/utilities.cpp

On Linux and macOS `std::filesystem::path` is implicitly convertible to `std::string`, while on Windows it is convertible to `std::wstring`, see https://en.cppreference.com/w/cpp/filesystem/path and https://stackoverflow.com/questions/57377349/implicit-conversion-between-stdfilesystempath-and-stdstring-should-it-hap . If we want to convert `std::filesystem::path` to `std::string` in a Windows-compatible way, it is then necessary to explicitly call the `.string()` method.
Fix part of https://github.com/moveit/moveit2/issues/2391 .

Explicit convert from std::filesystem::path to std::string for Windows compatibility

---

moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/acceleration_filter.hpp
moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.hpp
moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/ruckig_filter.hpp
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.hpp
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.hpp
moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.hpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/command_list_manager.hpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/limits_container.hpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.hpp
moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp
moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_common.cpp
moveit_planners/stomp/include/stomp_moveit/stomp_moveit_planning_context.hpp
moveit_planners/stomp/src/stomp_moveit_planning_context.cpp
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
moveit_ros/moveit_servo/include/moveit_servo/collision_monitor.hpp
moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
moveit_ros/moveit_servo/include/moveit_servo/utils/common.hpp
moveit_ros/planning/kinematics_plugin_loader/include/moveit/kinematics_plugin_loader/kinematics_plugin_loader.hpp
moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.hpp
moveit_ros/planning/planning_request_adapter_plugins/src/check_for_stacked_constraints.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_collision.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/validate_workspace_bounds.cpp
moveit_ros/planning/planning_response_adapter_plugins/src/add_time_optimal_parameterization.cpp
moveit_ros/planning/planning_response_adapter_plugins/src/display_motion_path.cpp
moveit_ros/planning/planning_response_adapter_plugins/src/validate_path.cpp

Now that `generate_parameter_library` changed the default install location of headers, this PR gets rid of deprecation warnings.

Update includes for generate_parameter_library 0.4.0

---

moveit_ros/moveit_servo/src/servo_node.cpp

Fixes occasional main thread starvation caused by repeatedly creating a lock_guard in the servo loop. One side effect would be that the pause_servo service would not respond. Fairness is improved by removing the thread sleep rate from the lock scope.

Reduce mutex scope in Servo thread

---

moveit_core/robot_state/src/robot_state.cpp

misleading log message for  RobotState::setFromIKSubgroups() when checking consistency_limits size
before:
fixed:

Fix: misleading error logs in RobotState::setFromIKSubgroups()

---

moveit_core/collision_detection/CMakeLists.txt
moveit_core/distance_field/CMakeLists.txt
moveit_core/robot_model/CMakeLists.txt
moveit_core/robot_state/CMakeLists.txt

I was doing a "build on potato computer" build of MoveIt 2 with `-j 4` and `--executor sequential`, and found myself with some errors related to missing `eigen_stl_containers` headers.
Turns out there has been a missing target dependency in these targets that use the library? Not sure how others haven't run into this, or whether some upstream dependency recently removed this transitively?

Add missing target dependencies to eigen_stl_containers

---

moveit_ros/hybrid_planning/global_planner/global_planner_component/src/global_planner_component.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp

Based on https://github.com/moveit/moveit2/actions/runs/13114230759/job/36584600940, it seems like clang-tidy is not happy. Why it wasn't before is confusing, but 🤷🏻 
Weirdly enough, most of these changes were backported in https://github.com/moveit/moveit2/pull/1704, but seems these 2 specific lines were not part of that PR by accident...

[humble] Fix clang-tidy warnings in hybrid planning package

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

It looks like [this](https://github.com/moveit/moveit2/pull/785) PR might have broken the chained controller management logic. 
Previously, `claimed_interfaces` were being used to determine which joints each controller was associated with, but now `required_command_interfaces` is used. That seems reasonable, but it was not updated everywhere. Specifically, there is some logic to handle ros2_control's chained controllers that was not updated. This PR fixes that issue.

Fix Ros2ControlManager chained controller logic

---

moveit_ros/moveit_servo/include/moveit_servo/servo.hpp

I was debugging something related to https://github.com/moveit/moveit2/pull/3251 and noticed that the docstring for `Servo::smoothHalt()` was slightly out of date in explaining its return type.
Super small change.

Fix docstring for Servo smoothHalt function

---

moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.hpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.hpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

- As https://github.com/moveit/moveit2/pull/3247 but with history preserved properly.
- Please back-port to Humble and Jazzy when merged

Ports moveit #3676 and #3682

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.hpp
moveit_core/robot_model/src/robot_model.cpp
moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/include/moveit/robot_state/attached_body.hpp
moveit_core/robot_state/include/moveit/robot_state/robot_state.hpp
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp
moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/planning_interface/test/subframes_test.cpp

- Fixes #3279 
- As https://github.com/moveit/moveit2/pull/3280, but with history correctly preserved. (Also includes a few commits in the same PRs, which #3280 missed)
- N.B. does not include changes to `cartesian_path_service_capability`, as that has changed significantly since the Moveit1 PRs were made.
- Please back-port to Humble and Jazzy when merged

Reverts #2985, Ports moveit #3388 #3470 #3539

---

moveit_ros/planning/rdf_loader/src/synchronized_string_parameter.cpp

Add namespace to the topic to read `robot_description`
- [ / ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ / ] Include a screenshot if changing a GUI

load robot_description from other namespace

---

moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.hpp
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
moveit_ros/planning/trajectory_execution_manager/test/test_execution_manager.cpp

Allow to specify a per joint allowed start tolerance for the TrajectoryExecutionManager. Port from https://github.com/moveit/moveit/pull/3287 with some changes to be able to dynamically update its values at runtime.
In `moveit_controllers.yaml`:
```yaml
trajectory_execution:
allowed_execution_duration_scaling: 1.2
allowed_goal_duration_margin: 0.5
allowed_start_tolerance: 0.01
allowed_start_tolerance_joints: {panda_joint3: 0.02, panda_joint5: 0.03, panda_finger_joint1: 0.005}
```
Joints that are not declared in `allowed_start_tolerance_joints` will use `allowed_start_tolerance` as the default.
- ~~I would personally have named this parameter "allowed_start_tolerance_joints" to be next to "allowed_start_tolerance" when sorted alphabetically. However, to maintain continuity with the …

Add allowed_start_tolerance_joints parameter (Port moveit#3287)

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Re-enabling the functionality to set `allowed_execution_duration_scaling` and `allowed_goal_duration_margin` for each controller, which has been commented out since moveit2 was created.
In `moveit_controllers.yaml`:
```
trajectory_execution:
allowed_execution_duration_scaling: 1.2 # Default global value for all controllers
allowed_goal_duration_margin: 0.5 # Default global value for all controllers
...
moveit_simple_controller_manager:
controller_names:
- panda_arm_controller
panda_arm_controller:
type: FollowJointTrajectory
allowed_execution_duration_scaling: 5.0 # Overrides the global value for this controller
allowed_goal_duration_margin: 1.0 # Overrides the global value for this controller
...
```
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard …

Enable allowed_execution_duration_scaling and allowed_goal_duration_margin for each controller

---

moveit_ros/moveit_servo/src/servo_node.cpp

Servo was not updating the current robot state when it was paused. This can result in massive jumps when servo is paused and the robot is moved with another mechanism, then servo is reactivated.

Update current state even if servo is paused

---

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

The motion planning plugin in RViz does not respect the alpha values for attached bodies when visualizing the trail of the planned path. The alpha values of the trail are only updated if the attached body color is changed at a later point. 
Updating the attached body color upon creation of the trail fixes this problem. The same thing applies to drawing the robot along the planned path which is handeled in the update function.

Respect robot alpha value in trail trajectory visual

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

When launching the `move_group` node with a namespace and running `moveit_py` within a node that has the same namespace, the `moveit_simple_controller_manager` lacked a namespace. As a result, the robot could not operate because the action for trajectory execution was missing the necessary namespace.  
Explicitly added the parent node's namespace.

fix: explicitly add the same namespace as the parent node

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp

Previously, the topics started by MoveItPy could not be remapped.
To address this, I added an argument for remapping, allowing remapping to be handled within Python scripts.
Ideally, I wanted MoveItPy to support remapping via the remappings option specified in the launch file. However, due to the design philosophy of rclpy, this seems difficult. As a compromise, I have ensured that remapping can at least be performed via an argument.

feat: add remapping argument to MoveItPy initialization

---

.github/workflows/ci.yaml

Same issue as described in https://github.com/actions/upload-artifact/issues/478

Overwrite test artifacts if written multiple times

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

For some reason, maybe over loaded network or CPU, listing the ros2 controllers of my robot is quite slow, a bit more than 1.0 second in average:
```bash
$ time ros2 control list_controllers
arm_controller          joint_trajectory_controller/JointTrajectoryController         active  
[...]
real    0m1.349s
user    0m0.658s
sys     0m0.144s
```
In consequence, the MoveIt ROS interface fails at executing the trajectory while the controller is actually ready to work.
I propose to increase the 1.0 second timeout to 10.0 seconds because 1.0 is really harsh, especially on slow computers.
Maybe a lower timeout would be more acceptable, as you prefer.

SERVICE_CALL_TIMEOUT = 1 second is harsh 🥵

---

moveit_planners/stomp/test/CMakeLists.txt

Fix missing linkage in `moveit_planners_stomp` tests via `target_link_libraries` declaration as suggested in https://github.com/moveit/moveit2/issues/3436#issuecomment-2801840569
Fixes https://github.com/moveit/moveit2/issues/3436

Add `stomp` target link to `moveit_planners_stomp` tests

---

moveit_setup_assistant/moveit_setup_controllers/package.xml
moveit_setup_assistant/moveit_setup_core_plugins/package.xml
moveit_setup_assistant/moveit_setup_framework/package.xml
moveit_setup_assistant/moveit_setup_simulation/package.xml
moveit_setup_assistant/moveit_setup_srdf_plugins/package.xml

Something changed in rolling apparently, so buildfarm is not happy.
Closes #3440 

Use ament_cmake_ros build tool in moveit_setup_assistant packages

---

moveit_setup_assistant/moveit_setup_app_plugins/package.xml

Shoot, missed one in #3441. Buildfarm still unhappy.
As I've said before, attention to detail is not my strength.

Fix one more buildtool_depend tag in moveit_setup_app_plugins

---

moveit_core/robot_state/src/robot_state.cpp
moveit_ros/planning/plan_execution/src/plan_execution.cpp

#3327 introduced a bug where motion execution can segfault by attempting to indexing into arrays of zero length.
```
[move_group-5] [INFO moveit_task_constructor_visualization.execute_task_solution 1746211985.025712029]: Executing TaskSolution
[move_group-5] [INFO move_group.moveit.moveit.plugins.simple_controller_manager 1746211985.025804455]: Returned 1 controllers in list
[move_group-5] [INFO move_group.moveit.moveit.ros.trajectory_execution_manager 1746211985.025904844]: Validating trajectory with allowed_start_tolerance 0.01
[move_group-5] [INFO move_group.moveit.moveit.ros.trajectory_execution_manager 1746211985.026685553]: Starting trajectory execution ...
[move_group-5] Stack trace (most recent call last) in thread 3045:
[move_group-5] #10   Object "", at 0xffffffffffffffff, in …
```

Fix seg fault with attached objects during motion execution

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.hpp

While compiling this package on Windows (see https://github.com/RoboStack/ros-humble/pull/241 for a similar issue), the Windows compilation was failing as depending on the compilation options `and` may not be supported in MSVC.
Anyhow, as everywhere else in the code `&&` is used, I think it make sense to be consistent and use `&&` also here.
Similar to https://github.com/moveit/moveit2/pull/3217 .

Use && in place of and keyword in action_based_controller_handle.hpp

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/background_processing.cpp

Since std::scoped_lock is used in the implementations, [the header defining this ](https://en.cppreference.com/w/cpp/header/mutex.html)should be included.
Otherwise this can lead to build errors such as in https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/runs/16434641652/job/46442308076#step:6:9912
Could also reproduce this when building moveit2 locally. Adding the changes from this PR fixed it.

Include mutex header for usage of scoped_lock

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/interactive_marker_display.cpp

MoveIt's iMarker doesn't initialize the marker namespace property, so that functionality is broken when you try to add other iMarkers alongside moveit's planning interface. Normally this just breaks the cursor, though in some cases we've seen rviz crash. I was under the impression that pluginlib might still load the default plugin for other markers, but that does not seem to be the case.
Regardless, I don't think there's a downside to providing the node abstraction to the namespace property object, so this PR just uncomments those lines.
Before (cursor gets stuck as a spinning wheel):
https://github.com/user-attachments/assets/753dc0bd-289f-47e4-8046-f22c667d8b5a
After:
https://github.com/user-attachments/assets/ccfcdb4d-5c47-47d4-a2e8-3f311f365d39
[//]: # "You can expect a response from …

Initialize the namespace property for custom iMarkers in rviz
