moveit/moveit2

moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp
moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.h
moveit_ros/manipulation/pick_place/include/moveit/pick_place/pick_place.h
moveit_ros/manipulation/pick_place/src/pick.cpp
moveit_ros/manipulation/pick_place/src/place.cpp
moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.h
moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp
moveit_ros/move_group/src/default_capabilities/move_action_capability.h
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/demo.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

I believe this is the correct approach to actions, and I tried to document it: https://github.com/ros2/ros2_documentation/pull/130

Port moveit_msgs actions

---

.docker/ci/Dockerfile
.travis.yml
moveit.rosinstall

This pr attempts to make the necessary changes to get the master branch to pass travis. 
It depends on #56 and #46 

Configure Travis

---

moveit.rosinstall

Fixing the moveit branch in the rosinstall

fixing rosinstall branch

---

moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_common_distance_field.h
moveit_core/collision_distance_field/src/collision_common_distance_field.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

Follows from https://github.com/ros-planning/moveit2/pull/36

Fixes to melodic-sync, adapt to ROS2 style

---

README.md

Clarifying 'Roadmap' as mentioned in several backlinks

---

.travis.yml

In response to @henningkayser 's comment  https://github.com/ros-planning/moveit2/pull/57#discussion_r270930595

Clarify why Travis uses Trusty

---

README.md

Content in the readme is not updated. Review of PRs is taking too long. Point users to the fork for now.

README, note that changes are being reviewed and point users to fork

---

moveit_core/kinematics_base/CMakeLists.txt
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/kinematics_base/src/kinematics_base.cpp

- Fixing logger variable 
- Library as shared
- porting lookupParam function but it still need more work

Kinematics base port to ROS 2

---

moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp

Addresing the following https://github.com/ros-planning/moveit2/pull/60#discussion_r297408923

Fix pr2_arm_kinematics_plugin test

---

.docker/README.md
.docker/ci/Dockerfile
.docker/release/Dockerfile
.docker/source/Dockerfile
.travis.yml
moveit2.repos

Update ROS 2 versions in Docker/CI to dashing.

Switch ROS 2 version from crystal to dashing

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/package.xml
moveit_ros/planning/rdf_loader/CMakeLists.txt
moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h
moveit_ros/planning/rdf_loader/src/rdf_loader.cpp

This is a continuation of [PR#76](https://github.com/ros-planning/moveit2/pull/76)
The addressed review was added to the master branch [see](https://github.com/AcutronicRobotics/moveit2/commits/master/moveit_ros/planning/rdf_loader) but because I'm not able to cherry-pick the changes for the specific files of rdf_loader, I just applied the changes to the rdf_loader and committed them

Port rdf_loader to ROS2 

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/robot_model_loader/CMakeLists.txt
moveit_ros/planning/robot_model_loader/include/moveit/robot_model_loader/robot_model_loader.h
moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

I didn't apply this [commit](https://github.com/AcutronicRobotics/moveit2/commit/fdaa83a6a5b02ad32ec84c7466f4da352ee89fac#diff-468186bdf99c33116a2d2ece4e3398c3) nor the changes to CMakeLists.txt from this [commit](https://github.com/AcutronicRobotics/moveit2/commit/5d645ee2e4c47fb4c5063b86482dba8909a40f0f#diff-468186bdf99c33116a2d2ece4e3398c3)
This PR depends on [PR#104](https://github.com/ros-planning/moveit2/pull/104) and [PR#107](https://github.com/ros-planning/moveit2/pull/107).

Port robot_model_loader to ROS2

---

README.md

Fix file URL in README

---

README.md

Update migration progress document URL

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/collision_plugin_loader/CMakeLists.txt
moveit_ros/planning/collision_plugin_loader/include/moveit/collision_plugin_loader/collision_plugin_loader.h
moveit_ros/planning/collision_plugin_loader/src/collision_plugin_loader.cpp

Fixup and reopen of  https://github.com/ros-planning/moveit2/pull/69

Port collision_plugin_loader to ROS 2

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/kdl_kinematics_plugin/CMakeLists.txt
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_mimic_svd.hpp
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h
moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_mimic_svd.cpp
moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp
moveit_kinematics/kdl_kinematics_plugin_description.xml
moveit_kinematics/lma_kinematics_plugin/CMakeLists.txt
moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/lma_kinematics_plugin.h
moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp
moveit_kinematics/lma_kinematics_plugin_description.xml
moveit_kinematics/package.xml
moveit_kinematics/srv_kinematics_plugin/CMakeLists.txt
moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.h
moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp
moveit_kinematics/srv_kinematics_plugin_description.xml
moveit_kinematics/test/CMakeLists.txt
moveit_kinematics/test/benchmark_ik.cpp
moveit_kinematics/test/test_kinematics_plugin.cpp

Port moveit kinematics to ROS2

---

moveit_ros/planning/CMakeLists.txt
moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.h
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

This enables the planning_pipeline and fixes remaining migration steps.

Fix and compile planning_pipeline

---

moveit2.repos

https://github.com/OctoMap/octomap_msgs/pull/13 was merged

Install octomap_msgs from upstream repo

---

moveit_core/CMakeLists.txt
moveit_core/package.xml
moveit_core/robot_model/CMakeLists.txt

Fixes #151 using https://github.com/ros2/eigen3_cmake_module

Fix Eigen3 linking issue in moveit_core

---

README.md

Launch day testing and tweaking for readability.

Simplify MoveIt 2 readme

---

README.md

Follow up from https://github.com/ros-planning/moveit2/pull/171
per @JafarAbdi

Shortcut to release versions in README

---

README.md

I thought it's more convenient to use HTTPS than SSH here.

Updated SSH link to HTTPS

---

moveit_core/CHANGELOG.rst
moveit_core/package.xml
moveit_demo_nodes/run_moveit_cpp/CHANGELOG.rst
moveit_demo_nodes/run_moveit_cpp/package.xml
moveit_kinematics/CHANGELOG.rst
moveit_kinematics/package.xml
moveit_planners/ompl/CHANGELOG.rst
moveit_planners/ompl/package.xml
moveit_plugins/moveit_simple_controller_manager/CHANGELOG.rst
moveit_plugins/moveit_simple_controller_manager/package.xml
moveit_ros/occupancy_map_monitor/CHANGELOG.rst
moveit_ros/occupancy_map_monitor/package.xml
moveit_ros/planning/CHANGELOG.rst
moveit_ros/planning/package.xml
moveit_ros/planning_interface/CHANGELOG.rst
moveit_ros/planning_interface/package.xml
moveit_ros/visualization/CHANGELOG.rst
moveit_ros/visualization/package.xml

Update version to 2.0.0

---

moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.rviz
moveit_demo_nodes/run_moveit_cpp/src/run_moveit_cpp.cpp
moveit_ros/visualization/CMakeLists.txt
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
moveit_ros/visualization/trajectory_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/trajectory_rviz_plugin/include/moveit/trajectory_rviz_plugin/trajectory_display.h
moveit_ros/visualization/trajectory_rviz_plugin/src/plugin_init.cpp
moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp
moveit_ros/visualization/trajectory_rviz_plugin_description.xml

This PR intends to port the `moveit_ros_visualization/trajectory_rviz_plugin` to ROS2. The dependencies were ported previously in PR #160.

Port trajectory_rviz_plugin

---

moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt
moveit_plugins/moveit_fake_controller_manager/moveit_fake_controller_manager_plugin_description.xml
moveit_plugins/moveit_fake_controller_manager/package.xml
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.cpp
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.h

Port moveit_fake_controller_manager to ROS2
The remaining warning is from srdfdom, wont fix

[Ready] Port moveit_fake_controller_manager to ROS2

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp

Contains changes made to simple_controller_manager, pulled from PR #187 . ~~Still a work in progress.~~ Expect more sub-PRs from PR#187.
~~Edit: Seems that there was a rebase of master, how should i fix this so the history/changes gets cleaned up?~~
Done! Contains mostly replacements to spin_until_future_complete so that PR#187 can work

[Ready] simple_controller_manager fixes from PR #187, remove spin_until_future_complete

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin-inl.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/GreedyKCenters.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighbors.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighborsGNAT.h
moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp
moveit_kinematics/cached_ik_kinematics_plugin_description.xml
moveit_kinematics/package.xml
moveit_kinematics/test/CMakeLists.txt
moveit_kinematics/test/benchmark_ik.cpp

Port CachedIKKinematicsPlugin to ROS2

---

moveit_ros/benchmarks/CMakeLists.txt
moveit_ros/benchmarks/package.xml

Fixes: https://github.com/ros-planning/moveit2/issues/239

Fix depend for boost date-time

---

moveit_demo_nodes/run_moveit_cpp/README.md
moveit_demo_nodes/run_moveit_cpp/config/controllers.yaml
moveit_demo_nodes/run_moveit_cpp/config/fake_controllers.yaml
moveit_demo_nodes/run_moveit_cpp/config/panda_controllers.yaml
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.rviz
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp_fake_controller.launch.py
moveit_demo_nodes/run_moveit_cpp/run_moveit_cpp.repos
moveit_demo_nodes/run_moveit_cpp/src/run_moveit_cpp.cpp
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp

Use MoveIt fake controller for the demo

---

.docker/ci-testing/Dockerfile
.docker/ci/Dockerfile
.docker/source/Dockerfile

Fix docker for Eloquent branch

---

.travis.yml
moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_pr2.h
moveit_core/collision_distance_field/CMakeLists.txt
moveit_core/collision_distance_field/test/test_collision_distance_field.cpp
moveit_core/constraint_samplers/CMakeLists.txt
moveit_core/package.xml
moveit_core/planning_scene/CMakeLists.txt
moveit_core/planning_scene/test/test_planning_scene.cpp
moveit_core/robot_model/CMakeLists.txt
moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/test/test_aabb.cpp
moveit_core/robot_state/test/test_cartesian_interpolator.cpp
moveit_core/robot_state/test/test_kinematic_complex.cpp
moveit_core/robot_trajectory/CMakeLists.txt
moveit_core/trajectory_processing/CMakeLists.txt
moveit_core/utils/CMakeLists.txt
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py
moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp_fake_controller.launch.py
moveit_demo_nodes/run_moveit_cpp/run_moveit_cpp.repos
moveit_demo_nodes/run_moveit_cpp/src/run_moveit_cpp.cpp
moveit_planners/ompl/ompl_interface/CMakeLists.txt
moveit_planners/ompl/ompl_interface/test/test_state_space.cpp
moveit_planners/ompl/package.xml
moveit_ros/planning/constraint_sampler_manager_loader/CMakeLists.txt
moveit_ros/planning/kinematics_plugin_loader/CMakeLists.txt
moveit_ros/planning/package.xml
moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt

See https://github.com/ros-planning/moveit_resources/pull/41, we should also sync this PR https://github.com/ros-planning/moveit/pull/2199

Update demo launch files to use the new moveit_resources layout

---

moveit_ros/moveit_servo/test/servo_launch_test_common.hpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Here are a couple of issues I found by building with thread sanitizer and running the servo tests.

[fix] threading issues in PSM and servo

---

moveit_ros/robot_interaction/CMakeLists.txt
moveit_ros/robot_interaction/include/moveit/robot_interaction/interaction.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/interaction_handler.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/interactive_marker_helpers.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/kinematic_options.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/kinematic_options_map.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/robot_interaction.h
moveit_ros/robot_interaction/package.xml
moveit_ros/robot_interaction/src/interaction_handler.cpp
moveit_ros/robot_interaction/src/interactive_marker_helpers.cpp
moveit_ros/robot_interaction/src/kinematic_options.cpp
moveit_ros/robot_interaction/src/kinematic_options_map.cpp
moveit_ros/robot_interaction/src/robot_interaction.cpp

Siphoned from PR #195
The only thing missing is the tests for this module. Maybe someone can take over from me while I go forward on breaking up the move_group PR #187 ?

Port Robot interaction to ROS2

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

Delete an unused line in getCommandFrameTransform

---

moveit_demo_nodes/run_move_group/README.md
moveit_demo_nodes/run_moveit_cpp/README.md

Update MoveIt logo URLs in the demos' README

---

.travis.yml
moveit2.repos

~~Expected to fail because of #242.~~
This resets workspace and moveit_ci branches to default ones.

Workspace and CI fixes

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp

***__~~TIP~~__***
Replaced the redundant namespaces 
> robot_state:: 
> robot_model:: 
with the actual namespace 
> moveit::core::

Enhancement 263 

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

Fix interactive markers not visible in motion planning plugin

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/config/demo_rviz_pose_tracking.rviz
moveit_ros/moveit_servo/config/panda_simulated_config_pose_tracking.yaml
moveit_ros/moveit_servo/include/moveit_servo/make_shared_from_pool.h
moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h
moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/cpp_interface_demo/pose_tracking_demo.cpp
moveit_ros/moveit_servo/src/cpp_interface_demo/servo_cpp_interface_demo.cpp
moveit_ros/moveit_servo/src/cpp_interface_example/pose_tracking_demo.cpp
moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/test/config/pose_tracking_settings.yaml
moveit_ros/moveit_servo/test/launch/test_servo_collision.test.py
moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
moveit_ros/moveit_servo/test/pose_tracking_test.cpp

Ported pose tracking from moveit_servo to ROS2

port pose tracking

---

moveit/CMakeLists.txt
moveit/scripts/create_maintainer_table.py
moveit/scripts/create_readme_table.py

Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
This enables (and fixes up issues found by) these linters in the `moveit` package:
* ament_copyright
* ament_flake8
* ament_pep257

Enable linting of moveit package

---

.docker/ci/Dockerfile
.docker/source/Dockerfile

This should fix https://github.com/ros-planning/moveit2/issues/403

Clone moveit2 in source docker file

---

moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/package.xml

1- Re-add moveit_ros_warehouse to moveit_ros_planning_interface
2- Remove warehouse_ros_mongo from moveit_ros_planning_interface test depends (this should fix the buildfarm issue https://build.ros2.org/job/Fdev__moveit__ubuntu_focal_amd64/changes)

Re-add moveit_ros_warehouse for moveit_ros_planning_interface

---

moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py

Depends on https://github.com/ros-planning/moveit_resources/pull/73

Load panda_hand_controller in run_move_group

---

moveit_ros/moveit_servo/include/moveit_servo/servo.h

Fixes https://github.com/ros-planning/moveit2/pull/521

Remove faulty gtest include

---

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp

This PR fixes two things
1- The previous PR that added the declaration for this parameterw introduced a new parameter called `has_position_limits` and it has to be true to override the max/min_positions which breaks all the existing setups, so I did revert it
2- Similar to https://github.com/ros-planning/moveit2/commit/45dfbae5baab6c1d1dddfff04af68f83cbff7464 it fixes unwanted overrides for the position limits

Fix joint's position limits loading

---

moveit_ros/hybrid_planning/global_planner/src/global_planner_component.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/include/moveit/hybrid_planning_manager/hybrid_planning_manager.h
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/include/moveit/hybrid_planning_manager/planner_logic_interface.h
moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/planner_logic_plugins/include/moveit/planner_logic_plugins/replan_invalidated_trajectory.h
moveit_ros/hybrid_planning/hybrid_planning_manager/planner_logic_plugins/include/moveit/planner_logic_plugins/single_plan_execution.h
moveit_ros/hybrid_planning/hybrid_planning_manager/planner_logic_plugins/src/replan_invalidated_trajectory.cpp
moveit_ros/hybrid_planning/hybrid_planning_manager/planner_logic_plugins/src/single_plan_execution.cpp
moveit_ros/hybrid_planning/local_planner/local_constraint_solver_plugins/include/moveit/local_constraint_solver_plugins/forward_trajectory.h
moveit_ros/hybrid_planning/local_planner/local_constraint_solver_plugins/src/forward_trajectory.cpp
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/local_constraint_solver_interface.h
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/local_planner_component.h
moveit_ros/hybrid_planning/local_planner/local_planner_component/include/moveit/local_planner/trajectory_operator_interface.h
moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
moveit_ros/hybrid_planning/local_planner/trajectory_operator_plugins/include/moveit/trajectory_operator_plugins/simple_sampler.h
moveit_ros/hybrid_planning/local_planner/trajectory_operator_plugins/src/simple_sampler.cpp
moveit_ros/hybrid_planning/test/config/demo_controller.yaml
moveit_ros/hybrid_planning/test/config/local_planner.yaml

Address changes requested by @AdamPettinger 

Address hybrid planning review

---

moveit_ros/moveit_servo/include/moveit_servo/low_pass_filter.h

Port of https://github.com/ros-planning/moveit/pull/2722

Refactor moveit_servo::LowPassFilter to be assignable

---

.github/workflows/build_and_test_galactic.yaml
moveit2_galactic.repos
moveit_demo_nodes/run_move_group/package.xml
moveit_demo_nodes/run_moveit_cpp/package.xml
moveit_demo_nodes/run_ompl_constrained_planning/package.xml

Add missing exec dependencies to demo packages

---

moveit2.repos

Fix: https://github.com/ros-planning/moveit2/issues/588#issuecomment-891789521

Use foxy branch for geometric_shapes

---

moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor_middleware_handle.hpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp
moveit_ros/planning/planning_scene_monitor/test/current_state_monitor_tests.cpp

This fixes a bug I found while trying to use the servo demo on rolling.

Wait for complete state duration fix

---

.github/workflows/build_and_test_rolling.yaml

Now that https://github.com/osrf/infrastructure/issues/5#issuecomment-892786325 is fixed this re-enables testing on rolling-testing.

Enable testing on rolling-testing

---

moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py

[foxy] Fix missing include in servo example

---

moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
moveit_core/robot_state/test/robot_state_test.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py

A chunk of synced commits with a hopefully reviewable diff.
(we need a couple of these, 103 commits to go)

Sync MoveIt 1

---

moveit_ros/moveit_servo/launch/servo_example.launch.py

This is a small mistake from #621. Probably mine.

Delete duplicate entry in Servo launch file

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

Publish singularity condition to ~/servo_server/condition to help understand servo behavior around singularities
This is broken out from https://github.com/ros-planning/moveit2/pull/620

Publish singularity condition to topic

---

moveit_core/collision_detection_bullet/CMakeLists.txt

Fix: https://github.com/ros-planning/moveit2/issues/655

collision_detection_bullet: Fix target installation

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

moveit_ros_control_interface: Fix dangling reference

---

moveit_ros/moveit_servo/src/servo_parameters.cpp

Fix std::placeholders namespace conflict

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_loader.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

- Prefer std::make_shared over new operator (#2756)
- Improve readability of comment
- Servo: minor fixups (#2759)

Sync with MoveIt 1

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

MoveitCpp - path constraints added from PlanningComponent (backport #752)

---

moveit_ros/planning_interface/common_planning_interface_objects/include/moveit/common_planning_interface_objects/common_objects.h
moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

Fix: https://github.com/ros-planning/moveit2/issues/780

[foxy]: Backport fixes to race-condition causing exceptions

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_plugin.h
moveit_core/kinematics_base/CMakeLists.txt
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch

Resolves #788 
Sync these commits from MoveIt with a merge:
```
* [2021-07-17] [bec399ae8] | Fix Windows CI (#2776) {{Robert Haschke}} 
* [2021-07-17] [8ff9cdf7b] | Revert $(dirname) use for rviz config file {{Robert Haschke}} 
* [2021-07-16] [442c3202a] | Fix MSA templates (#2769) {{Robert Haschke}} 
* [2021-07-12] [e8b54db3a] | CI: Switch to Noetic builds by default (#2765) {{Robert Haschke}} 
*   [2021-07-09] [7d31f8186] | Merge pull request #2758 from ubi-agni/master {{Michael Görner}} 
|\  
| * [2021-07-09] [7996ff82c] | Fixup devel-space build after #2604 {{Robert Haschke}} 
| * [2021-07-08] [c99ea93c7] | Cleanup CollisionDetectorAllocatorTemplate::getName() {{Robert Haschke}} 
* [2021-07-09] [a0eeb70ae] | controller manager: enclose name in quotes (#2761) {{G.A. vd. Hoorn}} 
```

Sync with MoveIt1

---

moveit_commander/src/moveit_commander/move_group.py
moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_service.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

Sync with MoveIt

---

.github/mergify.yml

See comment here: https://github.com/ros-planning/moveit2/pull/817#issuecomment-973984413

Fix mergify falsely tagging Foxy.io

---

.github/workflows/ci.yaml

This will put ccache stats in the log to make sure it is working as expected.

Log ccache stats

---

moveit_ros/hybrid_planning/test/hybrid_planning_demo_node.cpp

Replace a comma with a semicolon. I am a little bit confused, why did this build before and why doesn't CI complain about this?

Fix syntax

---

moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp

A small correction from #932. This was left over from testing.

Fix action name

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_env.h
moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h
moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h
moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h
moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/robot_model/include/moveit/robot_model/joint_model.h
moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/include/moveit/robot_model/link_model.h
moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_experimental/kinematics_constraint_aware/src/kinematics_constraint_aware.cpp
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast.h
moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
moveit_planners/sbpl/core/sbpl_interface/include/sbpl_interface/dummy_environment.h
moveit_planners/sbpl/core/sbpl_interface/include/sbpl_interface/environment_chain3d.h
moveit_planners/sbpl/core/sbpl_interface/include/sbpl_interface/environment_chain3d_types.h
moveit_planners/sbpl/core/sbpl_interface/src/environment_chain3d.cpp
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/include/ikfast.h
moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_solver.cpp
moveit_ros/manipulation/pick_place/src/place.cpp
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp
moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/serialize_msg.h
moveit_ros/robot_interaction/include/moveit/robot_interaction/locked_robot_state.h
moveit_setup_assistant/src/widgets/planning_groups_widget.cpp
moveit_setup_assistant/src/widgets/ros_controllers_widget.cpp

Replace NULL with nullptr throughout the project as per #841

Replaced NULL with nullptr

---

.github/mergify.yml

I thought this has already been added, but now this is fixed anyway

Mergify configuration for Galactic backport

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
.github/workflows/format.yaml
.github/workflows/prerelease.yaml
README.md

Updates build badges and workflows for `galactic`
Fixes #748

Galactic branch

---

.github/workflows/prerelease.yaml

Remove other distros from pre-release on foxy branch.

Pre-release foxy

---

Doxyfile

Make user enter the directory for Doxygen reference generation.

Set doxygen reference generation directory

---

moveit2.repos

Update moveit2.repos to ros2 for moveit_resources

---

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp

Fix mixed-up implementations in TfSubscription creation

---

moveit_configs_utils/moveit_configs_utils/launch_utils.py
moveit_configs_utils/moveit_configs_utils/launches.py
moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
moveit_configs_utils/package.xml

Related to my MSA work, here's some additional Python code for creating launch files using @JafarAbdi's `moveit_configs_utils`. (See #591) 
* Adds `package_path` as an attribute in `MoveItConfigs` class
* Adds a launch utility library with two common MoveIt launch file tasks
* Declare a launch argument with a boolean value
* Add a node with which you can enable debugging with a flag. 
* Adds a collection of basic launch files that replace launch files from ROS 1
* `generate_rsp_launch` launches a `robot_state_publisher`
* `generate_rviz_launch` replaces `moveit_rviz.launch`
* `generate_assistant_launch` replaces `setup_assistant.launch`
* `generate_warehouse_launch` replaces `default_warehouse_db.launch/warehouse.launch/warehouse_settings.launch.xml`
This lays the groundwork for being …

New Launch Files using moveit_configs_utils

---

moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/CMakeLists.txt

These flags are not available on Windows.

Fix prbt_ikfast win compilation

---

moveit_setup_assistant/moveit_setup_framework/src/package_settings_config.cpp

Replacement for #1201 in the `feature/msa` branch. 

[MSA] Fix for long TLDs

---

moveit_ros/planning_interface/test/move_group_ompl_constraints_test.cpp

Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
Fix a deprecation warning.

Fix deprecated

---

.docker/ci/Dockerfile

Fix bash syntax in CI Dockerfile

---

moveit_core/collision_detection_bullet/CMakeLists.txt

Signed-off-by: Tyler Weaver <tyler@picknik.ai>
I needed this change to get a source build working in rolling.

Add missing dependencies to cmake

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
README.md

This enables Humble CI jobs, the docker images were already built successfully https://github.com/ros-planning/moveit2/pkgs/container/moveit2

Humble Support

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
moveit_setup_assistant/moveit_setup_assistant/src/setup_assistant_widget.cpp
moveit_setup_assistant/moveit_setup_controllers/src/controllers_widget.cpp
moveit_setup_assistant/moveit_setup_framework/templates/config/cartesian_limits.yaml
moveit_setup_assistant/moveit_setup_srdf_plugins/moveit_setup_framework_plugins.xml

- Enable compilation of controllers
- Add user warning for hand generating controllers
- Issue a warning instead of raising an exception if the controllers haven't been found

[MSA] Workaround to launch files without controllers

---

moveit2.repos

Inspired by #1294, we should not need anything to build from the source since the humble and rolling syncs are out!

Remove everything from repos

---

.github/workflows/format.yaml
moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp
moveit_setup_assistant/src/tools/compute_default_collisions.cpp

Although our main branch is meant to run on Ubuntu 22.04 our pre-commit was running on ubuntu-latest which still targets Ubuntu 20.04. This PR should fix this

Update pre-commit run on Ubuntu 22.04

---

moveit_ros/moveit_servo/CMakeLists.txt

Use substitutions to clean up the CMakeLists

Minor cleanup of Servo CMakeLists

---

moveit_core/collision_detection/src/collision_env.cpp
moveit_core/collision_detection/src/collision_matrix.cpp
moveit_core/collision_detection/src/collision_octomap_filter.cpp
moveit_core/collision_detection/src/collision_plugin_cache.cpp
moveit_core/collision_detection/src/collision_tools.cpp
moveit_core/collision_detection/src/world.cpp

Const'd function parameters and locally scoped variables in the collision_detection portion of of moveit_core. This PR pertains to [Const as much as possible #879](https://github.com/ros-planning/moveit2/issues/879) 

Added const to moveit_core/collision_detection per issue 879

---

moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

It was causing the function to return false even if we are missing an optinal parameter

pointcloud_octomap_updater: Don't return false when not finding optional parameter

---

moveit/package.xml
moveit_setup_assistant/moveit_setup_assistant/package.xml

Organize package xml of MSA

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
.github/workflows/format.yaml

They were still pointing to main

Switch CI target branches to humble

---

moveit_ros/planning/rdf_loader/test/test_rdf_integration.cpp

Cherry-picked f8da9512675d878c095f1421927dd6b2c2d3a291 from https://github.com/ros-planning/moveit2/pull/1170

Fix failing RDFLoader test

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp
moveit_ros/benchmarks/benchmarks/src/benchmark_execution.cpp
moveit_ros/benchmarks/src/BenchmarkExecutor.cpp

Co-authored-by: Sebastian Jahr <sebastian.jahr@picknik.ai>
Signed-off-by: Tyler Weaver <tyler@picknik.ai>

Free functions for calculating properties of trajectories

---

moveit_ros/move_group/include/moveit/move_group/move_group_capability.h

Contribution to #880, marked as explicit.

avoid implicit conversions

---

moveit_core/collision_detection/src/collision_common.cpp

Added brace intialization in move_it/collision_detection

---

moveit_core/utils/include/moveit/utils/moveit_error_code.h

Simply add the new error codes from this PR:
https://github.com/ros-planning/moveit_msgs/pull/146

Add new error types (moveit_msgs #146)

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Fixed typo in deprecation warning in ControllerManager

---

.github/workflows/ci.yaml
moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py

Fix IKFAST_TEST

---

.github/ISSUE_TEMPLATE/bug_report.md

Add this question to the issue template b/c we get quite a lot of people using Fast DDS.

Add a question about RMW type to the issue template

---

moveit2.repos
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

... and remove obsolete include. See https://github.com/ros-planning/moveit2/issues/1852#issuecomment-1375698649.

GHA: Build moveit_msgs from source

---

.docker/ci/Dockerfile
.pre-commit-config.yaml
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_utils.h
moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/constraint_samplers/src/constraint_sampler_manager.cpp
moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_parameters.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor_middleware_handle.hpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp

Switch to clang-format-14

---

moveit_kinematics/CMakeLists.txt
moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
moveit_kinematics/kdl_kinematics_plugin/CMakeLists.txt
moveit_kinematics/lma_kinematics_plugin/CMakeLists.txt
moveit_kinematics/srv_kinematics_plugin/CMakeLists.txt

Expanding on the work we started in #1786.

Install moveit_kinematics headers within additional directory

---

moveit_planners/chomp/chomp_motion_planner/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner_testutils/CMakeLists.txt
moveit_plugins/moveit_ros_control_interface/CMakeLists.txt
moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt
moveit_setup_assistant/moveit_setup_app_plugins/CMakeLists.txt
moveit_setup_assistant/moveit_setup_assistant/CMakeLists.txt
moveit_setup_assistant/moveit_setup_controllers/CMakeLists.txt

Expands on #1901. There are many more packages to fix but I'm batching packages together to make incremental progress reviewing and merging these changes.

Install headers within additional directory

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

Addresses discussion in #1862 
BREAKING CHANGE

Remove last_plan_solution_ in PlanningComponent

---

moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.h

Provide some references and equations for the Butterworth filter, especially the mystery coefficient.

Document the Butterworth filter better

---

.github/workflows/project.yaml

Reference: https://github.com/actions/add-to-project
Let's try this out with our new project.

Action for adding new issues and pull requests to project

---

.docker/ci/Dockerfile

This should fix #2038, I already have a docker job running to test this

Upgrade apt dependencies --with-new-pkgs

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

A port of [this PR](https://github.com/ros-planning/moveit/pull/3376) from MoveIt1.

Optionally mitigate Ruckig overshoot

---

moveit_kinematics/test/benchmark_ik.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/planning_link_updater.h
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_link_updater.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

Minor variable name cleanup to make the naming more consistent.

Rename kinematic_state to robot_state

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp

Address https://github.com/ros-planning/moveit2/pull/2001#pullrequestreview-1334537462

Update moveit_py 'get_planning_scene_monitor' to return NonConst

---

moveit_ros/moveit_servo/launch/servo_example.launch.py

Add the new parameter to a launch file as a means of documentation
@ibrahiminfinite can you please review?

[Servo] Document the new low-pass filter param

---

moveit_common/cmake/moveit_package.cmake
moveit_ros/hybrid_planning/test/CMakeLists.txt
moveit_ros/hybrid_planning/test/hybrid_planning_demo_node.cpp
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/src/teleop_demo/joystick_servo_example.cpp
moveit_ros/moveit_servo/test/publish_fake_jog_commands.cpp
moveit_ros/occupancy_map_monitor/CMakeLists.txt
moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp
moveit_ros/perception/semantic_world/CMakeLists.txt
moveit_ros/perception/semantic_world/src/semantic_world.cpp
moveit_ros/planning/planning_components_tools/CMakeLists.txt
moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp
moveit_ros/planning/planning_components_tools/src/visualize_robot_collision_volume.cpp
moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/demos/demo_scene.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp
moveit_ros/warehouse/src/broadcast.cpp
moveit_ros/warehouse/src/save_to_warehouse.cpp

Address error happening here https://github.com/ros-planning/moveit2/pull/2020#pullrequestreview-1383635249
```
Starting >>> moveit_resources_prbt_ikfast_manipulator_plugin
--- stderr: moveit_ros_occupancy_map_monitor
In file included from /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp:48:
/opt/ros/rolling/include/rclcpp/rclcpp/qos_event.hpp:18:2: error: This header is obsolete, please include rclcpp/event_handler.hpp instead [-Werror,-W#warnings]
#warning This header is obsolete, please include rclcpp/event_handler.hpp instead
^
1 error generated.
gmake[2]: *** [CMakeFiles/moveit_ros_occupancy_map_server.dir/build.make:76: CMakeFiles/moveit_ros_occupancy_map_server.dir/src/occupancy_map_server.cpp.o] Error 1 …
```

Switch from qos_event.hpp to event_handler.hpp

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

This PR renames variables within `ServoCalcs` class to improve readability.

[Servo] Change variable names in `ServoCalcs` for improved readability

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

Fix: https://github.com/ros-planning/moveit2/issues/2105
We have two bugs here:
1- We used `right` to delete the controller's resources, but `left` is what we should use for that ([see](https://github.com/ros-planning/moveit2/blob/ac104953348ece6c0e134cc85447a0cc2e7df32c/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp#L415))
2- We loop through the resources and insert them all with the same `left` value ([controller_manager_plugin.cpp#L415](https://github.com/ros-planning/moveit2/blob/ac104953348ece6c0e134cc85447a0cc2e7df32c/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp#L415)), so we always end-up with one element, to fix this I update the `left` type to be `boost::bimaps::unordered_multiset_of<std::string>`, see …

Fix controller_manager_plugin's switch controllers functionality

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/include/moveit_servo/servo_node.h

People were confused why Servo was paused but it continued to published commands.

Document pausing better

---

moveit_common/cmake/moveit_package.cmake
moveit_ros/hybrid_planning/test/CMakeLists.txt
moveit_ros/hybrid_planning/test/hybrid_planning_demo_node.cpp
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/src/teleop_demo/joystick_servo_example.cpp
moveit_ros/moveit_servo/test/publish_fake_jog_commands.cpp
moveit_ros/occupancy_map_monitor/CMakeLists.txt
moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp
moveit_ros/perception/semantic_world/CMakeLists.txt
moveit_ros/perception/semantic_world/src/semantic_world.cpp
moveit_ros/planning/planning_components_tools/CMakeLists.txt
moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp
moveit_ros/planning/planning_components_tools/src/visualize_robot_collision_volume.cpp
moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/demos/demo_scene.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor_middleware_handle.cpp
moveit_ros/warehouse/src/broadcast.cpp
moveit_ros/warehouse/src/save_to_warehouse.cpp

Fixes https://github.com/ros-planning/moveit2/pull/2111#pullrequestreview-1393472939

Replace check for the ROS_DISTRO env variable with a check for the rclcpp version

---

moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.h
moveit_core/online_signal_smoothing/src/butterworth_filter.cpp
moveit_core/package.xml

Clean up some issues I noticed while reviewing #2129

Alphabetize, smart pointer not needed

---

.github/workflows/ci.yaml
sonar-project.properties

This is for testing using SonarCloud static analysis in our CI.

Add sonar cloud testing to CI

---

.github/workflows/ci.yaml
.github/workflows/sonar.yaml
sonar-project.properties

This enables sending the coverage report to sonar cloud.

Run SonarCloud only on push

---

moveit_ros/move_group/src/move_group.cpp

Fix loading multi planners capabilities

fix move_group capabilities loading

---

moveit_core/robot_model/src/robot_model.cpp

Fix typo in error message

---

.github/mergify.yml

Add mergify iron backport label

---

.gitignore

Fix typo in .gitignore

---

moveit_setup_assistant/moveit_setup_srdf_plugins/src/compute_default_collisions.cpp

This pull request fixes typos in `moveit_setup_assistant/moveit_setup_srdf_plugins/src/compute_default_collisions.cpp`. The typo fixes are:
1. direcitonal -> directional
2. Repeatidly -> Repeatedly

fix typos in compute_default_collisions.cpp

---

moveit_core/online_signal_smoothing/CMakeLists.txt
moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.h
moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/smoothing_base_class.h
moveit_core/online_signal_smoothing/src/butterworth_filter.cpp
moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/include/moveit_servo/utils/datatypes.hpp
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/utils/common.cpp

Replaces #2405 since I couldn't push to Ibrahim's fork.
@ibrahiminfinite

Smoothing plugin API update and bug fix

---

moveit_py/src/moveit/moveit_core/robot_trajectory/robot_trajectory.cpp

https://github.com/ros-planning/moveit2/pull/2471 was not enough... fixing more stuff, and also added missing docstrings.

More fixes to Python bindings docstrings

---

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh

As per https://github.com/osrf/docker_images/issues/697

Update ROS Snapshots GPG key

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp

(moveit_py) execute needs a `gil_scoped_release`

---

moveit_core/planning_interface/include/moveit/planning_interface/planning_request_adapter.h

Add missing header

---

moveit_core/online_signal_smoothing/CMakeLists.txt
moveit_core/utils/CMakeLists.txt

Add missing pluginlib dependency

---

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h

Fix doc reference to non-existent function

---

moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py

As requested in the discussion in #2684 (Fix xargo args loading issue), I'm providing a PR to merge the bugfix into Humble as well.

Backport of #2172 and #2684 into Humble

---

moveit2.repos

#2807 has a merge conflict and I can't seem to get mergify to resolve it. 
Created this PR to expedite the resolution without fighting mergify.

Backport #2802 to humble

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Fixes:
- https://github.com/moveit/moveit2/issues/2839

Add getNodeHandle impl

---

moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp

Fixes #2947 
Edited the typo in line from "trajactory" to "trajectory"

fixed typo from trajactory to trajectory

---

README.md

Fix #2946 
Added a different url path for the image

Correct moveit logo path in readme.md file

---

.github/mergify.yml

Galactic Geochelone development ended 1 year and 8 months ago (09 Dec 2022) Foxy Fitzroy	development ended 1 year and 3 months ago (01 May 2023)
- [* ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

remove old ros distro into  mergify.yml

---

.github/workflows/docker.yaml

This is why the humble image wasnt pushed!!!

[Humble] Switch from ros-planning to moveit org

---

moveit_py/CMakeLists.txt

aligned cmake version to highest requested by moveit2
- [ *] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

Aligned CMake version

---

moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.h

Fixed include path for moveit_butterworth_parameters.hpp

---

moveit_ros/moveit_servo/demos/servo_keyboard_input.cpp

Add support for Windows in servo_keyboard_input demo.

servo_keyboard_input: Add Windows support

---

moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

Fix https://github.com/moveit/moveit2/issues/3286

fix: pointcloud_octomap_updater not cleaning objects at max_range

---

moveit_configs_utils/default_configs/ompl_defaults.yaml

This has probably never worked.
See https://github.com/moveit/moveit2/issues/2088.

Update ompl_defaults.yaml to not have an invalid AnytimePathShortening configuration

---

moveit_py/src/moveit/moveit_ros/trajectory_execution_manager/trajectory_execution_manager.hpp

[MoveitPy] Allow conversion from list[str] to std::vector<std::string> for controllers

---

moveit_ros/moveit_servo/config/panda_simulated_config.yaml

Just minor typo fix.
PS:> I just saw typo and it bugged me a bit. This is a very small Pull Request.

Minor Typo Fix in simulated Panda servo config

---

moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

When the `sensor_3d.yaml` file with `PointCloudUpdater` is used, but some required parameters are missing, `moveit_group` node fails to start with the error log: `Failed to configure updater of type PointCloudUpdater`, which doesn't give any clues of what's actually failed.
This PR is aimed at providing more user-friendly log messages that explicitly tell what is missing, e.g.:
```
[move_group-2] [ERROR] [1750954248.813778881] [move_group]: Missing parameters under 'vision_perception_node': , 'max_update_rate', 'filtered_cloud_topic'
[move_group-2] [ERROR] [1750954248.814011991] [move_group.moveit.moveit.ros.occupancy_map_monitor]: Failed to configure updater of type PointCloudUpdater
```
The changes are done only in the `pointcloud_octomap_updater.cpp`, but if accepted, it can also be …

moveit_ros/perception/pointcloud_octomap_updater: log missing parameters
